// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"reflect"
	"github.com/petergtz/pegomock"
	secrets "github.com/jenkins-x/jx/pkg/io/secrets"
)

func AnySecretsSecretsLocationKind() secrets.SecretsLocationKind {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(secrets.SecretsLocationKind))(nil)).Elem()))
	var nullValue secrets.SecretsLocationKind
	return nullValue
}

func EqSecretsSecretsLocationKind(value secrets.SecretsLocationKind) secrets.SecretsLocationKind {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue secrets.SecretsLocationKind
	return nullValue
}
