// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"reflect"
	"github.com/petergtz/pegomock"
	table "github.com/jenkins-x/jx/pkg/table"
)

func AnyTableTable() table.Table {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(table.Table))(nil)).Elem()))
	var nullValue table.Table
	return nullValue
}

func EqTableTable(value table.Table) table.Table {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue table.Table
	return nullValue
}
