apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  creationTimestamp: null
  name: abayer-js-test-repo-build-pack-1
  namespace: jx
spec:
  params:
    - default: 0.0.1
      description: the version number for this pipeline which is used as a tag on docker
        images and helm charts
      name: version
  resources:
    - name: abayer-js-test-repo-build-pack
      type: git
  tasks:
    - name: from-build-pack
      params:
        - name: version
          value: ${params.version}
      resources:
        inputs:
          - name: workspace
            resource: abayer-js-test-repo-build-pack
      taskRef:
        name: abayer-js-test-repo-build-pack-from-build-pack-1
status: {}