apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  creationTimestamp: null
  labels:
    branch: really-long
    build: "1"
    jenkins.io/pipelineType: build
    owner: abayer
    repository: js-test-repo
  name: abayer-js-test-repo-really-long-shnql-1
spec:
  params:
  - name: version
    value: 0.0.1
  pipelineRef:
    apiVersion: tekton.dev/v1alpha1
    name: abayer-js-test-repo-really-long-shnql-1
  podTemplate:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              tekton.dev/pipelineRun: abayer-js-test-repo-really-long-shnql-1
          topologyKey: kubernetes.io/hostname
  resources:
  - name: abayer-js-test-repo-really-long-shnql
    resourceRef:
      apiVersion: tekton.dev/v1alpha1
      name: abayer-js-test-repo-really-long-shnql
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
