FROM alpine:3.16.2

ARG BUILD_DATE
ARG VERSION
ARG REVISION
ARG TARGETARCH
ARG TARGETOS

LABEL maintainer="jenkins-x"

RUN addgroup -S app \
    && adduser -S -g app app \
    && apk --no-cache add \
    ca-certificates curl git git-lfs make netcat-openbsd bash yq

ENV JX_HOME /root/.jx
ENV JX3_HOME /root/.jx
ENV HELM_DATA_HOME /root/.local/share/helm

RUN echo using jx version ${VERSION} and OS ${TARGETOS} arch ${TARGETARCH} && \
  mkdir -p /home/.jx3 && \
  curl -L https://github.com/jenkins-x/jx/releases/download/v${VERSION}/jx-${TARGETOS}-${TARGETARCH}.tar.gz | tar xzv && \
  mv jx /usr/bin

RUN jx upgrade plugins --boot --path /usr/bin && \
  jx secret plugins upgrade

#RUN chown -R app:app /usr/bin/jx /home
#USER app



