extends:
  file: base-pipeline.yaml
pipelines:
  pullRequest:
    build:
      steps:
      - container: maven
        steps:
        - sh: export VERSION=$PREVIEW_VERSION && skaffold build -f skaffold.yaml
    postBuild:
      steps:
      - container: maven
        steps:
        - sh: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:$PREVIEW_VERSION
    promote:
      steps:
      - dir: ./charts/preview
        steps:
        - container: maven
          steps:
          - sh: make preview
          - sh: jx preview --app $APP_NAME --dir ../..

  release:
    build:
      steps:
      - container: maven
        steps:
        - sh: export VERSION=`cat VERSION` && skaffold build -f skaffold.yaml
        - sh: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:\$(cat VERSION)
    promote:
      steps:
      - dir: ./charts/REPLACE_ME_APP_NAME
        steps:
        - container: maven
          steps:
          - sh: jx step changelog --version v\$(cat ../../VERSION)
          - comment: release the helm chart
            sh: jx step helm release
          - comment: promote through all 'Auto' promotion Environments
            sh: jx promote -b --all-auto --timeout 1h --version \$(cat ../../VERSION)
