---
swagger: "2.0"
info:
  description: "Code against the Bitbucket API to automate simple tasks, embed Bitbucket\
    \ data into your own site, build mobile or desktop apps, or even add custom UI\
    \ add-ons into Bitbucket itself using the Connect framework."
  version: "2.0"
  title: "Bitbucket API"
  termsOfService: "https://www.atlassian.com/legal/customer-agreement"
  contact:
    name: "Bitbucket Support"
    url: "https://support.atlassian.com/bitbucket-cloud/"
    email: "support@bitbucket.org"
host: "api.bitbucket.org"
basePath: "/2.0"
tags:
- name: "users"
  description: ""
- name: "teams"
  description: ""
- name: "repositories"
  description: ""
- name: "source"
  description: "Browse the source code in the repository and\n                   \
    \           create new commits by uploading."
- name: "refs"
  description: ""
- name: "commits"
  description: ""
- name: "pullrequests"
  description: ""
- name: "issue_tracker"
  description: "The issue resources provide functionality for getting information\
    \ on\nissues in an issue tracker, creating new issues, updating them and deleting\n\
    them.\n\nYou can access public issues without authentication, but you can't gain\
    \ access\nto private repositories' issues. By authenticating, you will get the\
    \ ability\nto create issues, as well as access to updating data or deleting issues\
    \ you\nhave access to."
- name: "wiki"
  description: ""
- name: "downloads"
  description: ""
- name: "snippets"
  description: ""
- name: "webhooks"
  description: "Webhooks provide a way to configure Bitbucket Cloud to make requests\
    \ to\nyour server (or another external service) whenever certain events occur\
    \ in\nBitbucket Cloud.\n\nA webhook consists of:\n\n* A subject -- The resource\
    \ that generates the events. Currently, this resource\n  is the repository, user\
    \ account, or team where you create the webhook.\n* One or more event -- The default\
    \ event is a repository push, but you can\n  select multiple events that can trigger\
    \ the webhook.\n* A URL -- The endpoint where you want Bitbucket to send the event\
    \ payloads\n  when a matching event happens.\n\nThere are two parts to getting\
    \ a webhook to work: creating the webhook and\ntriggering the webhook. After you\
    \ create a webhook for an event, every time\nthat event occurs, Bitbucket sends\
    \ a payload request that describes the event\nto the specified URL. Thus, you\
    \ can think of webhooks as a kind of\nnotification system.\n\nUse webhooks to\
    \ integrate applications with Bitbucket Cloud. The following\nuse cases provides\
    \ examples of when you would want to use webhooks:\n\n* Every time a user pushes\
    \ commits in a repository, you may want to notify\n  your CI server to start a\
    \ build.\n* Every time a user pushes commits or creates a pull request, you may\
    \ want to\n  display a notification in your application.\n"
- name: "commitstatuses"
  description: "Commit statuses provide a way to tag commits with meta data,\nlike\
    \ automated build results.\n"
- name: "branchrestrictions"
  description: "Repository owners and administrators can set branch management\nrules\
    \ on a repository that control what can be pushed by whom.\nThrough these rules,\
    \ you can enforce a project or team\nworkflow. For example, owners or administrators\
    \ can:\n\n* Limit push powers\n* Prevent branch (bookmark) deletion\n* Prevent\
    \ history re-writes (Git only)\n"
- name: "projects"
  description: "Bitbucket Cloud projects make it easier for teams to focus on\na goal,\
    \ product, or process by organizing their repositories.\n"
- name: "pipelines"
  description: "Bitbucket Pipelines brings continuous delivery to Bitbucket\nCloud,\
    \ empowering teams with full branching to deployment\nvisibility and faster feedback\
    \ loops.\n"
schemes:
- "https"
paths:
  /repositories/{username}/{repo_slug}/refs/branches/{name}:
    get:
      tags:
      - "refs"
      description: ""
      security:
      - oauth2:
        - "repository"
      - basic: []
      - api_key: []
  /teams/{username}/following:
    get:
      tags:
      - "teams"
      description: "Returns the list of accounts this team is following."
      security:
      - oauth2:
        - "account"
      - basic: []
      - api_key: []
  /user/permissions/repositories:
    get:
      tags:
      - "repositories"
      description: "Returns an object for each repository the caller has explicit\
        \ access\nto and their effective permission — the highest level of permission\
        \ the\ncaller has. This does not return public repositories that the user\
        \ was\nnot granted any specific permission in, and does not distinguish between\n\
        direct and indirect privileges.\n\nPermissions can be:\n\n* `admin`\n* `write`\n\
        * `read`\n\nExample:\n\n```\n$ curl https://api.bitbucket.org/2.0/user/permissions/repositories\n\
        \n{\n  \"pagelen\": 10,\n  \"values\": [\n    {\n      \"type\": \"repository_permission\"\
        ,\n      \"user\": {\n        \"type\": \"user\",\n        \"username\": \"\
        evzijst\",\n        \"display_name\": \"Erik van Zijst\",\n        \"uuid\"\
        : \"{d301aafa-d676-4ee0-88be-962be7417567}\"\n      },\n      \"repository\"\
        : {\n        \"type\": \"repository\",\n        \"name\": \"geordi\",\n  \
        \      \"full_name\": \"bitbucket/geordi\",\n        \"uuid\": \"{85d08b4e-571d-44e9-a507-fa476535aa98}\"\
        \n      },\n      \"permission\": \"admin\"\n    }\n  ],\n  \"page\": 1,\n\
        \  \"size\": 1\n}\n```\n\nResults may be further [filtered or sorted](../../../meta/filtering)\
        \ by\nrepository or permission by adding the following query string\nparameters:\n\
        \n* `q=repository.name=\"geordi\"` or `q=permission>\"read\"`\n* `sort=repository.name`\n\
        \nNote that the query parameter values need to be URL escaped so that `=`\n\
        would become `%3D`."
      security:
      - oauth2:
        - "account"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/commit/{sha}/comments/{comment_id}:
    get:
      tags:
      - "commits"
      description: "Returns the specified commit comment."
      security:
      - oauth2:
        - "repository"
      - basic: []
      - api_key: []
  /teams/{username}/pipelines_config/variables/{variable_uuid}:
    get:
      tags:
      - "pipelines"
      description: "Retrieve a team level variable."
      operationId: "getPipelineVariableForTeam"
    put:
      tags:
      - "pipelines"
      description: "Update a team level variable."
      operationId: "updatePipelineVariableForTeam"
    delete:
      tags:
      - "pipelines"
      description: "Delete a team level variable."
      operationId: "deletePipelineVariableForTeam"
  /repositories/{username}/{repo_slug}/hooks:
    get:
      tags:
      - "repositories"
      - "webhooks"
      description: "Returns a paginated list of webhooks installed on this repository."
      security:
      - oauth2:
        - "webhook"
      - basic: []
      - api_key: []
    post:
      tags:
      - "repositories"
      - "webhooks"
      description: "Creates a new webhook on the specified repository.\n\nExample:\n\
        \n```\n$ curl -X POST -u credentials -H 'Content-Type: application/json' \
        \          https://api.bitbucket.org/2.0/repositories/username/slug/hooks\
        \           -d '\n    {\n      \"description\": \"Webhook Description\",\n\
        \      \"url\": \"https://example.com/\",\n      \"active\": true,\n     \
        \ \"events\": [\n        \"repo:push\",\n        \"issue:created\",\n    \
        \    \"issue:updated\"\n      ]\n    }'\n```\n\nNote that this call requires\
        \ the webhook scope, as well as any scope\nthat applies to the events that\
        \ the webhook subscribes to. In the\nexample above that means: `webhook`,\
        \ `repository` and `issue`.\n\nAlso note that the `url` must properly resolve\
        \ and cannot be an\ninternal, non-routed address."
      security:
      - oauth2:
        - "webhook"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/pullrequests/{pull_request_id}/statuses:
    get:
      tags:
      - "repositories"
      - "pullrequests"
      - "commitstatuses"
      description: "Returns all statuses (e.g. build results) for the given pull\n\
        request."
      security:
      - oauth2:
        - "pullrequest"
      - basic: []
      - api_key: []
  /teams/{username}/projects/:
    get:
      tags:
      - "projects"
      description: ""
      security:
      - oauth2:
        - "project"
      - basic: []
      - api_key: []
    post:
      tags:
      - "projects"
      description: "Creates a new project.\n\nNote that the avatar has to be embedded\
        \ as either a data-url\nor a URL to an external image as shown in the examples\
        \ below:\n\n```\n$ body=$(cat << EOF\n{\n    \"name\": \"Mars Project\",\n\
        \    \"key\": \"MARS\",\n    \"description\": \"Software for colonizing mars.\"\
        ,\n    \"links\": {\n        \"avatar\": {\n            \"href\": \"data:image/gif;base64,R0lGODlhEAAQAMQAAORHHOVSKudfOulrSOp3WOyDZu6QdvCchPGolfO0o/...\"\
        \n        }\n    },\n    \"is_private\": false\n}\nEOF\n)\n$ curl -H \"Content-Type:\
        \ application/json\" \\\n       -X POST \\\n       -d \"$body\" \\\n     \
        \  https://api.bitbucket.org/2.0/teams/teams-in-space/projects/ | jq .\n{\n\
        \  // Serialized project document\n}\n```\n\nor even:\n\n```\n$ body=$(cat\
        \ << EOF\n{\n    \"name\": \"Mars Project\",\n    \"key\": \"MARS\",\n   \
        \ \"description\": \"Software for colonizing mars.\",\n    \"links\": {\n\
        \        \"avatar\": {\n            \"href\": \"http://i.imgur.com/72tRx4w.gif\"\
        \n        }\n    },\n    \"is_private\": false\n}\nEOF\n)\n$ curl -H \"Content-Type:\
        \ application/json\" \\\n       -X POST \\\n       -d \"$body\" \\\n     \
        \  https://api.bitbucket.org/2.0/teams/teams-in-space/projects/ | jq .\n{\n\
        \  // Serialized project document\n}\n```"
      security:
      - oauth2:
        - "project:write"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/issues/{issue_id}/attachments/{path}:
    get:
      tags:
      - "issue_tracker"
      description: "Returns the contents of the specified file attachment.\n\nNote\
        \ that this endpoint does not return a JSON response, but instead\nreturns\
        \ a redirect pointing to the actual file that in turn will return\nthe raw\
        \ contents.\n\nThe redirect URL contains a one-time token that has a limited\
        \ lifetime.\nAs a result, the link should not be persisted, stored, or shared."
      security:
      - oauth2:
        - "issue"
      - basic: []
      - api_key: []
    delete:
      tags:
      - "issue_tracker"
      description: "Deletes an attachment."
      security:
      - oauth2:
        - "issue:write"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/versions/{version_id}:
    get:
      tags:
      - "issue_tracker"
      description: "Returns the specified issue tracker version object."
      security:
      - oauth2:
        - "issue"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/issues/{issue_id}/vote:
    get:
      tags:
      - "issue_tracker"
      description: "Check whether the authenticated user has voted for this issue.\n\
        A 204 status code indicates that the user has voted, while a 404\nimplies\
        \ they haven't."
      security:
      - oauth2:
        - "issue"
        - "account"
      - basic: []
      - api_key: []
    put:
      tags:
      - "issue_tracker"
      description: "Vote for this issue.\n\nTo cast your vote, do an empty PUT. The\
        \ 204 status code indicates that\nthe operation was successful."
      security:
      - oauth2:
        - "issue"
        - "account:write"
      - basic: []
      - api_key: []
    delete:
      tags:
      - "issue_tracker"
      description: "Retract your vote."
      security:
      - oauth2:
        - "issue:write"
        - "account:write"
      - basic: []
      - api_key: []
  /users/{username}/pipelines_config/variables/{variable_uuid}:
    get:
      tags:
      - "pipelines"
      description: "Retrieve a user level variable."
      operationId: "getPipelineVariableForUser"
    put:
      tags:
      - "pipelines"
      description: "Update a user level variable."
      operationId: "updatePipelineVariableForUser"
    delete:
      tags:
      - "pipelines"
      description: "Delete an account level variable."
      operationId: "deletePipelineVariableForUser"
  /repositories/{username}/{repo_slug}/milestones:
    get:
      tags:
      - "issue_tracker"
      description: "Returns the milestones that have been defined in the issue tracker.\n\
        \nThis resource is only available on repositories that have the issue\ntracker\
        \ enabled."
      security:
      - oauth2:
        - "issue"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/pipelines/:
    get:
      tags:
      - "pipelines"
      description: "Find pipelines"
      operationId: "getPipelinesForRepository"
    post:
      tags:
      - "pipelines"
      description: "Endpoint to create and initiate a pipeline. \nThere are a couple\
        \ of different options to initiate a pipeline, where the payload of the request\
        \ will determine which type of pipeline will be instantiated.\n# Trigger a\
        \ Pipeline for a branch or tag\nOne way to trigger pipelines is by specifying\
        \ the reference for which you want to trigger a pipeline (e.g. a branch or\
        \ tag). \nThe specified reference will be used to determine which pipeline\
        \ definition from the `bitbucket-pipelines.yml` file will be applied to initiate\
        \ the pipeline. The pipeline will then do a clone of the repository and checkout\
        \ the latest revision of the specified reference.\n\n### Example\n\n```\n\
        $ curl -X POST -is -u username:password \\\n  -H 'Content-Type: application/json'\
        \ \\\n https://api.bitbucket.org/2.0/repositories/jeroendr/meat-demo2/pipelines/\
        \ \\\n  -d '\n  {\n    \"target\": {\n      \"ref_type\": \"branch\", \n \
        \     \"type\": \"pipeline_ref_target\", \n      \"ref_name\": \"master\"\n\
        \    }\n  }'\n```\n# Trigger a Pipeline for a commit on a branch or tag\n\
        You can initiate a pipeline for a specific commit and in the context of a\
        \ specified reference (e.g. a branch, tag or bookmark).\nThe specified reference\
        \ will be used to determine which pipeline definition from the bitbucket-pipelines.yml\
        \ file will be applied to initiate the pipeline. The pipeline will clone the\
        \ repository and then do a checkout the specified reference. \n\nThe following\
        \ reference types are supported:\n\n* `branch` \n* `named_branch`\n* `bookmark`\
        \ \n * `tag`\n\n### Example\n\n```\n$ curl -X POST -is -u username:password\
        \ \\\n  -H 'Content-Type: application/json' \\\n  https://api.bitbucket.org/2.0/repositories/jeroendr/meat-demo2/pipelines/\
        \ \\\n  -d '\n  {\n    \"target\": {\n      \"commit\": {\n        \"type\"\
        : \"commit\", \n        \"hash\": \"ce5b7431602f7cbba007062eeb55225c6e18e956\"\
        \n      }, \n      \"ref_type\": \"branch\", \n      \"type\": \"pipeline_ref_target\"\
        , \n      \"ref_name\": \"master\"\n    }\n  }'\n```\n# Trigger a specific\
        \ pipeline definition for a commit\nYou can trigger a specific pipeline that\
        \ is defined in your `bitbucket-pipelines.yml` file for a specific commit.\
        \ \nIn addition to the commit revision, you specify the type and pattern of\
        \ the selector that identifies the pipeline definition. The resulting pipeline\
        \ will then clone the repository and checkout the specified revision.\n\n\
        ### Example\n\n```\n$ curl -X POST -is -u username:password \\\n  -H 'Content-Type:\
        \ application/json' \\\n https://api.bitbucket.org/2.0/repositories/jeroendr/meat-demo2/pipelines/\
        \ \\\n -d '\n  {\n     \"target\": {\n      \"commit\": {\n         \"hash\"\
        :\"a3c4e02c9a3755eccdc3764e6ea13facdf30f923\",\n         \"type\":\"commit\"\
        \n       },\n        \"selector\": {\n           \"type\":\"custom\",\n  \
        \            \"pattern\":\"Deploy to production\"\n          },\n        \"\
        type\":\"pipeline_commit_target\"\n   }\n  }'\n```\n# Trigger a specific pipeline\
        \ definition for a commit on a branch or tag\nYou can trigger a specific pipeline\
        \ that is defined in your `bitbucket-pipelines.yml` file for a specific commit\
        \ in the context of a specified reference. \nIn addition to the commit revision,\
        \ you specify the type and pattern of the selector that identifies the pipeline\
        \ definition, as well as the reference information. The resulting pipeline\
        \ will then clone the repository a checkout the specified reference.\n\n###\
        \ Example\n\n```\n$ curl -X POST -is -u username:password \\\n  -H 'Content-Type:\
        \ application/json' \\\n https://api.bitbucket.org/2.0/repositories/jeroendr/meat-demo2/pipelines/\
        \ \\\n -d '\n  {\n     \"target\": {\n      \"commit\": {\n         \"hash\"\
        :\"a3c4e02c9a3755eccdc3764e6ea13facdf30f923\",\n         \"type\":\"commit\"\
        \n       },\n       \"selector\": {\n          \"type\": \"custom\",\n   \
        \       \"pattern\": \"Deploy to production\"\n       },\n       \"type\"\
        : \"pipeline_ref_target\",\n       \"ref_name\": \"master\",\n       \"ref_type\"\
        : \"branch\"\n     }\n  }'\n```\n"
      operationId: "createPipelineForRepository"
  /addon/linkers/{linker_key}/values:
    get:
      tags:
      - "addon"
      description: ""
      security:
      - oauth2: []
      - basic: []
      - api_key: []
    post:
      tags:
      - "addon"
      description: ""
      security:
      - oauth2: []
      - basic: []
      - api_key: []
    put:
      tags:
      - "addon"
      description: ""
      security:
      - oauth2: []
      - basic: []
      - api_key: []
    delete:
      tags:
      - "addon"
      description: ""
      security:
      - oauth2: []
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/issues/{issue_id}/changes:
    get:
      tags:
      - "issue_tracker"
      description: "Returns the list of all changes that have been made to the specified\n\
        issue. Changes are returned in chronological order with the oldest\nchange\
        \ first.\n\nEach time an issue is edited in the UI or through the API, an\
        \ immutable\nchange record is created. It also has a comment associated to\
        \ it.\n\n```\n$ curl -s https://api.bitbucket.org/2.0/repositories/evzijst/dogslow/issues/1/changes\
        \ - | jq .\n\n{\n  \"pagelen\": 20,\n  \"values\": [\n    {\n      \"changes\"\
        : {\n        \"priority\": {\n          \"new\": \"trivial\",\n          \"\
        old\": \"major\"\n        },\n        \"assignee\": {\n          \"new\":\
        \ \"\",\n          \"old\": \"evzijst\"\n        },\n        \"kind\": {\n\
        \          \"new\": \"enhancement\",\n          \"old\": \"bug\"\n       \
        \ }\n      },\n      \"links\": {\n        \"self\": {\n          \"href\"\
        : \"https://api.bitbucket.org/2.0/repositories/evzijst/dogslow/issues/1/changes/2\"\
        \n        },\n        \"html\": {\n          \"href\": \"https://bitbucket.org/evzijst/dogslow/issues/1#comment-2\"\
        \n        }\n      },\n      \"issue\": {\n        \"links\": {\n        \
        \  \"self\": {\n            \"href\": \"https://api.bitbucket.org/2.0/repositories/evzijst/dogslow/issues/1\"\
        \n          }\n        },\n        \"type\": \"issue\",\n        \"id\": 1,\n\
        \        \"repository\": {\n          \"links\": {\n            \"self\":\
        \ {\n              \"href\": \"https://api.bitbucket.org/2.0/repositories/evzijst/dogslow\"\
        \n            },\n            \"html\": {\n              \"href\": \"https://bitbucket.org/evzijst/dogslow\"\
        \n            },\n            \"avatar\": {\n              \"href\": \"https://bitbucket.org/evzijst/dogslow/avatar/32/\"\
        \n            }\n          },\n          \"type\": \"repository\",\n     \
        \     \"name\": \"dogslow\",\n          \"full_name\": \"evzijst/dogslow\"\
        ,\n          \"uuid\": \"{988b17c6-1a47-4e70-84ee-854d5f012bf6}\"\n      \
        \  },\n        \"title\": \"Updated title\"\n      },\n      \"created_on\"\
        : \"2018-03-03T00:35:28.353630+00:00\",\n      \"user\": {\n        \"username\"\
        : \"evzijst\",\n        \"display_name\": \"evzijst\",\n        \"type\":\
        \ \"user\",\n        \"uuid\": \"{aaa7972b-38af-4fb1-802d-6e3854c95778}\"\
        ,\n        \"links\": {\n          \"self\": {\n            \"href\": \"https://api.bitbucket.org/2.0/users/evzijst\"\
        \n          },\n          \"html\": {\n            \"href\": \"https://bitbucket.org/evzijst/\"\
        \n          },\n          \"avatar\": {\n            \"href\": \"https://bitbucket.org/account/evzijst/avatar/32/\"\
        \n          }\n        }\n      },\n      \"message\": {\n        \"raw\"\
        : \"Removed assignee, changed kind and priority.\",\n        \"markup\": \"\
        markdown\",\n        \"html\": \"<p>Removed assignee, changed kind and priority.</p>\"\
        ,\n        \"type\": \"rendered\"\n      },\n      \"type\": \"issue_change\"\
        ,\n      \"id\": 2\n    }\n  ],\n  \"page\": 1\n}\n```\n\nChanges support\
        \ [filtering and sorting](../../../meta/filtering) that\ncan be used to search\
        \ for specific changes. For instance, to see\nwhen an issue transitioned to\
        \ \"resolved\":\n\n```\n$ curl -s https://api.bitbucket.org/2.0/repositories/site/master/issues/1/changes\
        \ \\\n   -G --data-urlencode='q=changes.state.new = \"resolved\"'\n```\n\n\
        This resource is only available on repositories that have the issue\ntracker\
        \ enabled."
      security:
      - oauth2:
        - "issue"
      - basic: []
      - api_key: []
    post:
      tags:
      - "issue_tracker"
      description: "Makes a change to the specified issue.\n\nFor example, to change\
        \ an issue's state and assignee, create a new\nchange object that modifies\
        \ these fields:\n\n```\ncurl https://api.bitbucket.org/2.0/site/master/issues/1234/changes\
        \ \\\n  -s -u evzijst -X POST -H \"Content-Type: application/json\" \\\n \
        \ -d '{\n    \"changes\": {\n      \"assignee\": {\n        \"new\": \"evzijst\"\
        \n      },\n      \"state\": {\n        \"new\": 'resolved\"\n      }\n  \
        \  }\n    \"message\": {\n      \"raw\": \"This is now resolved.\"\n    }\n\
        \  }'\n```\n\nThe above example also includes a custom comment to go alongside\
        \ the\nchange. This comment will also be visible on the issue page in the\
        \ UI.\n\nNote that the fields of the `changes` object are strings, not objects.\n\
        This allows for immutable change log records, even after user accounts,\n\
        milestones, or other objects recorded in a change entry, get renamed or\n\
        deleted.\n\nThe assignee field stores the username. When POSTing a new change\
        \ and\nchanging the assignee, the client should also use the username in the\n\
        `changes.assignee.new` field.\n\nThis call requires authentication. Private\
        \ repositories or private\nissue trackers require the caller to authenticate\
        \ with an account that\nhas appropriate authorization."
      security:
      - oauth2:
        - "issue:write"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/refs/branches:
    get:
      tags:
      - "refs"
      description: ""
      security:
      - oauth2:
        - "repository"
      - basic: []
      - api_key: []
  /hook_events/{subject_type}:
    get:
      tags:
      - "webhooks"
      description: "Returns a paginated list of all valid webhook events for the\n\
        specified entity.\n\nThis is public data that does not require any scopes\
        \ or authentication.\n\nExample:\n\nNOTE: The following example is a truncated\
        \ response object for the `team` `subject_type`.\nWe return the same structure\
        \ for the other `subject_type` objects.\n\n```\n$ curl https://api.bitbucket.org/2.0/hook_events/team\n\
        {\n    \"page\": 1,\n    \"pagelen\": 30,\n    \"size\": 21,\n    \"values\"\
        : [\n        {\n            \"category\": \"Repository\",\n            \"\
        description\": \"Whenever a repository push occurs\",\n            \"event\"\
        : \"repo:push\",\n            \"label\": \"Push\"\n        },\n        {\n\
        \            \"category\": \"Repository\",\n            \"description\": \"\
        Whenever a repository fork occurs\",\n            \"event\": \"repo:fork\"\
        ,\n            \"label\": \"Fork\"\n        },\n        ...\n        {\n \
        \           \"category\": \"Repository\",\n            \"description\": \"\
        Whenever a repository import occurs\",\n            \"event\": \"repo:imported\"\
        ,\n            \"label\": \"Import\"\n        }\n    ]\n}\n```"
      security:
      - oauth2: []
      - basic: []
      - api_key: []
  /users/{username}/followers:
    get:
      tags:
      - "users"
      description: "Returns the list of accounts that are following this team."
      security:
      - oauth2: []
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/default-reviewers:
    get:
      tags:
      - "pullrequests"
      description: "Returns the repository's default reviewers.\n\nThese are the users\
        \ that are automatically added as reviewers on every\nnew pull request that\
        \ is created."
      security:
      - oauth2:
        - "repository:admin"
      - basic: []
      - api_key: []
  /teams/{username}/search/code:
    get:
  /teams/{username}/pipelines_config/variables/:
    get:
      tags:
      - "pipelines"
      description: "Find account level variables."
      operationId: "getPipelineVariablesForTeam"
    post:
      tags:
      - "pipelines"
      description: "Create an account level variable."
      operationId: "createPipelineVariableForTeam"
  /repositories/{username}/{repo_slug}/downloads/{filename}:
    get:
      tags:
      - "downloads"
      description: "Return a redirect to the contents of a download artifact.\n\n\
        This endpoint returns the actual file contents and not the artifact's\nmetadata.\n\
        \n    $ curl -s -L https://api.bitbucket.org/2.0/repositories/evzijst/git-tests/downloads/hello.txt\n\
        \    Hello World"
      security:
      - oauth2:
        - "repository"
      - basic: []
      - api_key: []
    delete:
      tags:
      - "downloads"
      description: "Deletes the specified download artifact from the repository."
      security:
      - oauth2:
        - "repository:write"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/commit/{node}/statuses/build/{key}:
    get:
      tags:
      - "repositories"
      - "commitstatuses"
      description: "Returns the specified build status for a commit."
      security:
      - oauth2:
        - "repository"
      - basic: []
      - api_key: []
    put:
      tags:
      - "repositories"
      - "commitstatuses"
      description: "Used to update the current status of a build status object on\
        \ the\nspecific commit.\n\nThis operation can also be used to change other\
        \ properties of the\nbuild status:\n\n* `state`\n* `name`\n* `description`\n\
        * `url`\n* `refname`\n\nThe `key` cannot be changed."
      security:
      - oauth2:
        - "repository"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/watchers:
    get:
      tags:
      - "repositories"
      description: "Returns a paginated list of all the watchers on the specified\n\
        repository."
      security:
      - oauth2:
        - "repository"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/components:
    get:
      tags:
      - "issue_tracker"
      description: "Returns the components that have been defined in the issue tracker.\n\
        \nThis resource is only available on repositories that have the issue\ntracker\
        \ enabled."
      security:
      - oauth2:
        - "issue"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/properties/{app_key}/{property_name}:
    get:
    put:
    delete:
  /snippets/{username}/{encoded_id}/commits:
    get:
      tags:
      - "snippets"
      description: "Returns the changes (commits) made on this snippet."
      security:
      - oauth2:
        - "snippet"
      - basic: []
      - api_key: []
  /users/{username}/repositories:
    get:
      tags:
      - "users"
      - "teams"
      description: "All repositories owned by a user/team. This includes private\n\
        repositories, but filtered down to the ones that the calling user has\naccess\
        \ to."
      security:
      - oauth2:
        - "repository"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/pullrequests/activity:
    get:
      tags:
      - "pullrequests"
      description: "Returns a paginated list of the pull request's activity log.\n\
        \nThis includes comments that were made by the reviewers, updates and\napprovals."
      security:
      - oauth2:
        - "pullrequest"
      - basic: []
      - api_key: []
  /snippets/{username}/{encoded_id}/comments/{comment_id}:
    get:
      tags:
      - "snippets"
      description: "Returns the specific snippet comment."
      security:
      - oauth2:
        - "snippet"
      - basic: []
      - api_key: []
    put:
      tags:
      - "snippets"
      description: "Updates a comment.\n\nComments can only be updated by their author."
      security:
      - oauth2:
        - "snippet"
      - basic: []
      - api_key: []
    delete:
      tags:
      - "snippets"
      description: "Deletes a snippet comment.\n\nComments can only be removed by\
        \ their author."
      security:
      - oauth2:
        - "snippet"
      - basic: []
      - api_key: []
  /teams/{username}/permissions:
    get:
      tags: []
      description: "Returns an object for each team permission a user on the team\
        \ has.\n\nPermissions returned are effective permissions — if a user is a\
        \ member of\nmultiple groups with distinct roles, only the highest level is\
        \ returned.\n\nPermissions can be:\n\n* `admin`\n* `collaborator`\n\nOnly\
        \ users with admin permission for the team may access this resource.\n\nExample:\n\
        \n```\n$ curl https://api.bitbucket.org/2.0/teams/atlassian_tutorial/permissions\n\
        \n{\n  \"pagelen\": 10,\n  \"values\": [\n    {\n      \"permission\": \"\
        admin\",\n      \"type\": \"team_permission\",\n      \"user\": {\n      \
        \  \"type\": \"user\",\n        \"username\": \"evzijst\",\n        \"display_name\"\
        : \"Erik van Zijst\",\n        \"uuid\": \"{d301aafa-d676-4ee0-88be-962be7417567}\"\
        \n      },\n      \"team\": {\n        \"username\": \"bitbucket\",\n    \
        \    \"display_name\": \"Atlassian Bitbucket\",\n        \"uuid\": \"{4cc6108a-a241-4db0-96a5-64347ac04f87}\"\
        \n      }\n    },\n    {\n      \"permission\": \"collaborator\",\n      \"\
        type\": \"team_permission\",\n      \"user\": {\n        \"type\": \"user\"\
        ,\n        \"username\": \"seanaty\",\n        \"display_name\": \"Sean Conaty\"\
        ,\n        \"uuid\": \"{504c3b62-8120-4f0c-a7bc-87800b9d6f70}\"\n      },\n\
        \      \"team\": {\n        \"username\": \"bitbucket\",\n        \"display_name\"\
        : \"Atlassian Bitbucket\",\n        \"uuid\": \"{4cc6108a-a241-4db0-96a5-64347ac04f87}\"\
        \n      }\n    }\n  ],\n  \"page\": 1,\n  \"size\": 2\n}\n```\n\nResults may\
        \ be further [filtered or sorted](../../../meta/filtering) by\nteam, user,\
        \ or permission by adding the following query string\nparameters:\n\n* `q=user.username=\"\
        evzijst\"` or `q=permission=\"admin\"`\n* `sort=team.display_name`\n\nNote\
        \ that the query parameter values need to be URL escaped so that `=`\nwould\
        \ become `%3D`."
      security:
      - oauth2:
        - "team"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/diff/{spec}:
    get:
      tags:
      - "commits"
      description: "Produces a raw, git-style diff for either a single commit (diffed\n\
        against its first parent), or a revspec of 2 commits (e.g.\n`3a8b42..9ff173`\
        \ where the first commit represents the source and the\nsecond commit the\
        \ destination).\n\nIn case of the latter (diffing a revspec), a 3-way diff,\
        \ or merge diff,\nis computed. This shows the changes introduced by the left\
        \ branch\n(`3a8b42` in our example) as compared againt the right branch\n\
        (`9ff173`).\n\nThis is equivalent to merging the left branch into the right\
        \ branch and\nthen computing the diff of the merge commit against its first\
        \ parent\n(the right branch). This follows the same behavior as pull requests\n\
        that also show this style of 3-way, or merge diff.\n\nWhile similar to patches,\
        \ diffs:\n\n* Don't have a commit header (username, commit message, etc)\n\
        * Support the optional `path=foo/bar.py` query param to filter\n  the diff\
        \ to just that one file diff\n\nThe raw diff is returned as-is, in whatever\
        \ encoding the files in the\nrepository use. It is not decoded into unicode.\
        \ As such, the\ncontent-type is `text/plain`."
      security:
      - oauth2:
        - "repository"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/pipelines_config/schedules/{schedule_uuid}:
    get:
      tags:
      - "pipelines"
      description: "Retrieve a schedule by its UUID."
      operationId: "getRepositoryPipelineSchedule"
    put:
      tags:
      - "pipelines"
      description: "Update a schedule."
      operationId: "updateRepositoryPipelineSchedule"
    delete:
      tags:
      - "pipelines"
      description: "Delete a schedule."
      operationId: "deleteRepositoryPipelineSchedule"
  /repositories/{username}/{repo_slug}/branch-restrictions:
    get:
      tags:
      - "branchrestrictions"
      description: "Returns a paginated list of all branch restrictions on the\nrepository."
      security:
      - oauth2:
        - "repository:admin"
      - basic: []
      - api_key: []
    post:
      tags:
      - "branchrestrictions"
      description: "Creates a new branch restriction rule for a repository.\n\n`kind`\
        \ describes what will be restricted. Allowed values are: `push`,\n`force`,\
        \ `delete`, and `restrict_merges`.\n\nDifferent kinds of branch restrictions\
        \ have different requirements:\n\n* `push` and `restrict_merges` require `users`\
        \ and `groups` to be\n  specified. Empty lists are allowed, in which case\
        \ permission is\n  denied for everybody.\n* `force` can not be specified in\
        \ a Mercurial repository.\n\n`pattern` is used to determine which branches\
        \ will be restricted.\n\nA `'*'` in `pattern` will expand to match zero or\
        \ more characters, and\nevery other character matches itself. For example,\
        \ `'foo*'` will match\n`'foo'` and `'foobar'`, but not `'barfoo'`. `'*'` will\
        \ match all\nbranches.\n\n`users` and `groups` are lists of user names and\
        \ group names.\n\n`kind` and `pattern` must be unique within a repository;\
        \ adding new\nusers or groups to an existing restriction should be done via\
        \ `PUT`.\n\nNote that branch restrictions with overlapping patterns are allowed,\n\
        but the resulting behavior may be surprising."
      security:
      - oauth2:
        - "repository:admin"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/issues/{issue_id}/comments/{comment_id}:
    get:
      tags:
      - "issue_tracker"
      description: "Returns the specified issue comment object."
      security:
      - oauth2:
        - "issue"
      - basic: []
      - api_key: []
  /teams/{username}/projects/{project_key}:
    get:
      tags:
      - "projects"
      description: ""
      security:
      - oauth2:
        - "project"
      - basic: []
      - api_key: []
    put:
      tags:
      - "projects"
      description: "Since this endpoint can be used to both update and to create a\n\
        project, the request body depends on the intent.\n\n### Creation\n\nSee the\
        \ POST documentation for the project collection for an\nexample of the request\
        \ body.\n\nNote: The `key` should not be specified in the body of request\n\
        (since it is already present in the URL). The `name` is required,\neverything\
        \ else is optional.\n\n### Update\n\nSee the POST documentation for the project\
        \ collection for an\nexample of the request body.\n\nNote: The key is not\
        \ required in the body (since it is already in\nthe URL). The key may be specified\
        \ in the body, if the intent is\nto change the key itself. In such a scenario,\
        \ the location of the\nproject is changed and is returned in the `Location`\
        \ header of the\nresponse."
      security:
      - oauth2:
        - "project:write"
      - basic: []
      - api_key: []
    delete:
      tags:
      - "projects"
      description: ""
      security:
      - oauth2:
        - "project:write"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/hooks/{uid}:
    get:
      tags:
      - "repositories"
      - "webhooks"
      description: "Returns the webhook with the specified id installed on the specified\n\
        repository."
      security:
      - oauth2:
        - "webhook"
      - basic: []
      - api_key: []
    put:
      tags:
      - "repositories"
      - "webhooks"
      description: "Updates the specified webhook subscription.\n\nThe following properties\
        \ can be mutated:\n\n* `description`\n* `url`\n* `active`\n* `events`"
      security:
      - oauth2:
        - "webhook"
      - basic: []
      - api_key: []
    delete:
      tags:
      - "repositories"
      - "webhooks"
      description: "Deletes the specified webhook subscription from the given\nrepository."
      security:
      - oauth2:
        - "webhook"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/pipelines_config/variables/:
    get:
      tags:
      - "pipelines"
      description: "Find repository level variables."
      operationId: "getRepositoryPipelineVariables"
    post:
      tags:
      - "pipelines"
      description: "Create a repository level variable."
      operationId: "createRepositoryPipelineVariable"
  /users/{username}:
    get:
      tags:
      - "users"
      description: "Gets the public information associated with a user account.\n\n\
        If the user's profile is private, `location`, `website` and\n`created_on`\
        \ elements are omitted."
      security:
      - oauth2: []
      - basic: []
      - api_key: []
  /users/{username}/pipelines_config/variables/:
    get:
      tags:
      - "pipelines"
      description: "Find user level variables."
      operationId: "getPipelineVariablesForUser"
    post:
      tags:
      - "pipelines"
      description: "Create a user level variable."
      operationId: "createPipelineVariableForUser"
  /snippets/{username}/{encoded_id}:
    get:
      tags:
      - "snippets"
      description: "Retrieves a single snippet.\n\nSnippets support multiple content\
        \ types:\n\n* application/json\n* multipart/related\n* multipart/form-data\n\
        \n\napplication/json\n----------------\n\nThe default content type of the\
        \ response is `application/json`.\nSince JSON is always `utf-8`, it cannot\
        \ reliably contain file contents\nfor files that are not text. Therefore,\
        \ JSON snippet documents only\ncontain the filename and links to the file\
        \ contents.\n\nThis means that in order to retrieve all parts of a snippet,\
        \ N+1\nrequests need to be made (where N is the number of files in the\nsnippet).\n\
        \n\nmultipart/related\n-----------------\n\nTo retrieve an entire snippet\
        \ in a single response, use the\n`Accept: multipart/related` HTTP request\
        \ header.\n\n    $ curl -H \"Accept: multipart/related\" https://api.bitbucket.org/2.0/snippets/evzijst/1\n\
        \nResponse:\n\n    HTTP/1.1 200 OK\n    Content-Length: 2214\n    Content-Type:\
        \ multipart/related; start=\"snippet\"; boundary=\"===============1438169132528273974==\"\
        \n    MIME-Version: 1.0\n\n    --===============1438169132528273974==\n  \
        \  Content-Type: application/json; charset=\"utf-8\"\n    MIME-Version: 1.0\n\
        \    Content-ID: snippet\n\n    {\n      \"links\": {\n        \"self\": {\n\
        \          \"href\": \"https://api.bitbucket.org/2.0/snippets/evzijst/kypj\"\
        \n        },\n        \"html\": {\n          \"href\": \"https://bitbucket.org/snippets/evzijst/kypj\"\
        \n        },\n        \"comments\": {\n          \"href\": \"https://api.bitbucket.org/2.0/snippets/evzijst/kypj/comments\"\
        \n        },\n        \"watchers\": {\n          \"href\": \"https://api.bitbucket.org/2.0/snippets/evzijst/kypj/watchers\"\
        \n        },\n        \"commits\": {\n          \"href\": \"https://api.bitbucket.org/2.0/snippets/evzijst/kypj/commits\"\
        \n        }\n      },\n      \"id\": kypj,\n      \"title\": \"My snippet\"\
        ,\n      \"created_on\": \"2014-12-29T22:22:04.790331+00:00\",\n      \"updated_on\"\
        : \"2014-12-29T22:22:04.790331+00:00\",\n      \"is_private\": false,\n  \
        \    \"files\": {\n        \"foo.txt\": {\n          \"links\": {\n      \
        \      \"self\": {\n              \"href\": \"https://api.bitbucket.org/2.0/snippets/evzijst/kypj/files/367ab19/foo.txt\"\
        \n            },\n            \"html\": {\n              \"href\": \"https://bitbucket.org/snippets/evzijst/kypj#file-foo.txt\"\
        \n            }\n          }\n        },\n        \"image.png\": {\n     \
        \     \"links\": {\n            \"self\": {\n              \"href\": \"https://api.bitbucket.org/2.0/snippets/evzijst/kypj/files/367ab19/image.png\"\
        \n            },\n            \"html\": {\n              \"href\": \"https://bitbucket.org/snippets/evzijst/kypj#file-image.png\"\
        \n            }\n          }\n        }\n      ],\n      \"owner\": {\n  \
        \      \"username\": \"evzijst\",\n        \"display_name\": \"Erik van Zijst\"\
        ,\n        \"uuid\": \"{d301aafa-d676-4ee0-88be-962be7417567}\",\n       \
        \ \"links\": {\n          \"self\": {\n            \"href\": \"https://api.bitbucket.org/2.0/users/evzijst\"\
        \n          },\n          \"html\": {\n            \"href\": \"https://bitbucket.org/evzijst\"\
        \n          },\n          \"avatar\": {\n            \"href\": \"https://bitbucket-staging-assetroot.s3.amazonaws.com/c/photos/2013/Jul/31/erik-avatar-725122544-0_avatar.png\"\
        \n          }\n        }\n      },\n      \"creator\": {\n        \"username\"\
        : \"evzijst\",\n        \"display_name\": \"Erik van Zijst\",\n        \"\
        uuid\": \"{d301aafa-d676-4ee0-88be-962be7417567}\",\n        \"links\": {\n\
        \          \"self\": {\n            \"href\": \"https://api.bitbucket.org/2.0/users/evzijst\"\
        \n          },\n          \"html\": {\n            \"href\": \"https://bitbucket.org/evzijst\"\
        \n          },\n          \"avatar\": {\n            \"href\": \"https://bitbucket-staging-assetroot.s3.amazonaws.com/c/photos/2013/Jul/31/erik-avatar-725122544-0_avatar.png\"\
        \n          }\n        }\n      }\n    }\n\n    --===============1438169132528273974==\n\
        \    Content-Type: text/plain; charset=\"us-ascii\"\n    MIME-Version: 1.0\n\
        \    Content-Transfer-Encoding: 7bit\n    Content-ID: \"foo.txt\"\n    Content-Disposition:\
        \ attachment; filename=\"foo.txt\"\n\n    foo\n\n    --===============1438169132528273974==\n\
        \    Content-Type: image/png\n    MIME-Version: 1.0\n    Content-Transfer-Encoding:\
        \ base64\n    Content-ID: \"image.png\"\n    Content-Disposition: attachment;\
        \ filename=\"image.png\"\n\n    iVBORw0KGgoAAAANSUhEUgAAABQAAAAoCAYAAAD+MdrbAAABD0lEQVR4Ae3VMUoDQRTG8ccUaW2m\n\
        \    TKONFxArJYJamCvkCnZTaa+VnQdJSBFl2SMsLFrEWNjZBZs0JgiL/+KrhhVmJRbCLPx4O+/DT2TB\n\
        \    cbblJxf+UWFVVRNsEGAtgvJxnLm2H+A5RQ93uIl+3632PZyl/skjfOn9Gvdwmlcw5aPUwimG+NT5\n\
        \    EnNN036IaZePUuIcK533NVfal7/5yjWeot2z9ta1cAczHEf7I+3J0ws9Cgx0fsOFpmlfwKcWPuBQ\n\
        \    73Oc4FHzBaZ8llq4q1mr5B2mOUCt815qYR8eB1hG2VJ7j35q4RofaH7IG+Xrf/PfJhfmwtfFYoIN\n\
        \    AqxFUD6OMxcvkO+UfKfkOyXfKdsv/AYCHMLVkHAFWgAAAABJRU5ErkJggg==\n    --===============1438169132528273974==--\n\
        \nmultipart/form-data\n-------------------\n\nAs with creating new snippets,\
        \ `multipart/form-data` can be used as an\nalternative to `multipart/related`.\
        \ However, the inherently flat\nstructure of form-data means that only basic,\
        \ root-level properties\ncan be returned, while nested elements like `links`\
        \ are omitted:\n\n    $ curl -H \"Accept: multipart/form-data\" https://api.bitbucket.org/2.0/snippets/evzijst/kypj\n\
        \nResponse:\n\n    HTTP/1.1 200 OK\n    Content-Length: 951\n    Content-Type:\
        \ multipart/form-data; boundary=----------------------------63a4b224c59f\n\
        \n    ------------------------------63a4b224c59f\n    Content-Disposition:\
        \ form-data; name=\"title\"\n    Content-Type: text/plain; charset=\"utf-8\"\
        \n\n    My snippet\n    ------------------------------63a4b224c59f--\n   \
        \ Content-Disposition: attachment; name=\"file\"; filename=\"foo.txt\"\n \
        \   Content-Type: text/plain\n\n    foo\n\n    ------------------------------63a4b224c59f\n\
        \    Content-Disposition: attachment; name=\"file\"; filename=\"image.png\"\
        \n    Content-Transfer-Encoding: base64\n    Content-Type: application/octet-stream\n\
        \n    iVBORw0KGgoAAAANSUhEUgAAABQAAAAoCAYAAAD+MdrbAAABD0lEQVR4Ae3VMUoDQRTG8ccUaW2m\n\
        \    TKONFxArJYJamCvkCnZTaa+VnQdJSBFl2SMsLFrEWNjZBZs0JgiL/+KrhhVmJRbCLPx4O+/DT2TB\n\
        \    cbblJxf+UWFVVRNsEGAtgvJxnLm2H+A5RQ93uIl+3632PZyl/skjfOn9Gvdwmlcw5aPUwimG+NT5\n\
        \    EnNN036IaZePUuIcK533NVfal7/5yjWeot2z9ta1cAczHEf7I+3J0ws9Cgx0fsOFpmlfwKcWPuBQ\n\
        \    73Oc4FHzBaZ8llq4q1mr5B2mOUCt815qYR8eB1hG2VJ7j35q4RofaH7IG+Xrf/PfJhfmwtfFYoIN\n\
        \    AqxFUD6OMxcvkO+UfKfkOyXfKdsv/AYCHMLVkHAFWgAAAABJRU5ErkJggg==\n    ------------------------------5957323a6b76--"
      security:
      - oauth2:
        - "snippet"
      - basic: []
      - api_key: []
    put:
      tags:
      - "snippets"
      description: "Used to update a snippet. Use this to add and delete files and\
        \ to\nchange a snippet's title.\n\nTo update a snippet, one can either PUT\
        \ a full snapshot, or only the\nparts that need to be changed.\n\nThe contract\
        \ for PUT on this API is that properties missing from the\nrequest remain\
        \ untouched so that snippets can be efficiently\nmanipulated with differential\
        \ payloads.\n\nTo delete a property (e.g. the title, or a file), include its\
        \ name in\nthe request, but omit its value (use `null`).\n\nAs in Git, explicit\
        \ renaming of files is not supported. Instead, to\nrename a file, delete it\
        \ and add it again under another name. This can\nbe done atomically in a single\
        \ request. Rename detection is left to\nthe SCM.\n\nPUT supports three different\
        \ content types for both request and\nresponse bodies:\n\n* `application/json`\n\
        * `multipart/related`\n* `multipart/form-data`\n\nThe content type used for\
        \ the request body can be different than that\nused for the response. Content\
        \ types are specified using standard HTTP\nheaders.\n\nUse the `Content-Type`\
        \ and `Accept` headers to select the desired\nrequest and response format.\n\
        \n\napplication/json\n----------------\n\nAs with creation and retrieval,\
        \ the content type determines what\nproperties can be manipulated. `application/json`\
        \ does not support\nfile contents and is therefore limited to a snippet's\
        \ meta data.\n\nTo update the title, without changing any of its files:\n\n\
        \    $ curl -X POST -H \"Content-Type: application/json\" https://api.bitbucket.org/2.0/snippets/evzijst/kypj\
        \             -d '{\"title\": \"Updated title\"}'\n\n\nTo delete the title:\n\
        \n    $ curl -X POST -H \"Content-Type: application/json\" https://api.bitbucket.org/2.0/snippets/evzijst/kypj\
        \             -d '{\"title\": null}'\n\nNot all parts of a snippet can be\
        \ manipulated. The owner and creator\nfor instance are immutable.\n\n\nmultipart/related\n\
        -----------------\n\n`multipart/related` can be used to manipulate all of\
        \ a snippet's\nproperties. The body is identical to a POST. properties omitted\
        \ from\nthe request are left unchanged. Since the `start` part contains JSON,\n\
        the mechanism for manipulating the snippet's meta data is identical\nto `application/json`\
        \ requests.\n\nTo update one of a snippet's file contents, while also changing\
        \ its\ntitle:\n\n    PUT /2.0/snippets/evzijst/kypj HTTP/1.1\n    Content-Length:\
        \ 288\n    Content-Type: multipart/related; start=\"snippet\"; boundary=\"\
        ===============1438169132528273974==\"\n    MIME-Version: 1.0\n\n    --===============1438169132528273974==\n\
        \    Content-Type: application/json; charset=\"utf-8\"\n    MIME-Version:\
        \ 1.0\n    Content-ID: snippet\n\n    {\n      \"title\": \"My updated snippet\"\
        ,\n      \"files\": {\n          \"foo.txt\": {}\n        }\n    }\n\n   \
        \ --===============1438169132528273974==\n    Content-Type: text/plain; charset=\"\
        us-ascii\"\n    MIME-Version: 1.0\n    Content-Transfer-Encoding: 7bit\n \
        \   Content-ID: \"foo.txt\"\n    Content-Disposition: attachment; filename=\"\
        foo.txt\"\n\n    Updated file contents.\n\n    --===============1438169132528273974==--\n\
        \nHere only the parts that are changed are included in the body. The\nother\
        \ files remain untouched.\n\nNote the use of the `files` list in the JSON\
        \ part. This list contains\nthe files that are being manipulated. This list\
        \ should have\ncorresponding multiparts in the request that contain the new\
        \ contents\nof these files.\n\nIf a filename in the `files` list does not\
        \ have a corresponding part,\nit will be deleted from the snippet, as shown\
        \ below:\n\n    PUT /2.0/snippets/evzijst/kypj HTTP/1.1\n    Content-Length:\
        \ 188\n    Content-Type: multipart/related; start=\"snippet\"; boundary=\"\
        ===============1438169132528273974==\"\n    MIME-Version: 1.0\n\n    --===============1438169132528273974==\n\
        \    Content-Type: application/json; charset=\"utf-8\"\n    MIME-Version:\
        \ 1.0\n    Content-ID: snippet\n\n    {\n      \"files\": {\n        \"image.png\"\
        : {}\n      }\n    }\n\n    --===============1438169132528273974==--\n\nTo\
        \ simulate a rename, delete a file and add the same file under\nanother name:\n\
        \n    PUT /2.0/snippets/evzijst/kypj HTTP/1.1\n    Content-Length: 212\n \
        \   Content-Type: multipart/related; start=\"snippet\"; boundary=\"===============1438169132528273974==\"\
        \n    MIME-Version: 1.0\n\n    --===============1438169132528273974==\n  \
        \  Content-Type: application/json; charset=\"utf-8\"\n    MIME-Version: 1.0\n\
        \    Content-ID: snippet\n\n    {\n        \"files\": {\n          \"foo.txt\"\
        : {},\n          \"bar.txt\": {}\n        }\n    }\n\n    --===============1438169132528273974==\n\
        \    Content-Type: text/plain; charset=\"us-ascii\"\n    MIME-Version: 1.0\n\
        \    Content-Transfer-Encoding: 7bit\n    Content-ID: \"bar.txt\"\n    Content-Disposition:\
        \ attachment; filename=\"bar.txt\"\n\n    foo\n\n    --===============1438169132528273974==--\n\
        \n\nmultipart/form-data\n-----------------\n\nAgain, one can also use `multipart/form-data`\
        \ to manipulate file\ncontents and meta data atomically.\n\n    $ curl -X\
        \ PUT http://localhost:12345/2.0/snippets/evzijst/kypj             -F title=\"\
        My updated snippet\" -F file=@foo.txt\n\n    PUT /2.0/snippets/evzijst/kypj\
        \ HTTP/1.1\n    Content-Length: 351\n    Content-Type: multipart/form-data;\
        \ boundary=----------------------------63a4b224c59f\n\n    ------------------------------63a4b224c59f\n\
        \    Content-Disposition: form-data; name=\"file\"; filename=\"foo.txt\"\n\
        \    Content-Type: text/plain\n\n    foo\n\n    ------------------------------63a4b224c59f\n\
        \    Content-Disposition: form-data; name=\"title\"\n\n    My updated snippet\n\
        \    ------------------------------63a4b224c59f\n\nTo delete a file, omit\
        \ its contents while including its name in the\n`files` field:\n\n    $ curl\
        \ -X PUT https://api.bitbucket.org/2.0/snippets/evzijst/kypj -F files=image.png\n\
        \n    PUT /2.0/snippets/evzijst/kypj HTTP/1.1\n    Content-Length: 149\n \
        \   Content-Type: multipart/form-data; boundary=----------------------------ef8871065a86\n\
        \n    ------------------------------ef8871065a86\n    Content-Disposition:\
        \ form-data; name=\"files\"\n\n    image.png\n    ------------------------------ef8871065a86--\n\
        \nThe explicit use of the `files` element in `multipart/related` and\n`multipart/form-data`\
        \ is only required when deleting files.\nThe default mode of operation is\
        \ for file parts to be processed,\nregardless of whether or not they are listed\
        \ in `files`, as a\nconvenience to the client."
      security:
      - oauth2:
        - "snippet:write"
      - basic: []
      - api_key: []
    delete:
      tags:
      - "snippets"
      description: "Deletes a snippet and returns an empty response."
      security:
      - oauth2:
        - "snippet:write"
      - basic: []
      - api_key: []
  /addon/linkers:
    get:
      tags:
      - "addon"
      description: ""
      security:
      - oauth2: []
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/pipelines_config/build_number:
    put:
      tags:
      - "pipelines"
      description: "Update the next build number that should be assigned to a pipeline.\
        \ The next build number that will be configured has to be strictly higher\
        \ than the current latest build number for this repository."
      operationId: "updateRepositoryBuildNumber"
  /repositories/{username}/{repo_slug}/pullrequests/{pull_request_id}/comments/{comment_id}:
    get:
      tags:
      - "pullrequests"
      description: "Returns a specific pull request comment."
      security:
      - oauth2:
        - "pullrequest"
      - basic: []
      - api_key: []
  /teams/{username}/permissions/repositories:
    get:
      tags: []
      description: "Returns an object for each repository permission for all of a\n\
        team’s repositories.\n\nPermissions returned are effective permissions — the\
        \ highest level of\npermission the user has. This does not include public\
        \ repositories that\nusers are not granted any specific permission in, and\
        \ does not\ndistinguish between direct and indirect privileges.\n\nOnly users\
        \ with admin permission for the team may access this resource.\n\nPermissions\
        \ can be:\n\n* `admin`\n* `write`\n* `read`\n\nExample:\n\n```\n$ curl https://api.bitbucket.org/2.0/teams/atlassian_tutorial/permissions/repositories\n\
        \n{\n  \"pagelen\": 10,\n  \"values\": [\n    {\n      \"type\": \"repository_permission\"\
        ,\n      \"user\": {\n        \"type\": \"user\",\n        \"username\": \"\
        evzijst\",\n        \"display_name\": \"Erik van Zijst\",\n        \"uuid\"\
        : \"{d301aafa-d676-4ee0-88be-962be7417567}\"\n      },\n      \"repository\"\
        : {\n        \"type\": \"repository\",\n        \"name\": \"geordi\",\n  \
        \      \"full_name\": \"bitbucket/geordi\",\n        \"uuid\": \"{85d08b4e-571d-44e9-a507-fa476535aa98}\"\
        \n      },\n      \"permission\": \"admin\"\n    },\n    {\n      \"type\"\
        : \"repository_permission\",\n      \"user\": {\n        \"type\": \"user\"\
        ,\n        \"username\": \"seanaty\",\n        \"display_name\": \"Sean Conaty\"\
        ,\n        \"uuid\": \"{504c3b62-8120-4f0c-a7bc-87800b9d6f70}\"\n      },\n\
        \      \"repository\": {\n        \"type\": \"repository\",\n        \"name\"\
        : \"geordi\",\n        \"full_name\": \"bitbucket/geordi\",\n        \"uuid\"\
        : \"{85d08b4e-571d-44e9-a507-fa476535aa98}\"\n      },\n      \"permission\"\
        : \"write\"\n    }\n  ],\n  \"page\": 1,\n  \"size\": 2\n}\n```\n\nResults\
        \ may be further [filtered or sorted](../../../../meta/filtering)\nby repository,\
        \ user, or permission by adding the following query string\nparameters:\n\n\
        * `q=repository.name=\"geordi\"` or `q=permission>\"read\"`\n* `sort=user.display_name`\n\
        \nNote that the query parameter values need to be URL escaped so that `=`\n\
        would become `%3D`."
      security:
      - oauth2:
        - "team"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/filehistory/{node}/{path}:
    get:
      tags:
      - "source"
      - "repositories"
      description: "Returns a paginated list of commits that modified the specified\
        \ file.\n\nCommits are returned in reverse chronological order. This is roughly\n\
        equivalent to the following commands:\n\n    $ git log --follow --date-order\
        \ <sha> <path>\n\n    $ hg log --follow <path>\n\nBy default, Bitbucket will\
        \ follow renames and the path name in the\nreturned entries reflects that.\
        \ This can be turned off using the\n`?renames=false` query parameter.\n\n\
        Results are returned in descending chronological order by default, and\nlike\
        \ most endpoints you can\n[filter and sort](../../../../../../meta/filtering)\
        \ the response to\nonly provide exactly the data you want.\n\nFor example,\
        \ if you wanted to find commits made before 2011-05-18\nagainst a file named\
        \ `README.rst`, but you only wanted the path and\ndate, your query would look\
        \ like this:\n\n```\n$ curl 'https://api.bitbucket.org/2.0/repositories/evzijst/dogslow/filehistory/master/README.rst'\\\
        \n  '?fields=values.next,values.path,values.commit.date&q=commit.date<=2011-05-18'\n\
        {\n  \"values\": [\n    {\n      \"commit\": {\n        \"date\": \"2011-05-17T07:32:09+00:00\"\
        \n      },\n      \"path\": \"README.rst\"\n    },\n    {\n      \"commit\"\
        : {\n        \"date\": \"2011-05-16T06:33:28+00:00\"\n      },\n      \"path\"\
        : \"README.txt\"\n    },\n    {\n      \"commit\": {\n        \"date\": \"\
        2011-05-16T06:15:39+00:00\"\n      },\n      \"path\": \"README.txt\"\n  \
        \  }\n  ]\n}\n```\n\nIn the response you can see that the file was renamed\
        \ to `README.rst`\nby the commit made on 2011-05-16, and was previously named\
        \ `README.txt`."
      security:
      - oauth2:
        - "repository"
      - basic: []
      - api_key: []
  /users/{username}/hooks:
    get:
      tags:
      - "users"
      - "webhooks"
      description: "Returns a paginated list of webhooks installed on this user account."
      security:
      - oauth2:
        - "webhook"
      - basic: []
      - api_key: []
    post:
      tags:
      - "users"
      - "webhooks"
      description: "Creates a new webhook on the specified user account.\n\nAccount-level\
        \ webhooks are fired for events from all repositories\nbelonging to that account.\n\
        \nNote that one can only register webhooks on one's own account, not that\n\
        of others."
      security:
      - oauth2:
        - "webhook"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/components/{component_id}:
    get:
      tags:
      - "issue_tracker"
      description: "Returns the specified issue tracker component object."
      security:
      - oauth2:
        - "issue"
      - basic: []
      - api_key: []
  /addon:
    put:
      tags:
      - "addon"
      description: ""
      security:
      - oauth2: []
      - basic: []
      - api_key: []
    delete:
      tags:
      - "addon"
      description: ""
      security:
      - oauth2: []
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/pipelines/{pipeline_uuid}:
    get:
      tags:
      - "pipelines"
      description: "Retrieve a specified pipeline"
      operationId: "getPipelineForRepository"
  /users/{username}/following:
    get:
      tags:
      - "users"
      description: "Returns the list of accounts this user is following."
      security:
      - oauth2:
        - "account"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/issues/{issue_id}:
    get:
      tags:
      - "issue_tracker"
      description: "Returns the specified issue."
      security:
      - oauth2:
        - "issue"
      - basic: []
      - api_key: []
    put:
      tags:
      - "issue_tracker"
      description: "Modifies the issue.\n\n```\n$ curl https://api.bitbucket.org/2.0/repostories/evzijst/dogslow/issues/123\
        \ \\\n  -u evzijst -s -X PUT -H 'Content-Type: application/json' \\\n  -d\
        \ '{\n  \"title\": \"Updated title\",\n  \"assignee\": {\n    \"username\"\
        : \"evzijst\"\n  },\n  \"priority\": \"minor\",\n  \"version\": {\n    \"\
        name\": \"1.0\"\n  },\n  \"component\": null\n}'\n```\n\nThe example above\
        \ changes the `title`, `assignee`, `priority` and the\n`version`. It also\
        \ removes the `component` from the issue by setting the\nfield explicitly\
        \ to `null`. Any field that is not present will keep its\nexisting value.\n\
        \nNote that the issue tracker keeps a list of all modifications made to\n\
        an issue under the `/issues/123/changes` endpoint and a PUT to this\nendpoint\
        \ will create a new changes record.\n\nIssues can also be manipulated by POSTing\
        \ directly to the issue\n`/changes` endpoint. This is equivalent to a PUT\
        \ here, except that the\nclient is able to provide a message that will be\
        \ stored alongside the\nchange record."
      security:
      - oauth2:
        - "issue:write"
      - basic: []
      - api_key: []
    delete:
      tags:
      - "issue_tracker"
      description: "Deletes the specified issue. This requires write access to the\n\
        repository."
      security:
      - oauth2:
        - "issue:write"
      - basic: []
      - api_key: []
  /teams/{username}/repositories:
    get:
      tags:
      - "users"
      - "teams"
      description: "All repositories owned by a user/team. This includes private\n\
        repositories, but filtered down to the ones that the calling user has\naccess\
        \ to."
      security:
      - oauth2:
        - "repository"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/downloads:
    get:
      tags:
      - "downloads"
      description: "Returns a list of download links associated with the repository."
      security:
      - oauth2:
        - "repository"
      - basic: []
      - api_key: []
    post:
      tags:
      - "downloads"
      description: "Upload new download artifacts.\n\nTo upload files, perform a `multipart/form-data`\
        \ POST containing one\nor more `files` fields:\n\n    $ echo Hello World >\
        \ hello.txt\n    $ curl -s -u evzijst -X POST https://api.bitbucket.org/2.0/repositories/evzijst/git-tests/downloads\
        \ -F files=@hello.txt\n\nWhen a file is uploaded with the same name as an\
        \ existing artifact,\nthen the existing file will be replaced."
      security:
      - oauth2:
        - "repository:write"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/refs:
    get:
      tags:
      - "refs"
      description: ""
      security:
      - oauth2:
        - "repository"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/pipelines_config/variables/{variable_uuid}:
    get:
      tags:
      - "pipelines"
      description: "Retrieve a repository level variable."
      operationId: "getRepositoryPipelineVariable"
    put:
      tags:
      - "pipelines"
      description: "Update a repository level variable."
      operationId: "updateRepositoryPipelineVariable"
    delete:
      tags:
      - "pipelines"
      description: "Delete a repository level variable."
      operationId: "deleteRepositoryPipelineVariable"
  /repositories/{username}/{repo_slug}/pipelines/{pipeline_uuid}/stopPipeline:
    post:
      tags:
      - "pipelines"
      description: "Signal the stop of a pipeline and all of its steps that not have\
        \ completed yet."
      operationId: "stopPipeline"
  /hook_events:
    get:
      tags:
      - "webhooks"
      description: "Returns the webhook resource or subject types on which webhooks\
        \ can\nbe registered.\n\nEach resource/subject type contains an `events` link\
        \ that returns the\npaginated list of specific events each individual subject\
        \ type can\nemit.\n\nThis endpoint is publicly accessible and does not require\n\
        authentication or scopes.\n\nExample:\n\n```\n$ curl https://api.bitbucket.org/2.0/hook_events\n\
        \n{\n    \"repository\": {\n        \"links\": {\n            \"events\":\
        \ {\n                \"href\": \"https://api.bitbucket.org/2.0/hook_events/repository\"\
        \n            }\n        }\n    },\n    \"team\": {\n        \"links\": {\n\
        \            \"events\": {\n                \"href\": \"https://api.bitbucket.org/2.0/hook_events/team\"\
        \n            }\n        }\n    },\n    \"user\": {\n        \"links\": {\n\
        \            \"events\": {\n                \"href\": \"https://api.bitbucket.org/2.0/hook_events/user\"\
        \n            }\n        }\n    }\n}\n```"
      security:
      - oauth2: []
      - basic: []
      - api_key: []
  /teams/{username}:
    get:
      tags:
      - "teams"
      description: "Gets the public information associated with a team.\n\nIf the\
        \ team's profile is private, `location`, `website` and\n`created_on` elements\
        \ are omitted."
      security:
      - oauth2: []
      - basic: []
      - api_key: []
  /user/emails/{email}:
    get:
      tags:
      - "users"
      description: "Returns details about a specific one of the authenticated user's\n\
        email addresses.\n\nDetails describe whether the address has been confirmed\
        \ by the user and\nwhether it is the user's primary address or not."
      security:
      - oauth2:
        - "email"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/pullrequests/{pull_request_id}/approve:
    post:
      tags:
      - "pullrequests"
      description: "Approve the specified pull request as the authenticated user."
      security:
      - oauth2:
        - "pullrequest:write"
      - basic: []
      - api_key: []
    delete:
      tags:
      - "pullrequests"
      description: "Redact the authenticated user's approval of the specified pull\n\
        request."
      security:
      - oauth2:
        - "pullrequest:write"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/patch/{spec}:
    get:
      tags:
      - "commits"
      description: "Produces a raw patch for a single commit (diffed against its first\n\
        parent), or a patch-series for a revspec of 2 commits (e.g.\n`3a8b42..9ff173`\
        \ where the first commit represents the source and the\nsecond commit the\
        \ destination).\n\nIn case of the latter (diffing a revspec), a patch series\
        \ is returned\nfor the commits on the source branch (`3a8b42` and its ancestors\
        \ in\nour example). For Mercurial, a single patch is returned that combines\n\
        the changes of all commits on the source branch.\n\nWhile similar to diffs,\
        \ patches:\n\n* Have a commit header (username, commit message, etc)\n* Do\
        \ not support the `path=foo/bar.py` query parameter\n\nThe raw patch is returned\
        \ as-is, in whatever encoding the files in the\nrepository use. It is not\
        \ decoded into unicode. As such, the\ncontent-type is `text/plain`."
      security:
      - oauth2:
        - "repository"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/pipelines_config:
    get:
      tags:
      - "pipelines"
      description: "Retrieve the repository pipelines configuration."
      operationId: "getRepositoryPipelineConfig"
    put:
      tags:
      - "pipelines"
      description: "Update the pipelines configuration for a repository."
      operationId: "updateRepositoryPipelineConfig"
  /repositories/{username}/{repo_slug}/forks:
    get:
      tags:
      - "repositories"
      description: "Returns a paginated list of all the forks of the specified\nrepository."
      security:
      - oauth2:
        - "repository"
      - basic: []
      - api_key: []
    post:
      tags:
      - "repositories"
      description: "Creates a new fork of the specified repository.\n\nBy default,\
        \ forks are created under the authenticated user's account\nwith the same\
        \ name and slug of the original repository.\n\n```\n$ curl -X POST -u jdoe\
        \ https://api.bitbucket.org/2.0/repositories/evzijst/dogslow/forks\n\n{\n\
        \  \"scm\": \"git\",\n  \"full_name\": \"jdoe/dogslow\",\n  \"parent\": {\n\
        \    \"full_name\": \"evzijst/dogslow\",\n    ...\n  },\n  ...\n}\n```\n\n\
        If you already have a repo with that name, then a 400 is returned and\nyou'll\
        \ need to specify a custom name for the new fork:\n\n```\n$ curl -X POST -u\
        \ jdoe https://api.bitbucket.org/2.0/repositories/evzijst/dogslow/forks \\\
        \n  -H 'Content-Type: application/json' -d '{\n    \"name\": \"dogslow_fork\"\
        \n}'\n```\n\nWhen you specify a value for `name`, it will also affect the\
        \ `slug`.\nThe `slug` is reflected in the repository URL of the new fork.\
        \ It is\nderived from `name` by substituting non-ASCII characters, removes\n\
        whitespace, and changes characters to lower case. For example,\n`My repo`\
        \ would turn into `my_repo`.\n\n## Forking a repository into a team account\n\
        \nTo create a fork into a team account, specify the new owner's account\n\
        explicitly as part of the request body. This prevents forked\nrepositories\
        \ from being owned by the authenticated user submitting the\nrequest:\n\n\
        ```\n$ curl -X POST -u jdoe https://api.bitbucket.org/2.0/repositories/atlassian/bbql/forks\
        \ \\\n  -H 'Content-Type: application/json' -d '{\n    \"name\": \"bbql_fork\"\
        ,\n    \"owner\": {\n      \"username\": \"atlassian\"\n    }\n}'\n```\n\n\
        To fork a repository into the same team, also specify a new `name`.\n\nYou\
        \ need contributor access to create new forks within a team account.\n\n\n\
        ## Change the properties of a new fork\n\nBy default the fork inherits most\
        \ of its properties from the parent.\nHowever, since the optional POST body\
        \ document follows the normal\n`repository` JSON schema and you can override\
        \ the new fork's\nproperties.\n\nProperties that can be overridden include:\n\
        \n* description\n* fork_policy\n* language\n* mainbranch\n* is_private (note\
        \ that a private repo's fork_policy might prohibit\n  the creation of public\
        \ forks, in which `is_private=False` would fail)\n* has_issues (to initialize\
        \ or disable the new repo's issue tracker --\n  note that the actual contents\
        \ of the parent repository's issue\n  tracker are not copied during forking)\n\
        * has_wiki (to initialize or disable the new repo's wiki --\n  note that the\
        \ actual contents of the parent repository's wiki are not\n  copied during\
        \ forking)\n* project (only teams have projects and when forking into a private\n\
        \  project, the fork's `is_private` must be `true`)\n\nProperties that cannot\
        \ be modified include:\n\n* scm\n* parent\n* full_name"
      security:
      - oauth2:
        - "repository:write"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/issues:
    get:
      tags:
      - "issue_tracker"
      description: "Returns the issues in the issue tracker."
      security:
      - oauth2:
        - "issue"
      - basic: []
      - api_key: []
    post:
      tags:
      - "issue_tracker"
      description: "Creates a new issue.\n\nThis call requires authentication. Private\
        \ repositories or private\nissue trackers require the caller to authenticate\
        \ with an account that\nhas appropriate authorisation.\n\nThe authenticated\
        \ user is used for the issue's `reporter` field."
      security:
      - oauth2:
        - "issue:write"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/pipelines_config/schedules/:
    get:
      tags:
      - "pipelines"
      description: "Retrieve the configured schedules for the given repository."
      operationId: "getRepositoryPipelineSchedules"
    post:
      tags:
      - "pipelines"
      description: "Create a schedule for the given repository."
      operationId: "createRepositoryPipelineSchedule"
  /repositories/{username}/{repo_slug}/pipelines/{pipeline_uuid}/steps/:
    get:
      tags:
      - "pipelines"
      description: "Find steps for the given pipeline."
      operationId: "getPipelineStepsForRepository"
  /repositories/{username}/{repo_slug}/issues/{issue_id}/attachments:
    get:
      tags:
      - "issue_tracker"
      description: "Returns all attachments for this issue.\n\nThis returns the files'\
        \ meta data. This does not return the files'\nactual contents.\n\nThe files\
        \ are always ordered by their upload date."
      security:
      - oauth2:
        - "issue"
      - basic: []
      - api_key: []
    post:
      tags:
      - "issue_tracker"
      description: "Upload new issue attachments.\n\nTo upload files, perform a `multipart/form-data`\
        \ POST containing one\nor more file fields.\n\nWhen a file is uploaded with\
        \ the same name as an existing attachment,\nthen the existing file will be\
        \ replaced."
      security:
      - oauth2:
        - "issue:write"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/versions:
    get:
      tags:
      - "issue_tracker"
      description: "Returns the versions that have been defined in the issue tracker.\n\
        \nThis resource is only available on repositories that have the issue\ntracker\
        \ enabled."
      security:
      - oauth2:
        - "issue"
      - basic: []
      - api_key: []
  /user/permissions/teams:
    get:
      tags: []
      description: "Returns an object for each team the caller is a member of, and\
        \ their\neffective role — the highest level of privilege the caller has. If\
        \ a\nuser is a member of multiple groups with distinct roles, only the\nhighest\
        \ level is returned.\n\nPermissions can be:\n\n* `admin`\n* `collaborator`\n\
        \nExample:\n\n```\n$ curl https://api.bitbucket.org/2.0/user/permissions/teams\n\
        \n{\n  \"pagelen\": 10,\n  \"values\": [\n    {\n      \"permission\": \"\
        admin\",\n      \"type\": \"team_permission\",\n      \"user\": {\n      \
        \  \"type\": \"user\",\n        \"username\": \"evzijst\",\n        \"display_name\"\
        : \"Erik van Zijst\",\n        \"uuid\": \"{d301aafa-d676-4ee0-88be-962be7417567}\"\
        \n      },\n      \"team\": {\n        \"username\": \"bitbucket\",\n    \
        \    \"display_name\": \"Atlassian Bitbucket\",\n        \"uuid\": \"{4cc6108a-a241-4db0-96a5-64347ac04f87}\"\
        \n      }\n    }\n  ],\n  \"page\": 1,\n  \"size\": 1\n}\n```\n\nResults may\
        \ be further [filtered or sorted](../../../meta/filtering) by\nteam or permission\
        \ by adding the following query string parameters:\n\n* `q=team.username=\"\
        bitbucket\"` or `q=permission=\"admin\"`\n* `sort=team.display_name`\n\nNote\
        \ that the query parameter values need to be URL escaped so that `=`\nwould\
        \ become `%3D`."
      security:
      - oauth2:
        - "account"
      - basic: []
      - api_key: []
  /teams/{username}/hooks/{uid}:
    get:
      tags:
      - "teams"
      - "webhooks"
      description: "Returns the webhook with the specified id installed on the given\n\
        team account."
      security:
      - oauth2:
        - "webhook"
      - basic: []
      - api_key: []
    put:
      tags:
      - "teams"
      - "webhooks"
      description: "Updates the specified webhook subscription.\n\nThe following properties\
        \ can be mutated:\n\n* `description`\n* `url`\n* `active`\n* `events`"
      security:
      - oauth2:
        - "webhook"
      - basic: []
      - api_key: []
    delete:
      tags:
      - "teams"
      - "webhooks"
      description: "Deletes the specified webhook subscription from the given team\n\
        account."
      security:
      - oauth2:
        - "webhook"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/pipelines_config/ssh/known_hosts/:
    get:
      tags:
      - "pipelines"
      description: "Find repository level known hosts."
      operationId: "getRepositoryPipelineKnownHosts"
    post:
      tags:
      - "pipelines"
      description: "Create a repository level known host."
      operationId: "createRepositoryPipelineKnownHost"
  /repositories/{username}/{repo_slug}/refs/tags/{name}:
    get:
      tags:
      - "refs"
      description: ""
      security:
      - oauth2:
        - "repository"
      - basic: []
      - api_key: []
  /snippets/{username}/{encoded_id}/watch:
    get:
      tags:
      - "snippets"
      description: "Used to check if the current user is watching a specific snippet.\n\
        \nReturns 204 (No Content) if the user is watching the snippet and 404 if\n\
        not.\n\nHitting this endpoint anonymously always returns a 404."
      security:
      - oauth2:
        - "snippet"
      - basic: []
      - api_key: []
    put:
      tags:
      - "snippets"
      description: "Used to start watching a specific snippet. Returns 204 (No Content)."
      security:
      - oauth2:
        - "snippet:write"
      - basic: []
      - api_key: []
    delete:
      tags:
      - "snippets"
      description: "Used to stop watching a specific snippet. Returns 204 (No Content)\n\
        to indicate success."
      security:
      - oauth2:
        - "snippet:write"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/pullrequests/{pull_request_id}/diff:
    get:
      tags:
      - "pullrequests"
      description: ""
      security:
      - oauth2:
        - "pullrequest"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/src/{node}/{path}:
    get:
      tags:
      - "source"
      - "repositories"
      description: "This endpoints is used to retrieve the contents of a single file,\n\
        or the contents of a directory at a specified revision.\n\n## Raw file contents\n\
        \nWhen `path` points to a file, this endpoint returns the raw contents.\n\
        The response's Content-Type is derived from the filename\nextension (not from\
        \ the contents). The file contents are not processed\nand no character encoding/recoding\
        \ is performed and as a result no\ncharacter encoding is included as part\
        \ of the Content-Type.\n\nThe `Content-Disposition` header will be \"attachment\"\
        \ to prevent\nbrowsers from running executable files.\n\nIf the file is managed\
        \ by LFS, then a 301 redirect pointing to\nAtlassian's media services platform\
        \ is returned.\n\nThe response includes an ETag that is based on the contents\
        \ of the file\nand its attributes. This means that an empty `__init__.py`\
        \ always\nreturns the same ETag, regardless on the directory it lives in,\
        \ or the\ncommit it is on.\n\n## File meta data\n\nWhen the request for a\
        \ file path includes the query parameter\n`?format=meta`, instead of returning\
        \ the file's raw contents, Bitbucket\ninstead returns the JSON object describing\
        \ the file's properties:\n\n```javascript\n$ curl https://api.bitbucket.org/2.0/repositories/atlassian/bbql/src/eefd5ef/tests/__init__.py?format=meta\n\
        {\n  \"links\": {\n    \"self\": {\n      \"href\": \"https://api.bitbucket.org/2.0/repositories/atlassian/bbql/src/eefd5ef5d3df01aed629f650959d6706d54cd335/tests/__init__.py\"\
        \n    },\n    \"meta\": {\n      \"href\": \"https://api.bitbucket.org/2.0/repositories/atlassian/bbql/src/eefd5ef5d3df01aed629f650959d6706d54cd335/tests/__init__.py?format=meta\"\
        \n    }\n  },\n  \"path\": \"tests/__init__.py\",\n  \"commit\": {\n    \"\
        type\": \"commit\",\n    \"hash\": \"eefd5ef5d3df01aed629f650959d6706d54cd335\"\
        ,\n    \"links\": {\n      \"self\": {\n        \"href\": \"https://api.bitbucket.org/2.0/repositories/atlassian/bbql/commit/eefd5ef5d3df01aed629f650959d6706d54cd335\"\
        \n      },\n      \"html\": {\n        \"href\": \"https://bitbucket.org/atlassian/bbql/commits/eefd5ef5d3df01aed629f650959d6706d54cd335\"\
        \n      }\n    }\n  },\n  \"attributes\": [],\n  \"type\": \"commit_file\"\
        ,\n  \"size\": 0\n}\n```\n\nFile objects contain an `attributes` element that\
        \ contains a list of\npossible modifiers. Currently defined values are:\n\n\
        * `link` -- indicates that the entry is a symbolic link. The contents\n  \
        \  of the file represent the path the link points to.\n* `executable` -- indicates\
        \ that the file has the executable bit set.\n* `subrepository` -- indicates\
        \ that the entry points to a submodule or\n    subrepo. The contents of the\
        \ file is the SHA1 of the repository\n    pointed to.\n* `binary` -- indicates\
        \ whether Bitbucket thinks the file is binary.\n\nThis endpoint can provide\
        \ an alternative to how a HEAD request can be\nused to check for the existence\
        \ of a file, or a file's size without\nincurring the overhead of receiving\
        \ its full contents.\n\n\n## Directory listings\n\nWhen `path` points to a\
        \ directory instead of a file, the response is a\npaginated list of directory\
        \ and file objects in the same order as the\nunderlying SCM system would return\
        \ them.\n\nFor example:\n\n```javascript\n$ curl https://api.bitbucket.org/2.0/repositories/atlassian/bbql/src/eefd5ef/tests\n\
        {\n  \"pagelen\": 10,\n  \"values\": [\n    {\n      \"path\": \"tests/test_project\"\
        ,\n      \"type\": \"commit_directory\",\n      \"links\": {\n        \"self\"\
        : {\n          \"href\": \"https://api.bitbucket.org/2.0/repositories/atlassian/bbql/src/eefd5ef5d3df01aed629f650959d6706d54cd335/tests/test_project/\"\
        \n        },\n        \"meta\": {\n          \"href\": \"https://api.bitbucket.org/2.0/repositories/atlassian/bbql/src/eefd5ef5d3df01aed629f650959d6706d54cd335/tests/test_project/?format=meta\"\
        \n        }\n      },\n      \"commit\": {\n        \"type\": \"commit\",\n\
        \        \"hash\": \"eefd5ef5d3df01aed629f650959d6706d54cd335\",\n       \
        \ \"links\": {\n          \"self\": {\n            \"href\": \"https://api.bitbucket.org/2.0/repositories/atlassian/bbql/commit/eefd5ef5d3df01aed629f650959d6706d54cd335\"\
        \n          },\n          \"html\": {\n            \"href\": \"https://bitbucket.org/atlassian/bbql/commits/eefd5ef5d3df01aed629f650959d6706d54cd335\"\
        \n          }\n        }\n      }\n    },\n    {\n      \"links\": {\n   \
        \     \"self\": {\n          \"href\": \"https://api.bitbucket.org/2.0/repositories/atlassian/bbql/src/eefd5ef5d3df01aed629f650959d6706d54cd335/tests/__init__.py\"\
        \n        },\n        \"meta\": {\n          \"href\": \"https://api.bitbucket.org/2.0/repositories/atlassian/bbql/src/eefd5ef5d3df01aed629f650959d6706d54cd335/tests/__init__.py?format=meta\"\
        \n        }\n      },\n      \"path\": \"tests/__init__.py\",\n      \"commit\"\
        : {\n        \"type\": \"commit\",\n        \"hash\": \"eefd5ef5d3df01aed629f650959d6706d54cd335\"\
        ,\n        \"links\": {\n          \"self\": {\n            \"href\": \"https://api.bitbucket.org/2.0/repositories/atlassian/bbql/commit/eefd5ef5d3df01aed629f650959d6706d54cd335\"\
        \n          },\n          \"html\": {\n            \"href\": \"https://bitbucket.org/atlassian/bbql/commits/eefd5ef5d3df01aed629f650959d6706d54cd335\"\
        \n          }\n        }\n      },\n      \"attributes\": [],\n      \"type\"\
        : \"commit_file\",\n      \"size\": 0\n    }\n  ],\n  \"page\": 1,\n  \"size\"\
        : 2\n}\n```\n\nWhen listing the contents of the repo's root directory, the\
        \ use of a\ntrailing slash at the end of the URL is required.\n\nThe response\
        \ is not recursive, meaning that only the direct contents of\na path are returned.\
        \ The response does not recurse down into\nsubdirectories. In order to \"\
        walk\" the entire directory tree, the\nclient needs to parse each response\
        \ and follow the `self` links of each\n`commit_directory` object.\n\nEach\
        \ returned object is either a `commit_file`, or a `commit_directory`,\nboth\
        \ of which contain a `path` element. This path is the absolute path\nfrom\
        \ the root of the repository. Each object also contains a `commit`\nobject\
        \ which embeds the commit the file is on. Note that this is merely\nthe commit\
        \ that was used in the URL. It is *not* the commit that last\nmodified the\
        \ file.\n\nDirectory objects have 2 representations. Their `self` link returns\
        \ the\npaginated contents of the directory. The `meta` link on the other hand\n\
        returns the actual `directory` object itself, e.g.:\n\n```javascript\n{\n\
        \  \"path\": \"tests/test_project\",\n  \"type\": \"commit_directory\",\n\
        \  \"links\": {\n    \"self\": {\n      \"href\": \"https://api.bitbucket.org/2.0/repositories/atlassian/bbql/src/eefd5ef5d3df01aed629f650959d6706d54cd335/tests/test_project/\"\
        \n    },\n    \"meta\": {\n      \"href\": \"https://api.bitbucket.org/2.0/repositories/atlassian/bbql/src/eefd5ef5d3df01aed629f650959d6706d54cd335/tests/test_project/?format=meta\"\
        \n    }\n  },\n  \"commit\": { ... }\n}\n```\n\n## Querying, filtering and\
        \ sorting\n\nLike most API endpoints, this API supports the Bitbucket\nquerying/filtering\
        \ syntax and so you could filter a directory listing\nto only include entries\
        \ that match certain criteria. For instance, to\nlist all binary files over\
        \ 1kb use the expression:\n\n`size > 1024 and attributes = \"binary\"`\n\n\
        which after urlencoding yields the query string:\n\n`?q=size%3E1024+and+attributes%3D%22binary%22`\n\
        \nTo change the ordering of the response, use the `?sort` parameter:\n\n`.../src/eefd5ef/?sort=-size`\n\
        \nSee [filtering and sorting](../../../../../../meta/filtering) for more\n\
        details."
      security:
      - oauth2:
        - "repository"
      - basic: []
      - api_key: []
  /snippets:
    get:
      tags:
      - "snippets"
      description: "Returns all snippets. Like pull requests, repositories and teams,\
        \ the\nfull set of snippets is defined by what the current user has access\
        \ to.\n\nThis includes all snippets owned by the current user, but also all\
        \ snippets\nowned by any of the teams the user is a member of, or snippets\
        \ by other\nusers that the current user is either watching or has collaborated\
        \ on (for\ninstance by commenting on it).\n\nTo limit the set of returned\
        \ snippets, apply the\n`?role=[owner|contributor|member]` query parameter\
        \ where the roles are\ndefined as follows:\n\n* `owner`: all snippets owned\
        \ by the current user\n* `contributor`: all snippets owned by, or watched\
        \ by the current user\n* `member`: owned by the user, their teams, or watched\
        \ by the current user\n\nWhen no role is specified, all public snippets are\
        \ returned, as well as all\nprivately owned snippets watched or commented\
        \ on.\n\nThe returned response is a normal paginated JSON list. This endpoint\n\
        only supports `application/json` responses and no\n`multipart/form-data` or\
        \ `multipart/related`. As a result, it is not\npossible to include the file\
        \ contents."
      security:
      - oauth2:
        - "snippet"
      - basic: []
      - api_key: []
    post:
      tags:
      - "snippets"
      description: "Creates a new snippet under the authenticated user's account.\n\
        \nSnippets can contain multiple files. Both text and binary files are\nsupported.\n\
        \nThe simplest way to create a new snippet from a local file:\n\n    $ curl\
        \ -u username:password -X POST https://api.bitbucket.org/2.0/snippets    \
        \           -F file=@image.png\n\nCreating snippets through curl has a few\
        \ limitations and so let's look\nat a more complicated scenario.\n\nSnippets\
        \ are created with a multipart POST. Both `multipart/form-data`\nand `multipart/related`\
        \ are supported. Both allow the creation of\nsnippets with both meta data\
        \ (title, etc), as well as multiple text\nand binary files.\n\nThe main difference\
        \ is that `multipart/related` can use rich encoding\nfor the meta data (currently\
        \ JSON).\n\n\nmultipart/related (RFC-2387)\n----------------------------\n\
        \nThis is the most advanced and efficient way to create a paste.\n\n    POST\
        \ /2.0/snippets/evzijst HTTP/1.1\n    Content-Length: 1188\n    Content-Type:\
        \ multipart/related; start=\"snippet\"; boundary=\"===============1438169132528273974==\"\
        \n    MIME-Version: 1.0\n\n    --===============1438169132528273974==\n  \
        \  Content-Type: application/json; charset=\"utf-8\"\n    MIME-Version: 1.0\n\
        \    Content-ID: snippet\n\n    {\n      \"title\": \"My snippet\",\n    \
        \  \"is_private\": true,\n      \"scm\": \"hg\",\n      \"files\": {\n   \
        \       \"foo.txt\": {},\n          \"image.png\": {}\n        }\n    }\n\n\
        \    --===============1438169132528273974==\n    Content-Type: text/plain;\
        \ charset=\"us-ascii\"\n    MIME-Version: 1.0\n    Content-Transfer-Encoding:\
        \ 7bit\n    Content-ID: \"foo.txt\"\n    Content-Disposition: attachment;\
        \ filename=\"foo.txt\"\n\n    foo\n\n    --===============1438169132528273974==\n\
        \    Content-Type: image/png\n    MIME-Version: 1.0\n    Content-Transfer-Encoding:\
        \ base64\n    Content-ID: \"image.png\"\n    Content-Disposition: attachment;\
        \ filename=\"image.png\"\n\n    iVBORw0KGgoAAAANSUhEUgAAABQAAAAoCAYAAAD+MdrbAAABD0lEQVR4Ae3VMUoDQRTG8ccUaW2m\n\
        \    TKONFxArJYJamCvkCnZTaa+VnQdJSBFl2SMsLFrEWNjZBZs0JgiL/+KrhhVmJRbCLPx4O+/DT2TB\n\
        \    cbblJxf+UWFVVRNsEGAtgvJxnLm2H+A5RQ93uIl+3632PZyl/skjfOn9Gvdwmlcw5aPUwimG+NT5\n\
        \    EnNN036IaZePUuIcK533NVfal7/5yjWeot2z9ta1cAczHEf7I+3J0ws9Cgx0fsOFpmlfwKcWPuBQ\n\
        \    73Oc4FHzBaZ8llq4q1mr5B2mOUCt815qYR8eB1hG2VJ7j35q4RofaH7IG+Xrf/PfJhfmwtfFYoIN\n\
        \    AqxFUD6OMxcvkO+UfKfkOyXfKdsv/AYCHMLVkHAFWgAAAABJRU5ErkJggg==\n    --===============1438169132528273974==--\n\
        \nThe request contains multiple parts and is structured as follows.\n\nThe\
        \ first part is the JSON document that describes the snippet's\nproperties\
        \ or meta data. It either has to be the first part, or the\nrequest's `Content-Type`\
        \ header must contain the `start` parameter to\npoint to it.\n\nThe remaining\
        \ parts are the files of which there can be zero or more.\nEach file part\
        \ should contain the `Content-ID` MIME header through\nwhich the JSON meta\
        \ data's `files` element addresses it. The value\nshould be the name of the\
        \ file.\n\n`Content-Disposition` is an optional MIME header. The header's\n\
        optional `filename` parameter can be used to specify the file name\nthat Bitbucket\
        \ should use when writing the file to disk. When present,\n`filename` takes\
        \ precedence over the value of `Content-ID`.\n\nWhen the JSON body omits the\
        \ `files` element, the remaining parts are\nnot ignored. Instead, each file\
        \ is added to the new snippet as if its\nname was explicitly linked (the use\
        \ of the `files` elements is\nmandatory for some operations like deleting\
        \ or renaming files).\n\n\nmultipart/form-data\n-------------------\n\nThe\
        \ use of JSON for the snippet's meta data is optional. Meta data can\nalso\
        \ be supplied as regular form fields in a more conventional\n`multipart/form-data`\
        \ request:\n\n    $ curl -X POST -u credentials https://api.bitbucket.org/2.0/snippets\
        \               -F title=\"My snippet\"               -F file=@foo.txt -F\
        \ file=@image.png\n\n    POST /2.0/snippets HTTP/1.1\n    Content-Length:\
        \ 951\n    Content-Type: multipart/form-data; boundary=----------------------------63a4b224c59f\n\
        \n    ------------------------------63a4b224c59f\n    Content-Disposition:\
        \ form-data; name=\"file\"; filename=\"foo.txt\"\n    Content-Type: text/plain\n\
        \n    foo\n\n    ------------------------------63a4b224c59f\n    Content-Disposition:\
        \ form-data; name=\"file\"; filename=\"image.png\"\n    Content-Type: application/octet-stream\n\
        \n    ?PNG\n\n    IHDR?1??I.....\n    ------------------------------63a4b224c59f\n\
        \    Content-Disposition: form-data; name=\"title\"\n\n    My snippet\n  \
        \  ------------------------------63a4b224c59f--\n\nHere the meta data properties\
        \ are included as flat, top-level form\nfields. The file attachments use the\
        \ `file` field name. To attach\nmultiple files, simply repeat the field.\n\
        \nThe advantage of `multipart/form-data` over `multipart/related` is\nthat\
        \ it can be easier to build clients.\n\nEssentially all properties are optional,\
        \ `title` and `files` included.\n\n\nSharing and Visibility\n----------------------\n\
        \nSnippets can be either public (visible to anyone on Bitbucket, as well\n\
        as anonymous users), or private (visible only to the owner, creator\nand members\
        \ of the team in case the snippet is owned by a team). This\nis controlled\
        \ through the snippet's `is_private` element:\n\n* **is_private=false** --\
        \ everyone, including anonymous users can view\n  the snippet\n* **is_private=true**\
        \ -- only the owner and team members (for team\n  snippets) can view it\n\n\
        To create the snippet under a team account, just append the team name\nto\
        \ the URL (see `/2.0/snippets/{username}`)."
      security:
      - oauth2:
        - "snippet:write"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/pipelines_config/ssh/known_hosts/{known_host_uuid}:
    get:
      tags:
      - "pipelines"
      description: "Retrieve a repository level known host."
      operationId: "getRepositoryPipelineKnownHost"
    put:
      tags:
      - "pipelines"
      description: "Update a repository level known host."
      operationId: "updateRepositoryPipelineKnownHost"
    delete:
      tags:
      - "pipelines"
      description: "Delete a repository level known host."
      operationId: "deleteRepositoryPipelineKnownHost"
  /repositories/{username}/{repo_slug}/pullrequests/{pull_request_id}:
    get:
      tags:
      - "pullrequests"
      description: "Returns the specified pull request."
      security:
      - oauth2:
        - "pullrequest"
      - basic: []
      - api_key: []
    put:
      tags:
      - "pullrequests"
      description: "Mutates the specified pull request.\n\nThis can be used to change\
        \ the pull request's branches or description.\n\nOnly open pull requests can\
        \ be mutated."
      security:
      - oauth2:
        - "pullrequest:write"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/pullrequests/{pull_request_id}/comments:
    get:
      tags:
      - "pullrequests"
      description: "Returns a paginated list of the pull request's comments.\n\nThis\
        \ includes both global, inline comments and replies.\n\nThe default sorting\
        \ is oldest to newest and can be overridden with\nthe `sort` query parameter.\n\
        \nThis endpoint also supports filtering and sorting of the results. See\n\
        [filtering and sorting](../../../../../../meta/filtering) for more\ndetails."
      security:
      - oauth2:
        - "pullrequest"
      - basic: []
      - api_key: []
  /users/{username}/search/code:
    get:
  /repositories/{username}/{repo_slug}/pullrequests/{pull_request_id}/decline:
    post:
      tags:
      - "pullrequests"
      description: "Declines the pull request."
      security:
      - oauth2:
        - "pullrequest:write"
      - basic: []
      - api_key: []
  /user/emails:
    get:
      tags:
      - "users"
      description: "Returns all the authenticated user's email addresses. Both\nconfirmed\
        \ and unconfirmed."
      security:
      - oauth2:
        - "email"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/pullrequests:
    get:
      tags:
      - "pullrequests"
      description: "Returns a paginated list of all pull requests on the specified\n\
        repository. By default only open pull requests are returned. This can\nbe\
        \ controlled using the `state` query parameter. To retrieve pull\nrequests\
        \ that are in one of multiple states, repeat the `state`\nparameter for each\
        \ individual state.\n\nThis endpoint also supports filtering and sorting of\
        \ the results. See\n[filtering and sorting](../../../../meta/filtering) for\
        \ more details."
      security:
      - oauth2:
        - "pullrequest"
      - basic: []
      - api_key: []
    post:
      tags:
      - "pullrequests"
      description: "Creates a new pull request."
      security:
      - oauth2:
        - "pullrequest:write"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/commits:
    get:
      tags:
      - "commits"
      description: "These are the repository's commits. They are paginated and returned\n\
        in reverse chronological order, similar to the output of `git log` and\n`hg\
        \ log`. Like these tools, the DAG can be filtered.\n\n## GET /repositories/{username}/{repo_slug}/commits/\n\
        \nReturns all commits in the repo in topological order (newest commit\nfirst).\
        \ All branches and tags are included (similar to\n`git log --all` and `hg\
        \ log`).\n\n## GET /repositories/{username}/{repo_slug}/commits/master\n\n\
        Returns all commits on rev `master` (similar to `git log master`,\n`hg log\
        \ master`).\n\n## GET /repositories/{username}/{repo_slug}/commits/dev?exclude=master\n\
        \nReturns all commits on ref `dev`, except those that are reachable on\n`master`\
        \ (similar to `git log dev ^master`).\n\n## GET /repositories/{username}/{repo_slug}/commits/?exclude=master\n\
        \nReturns all commits in the repo that are not on master\n(similar to `git\
        \ log --all ^master`).\n\n## GET /repositories/{username}/{repo_slug}/commits/?include=foo&include=bar&exclude=fu&exclude=fubar\n\
        \nReturns all commits that are on refs `foo` or `bar`, but not on `fu` or\n\
        `fubar` (similar to `git log foo bar ^fu ^fubar`).\n\nBecause the response\
        \ could include a very large number of commits, it\nis paginated. Follow the\
        \ 'next' link in the response to navigate to the\nnext page of commits. As\
        \ with other paginated resources, do not\nconstruct your own links.\n\nWhen\
        \ the include and exclude parameters are more than can fit in a\nquery string,\
        \ clients can use a `x-www-form-urlencoded` POST instead."
      security:
      - oauth2:
        - "repository"
      - basic: []
      - api_key: []
    post:
      tags:
      - "commits"
      description: "Identical to `GET /repositories/{username}/{repo_slug}/commits`,\n\
        except that POST allows clients to place the include and exclude\nparameters\
        \ in the request body to avoid URL length issues.\n\n**Note that this resource\
        \ does NOT support new commit creation.**"
      security:
      - oauth2:
        - "repository"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/commit/{node}/statuses:
    get:
      tags:
      - "repositories"
      - "commitstatuses"
      description: "Returns all statuses (e.g. build results) for a specific commit."
      security:
      - oauth2:
        - "repository"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/commit/{sha}/comments:
    get:
      tags:
      - "commits"
      description: "Returns the commit's comments.\n\nThis includes both global and\
        \ inline comments.\n\nThe default sorting is oldest to newest and can be overridden\
        \ with\nthe `sort` query parameter."
      security:
      - oauth2:
        - "repository"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/commit/{revision}:
    get:
      tags:
      - "commits"
      description: "Returns the specified commit."
      security:
      - oauth2:
        - "repository"
      - basic: []
      - api_key: []
  /snippets/{username}:
    get:
      tags:
      - "snippets"
      description: "Identical to `/snippets`, except that the result is further filtered\n\
        by the snippet owner and only those that are owned by `{username}` are\nreturned."
      security:
      - oauth2:
        - "snippet"
      - basic: []
      - api_key: []
    post:
      tags:
      - "snippets"
      description: "Identical to `/snippets`, except that the new snippet will be\n\
        created under the account specified in the path parameter `{username}`."
      security:
      - oauth2:
        - "snippet:write"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/issues/{issue_id}/watch:
    get:
      tags:
      - "issue_tracker"
      description: "Indicated whether or not the authenticated user is watching this\n\
        issue."
      security:
      - oauth2:
        - "issue"
        - "account"
      - basic: []
      - api_key: []
    put:
      tags:
      - "issue_tracker"
      description: "Start watching this issue.\n\nTo start watching this issue, do\
        \ an empty PUT. The 204 status code\nindicates that the operation was successful."
      security:
      - oauth2:
        - "issue"
        - "account:write"
      - basic: []
      - api_key: []
    delete:
      tags:
      - "issue_tracker"
      description: "Stop watching this issue."
      security:
      - oauth2:
        - "issue:write"
        - "account:write"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/milestones/{milestone_id}:
    get:
      tags:
      - "issue_tracker"
      description: "Returns the specified issue tracker milestone object."
      security:
      - oauth2:
        - "issue"
      - basic: []
      - api_key: []
  /snippets/{username}/{encoded_id}/commits/{revision}:
    get:
      tags:
      - "snippets"
      description: ""
      security:
      - oauth2:
        - "snippet"
      - basic: []
      - api_key: []
  /teams:
    get:
      tags:
      - "teams"
      description: "Returns all the teams that the authenticated user is associated\n\
        with."
      security:
      - oauth2:
        - "team"
      - basic: []
      - api_key: []
  /user:
    get:
      tags:
      - "users"
      description: "Returns the currently logged in user."
      security:
      - oauth2:
        - "account"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/commits/{revision}:
    get:
      tags:
      - "commits"
      description: "These are the repository's commits. They are paginated and returned\n\
        in reverse chronological order, similar to the output of `git log` and\n`hg\
        \ log`. Like these tools, the DAG can be filtered.\n\n## GET /repositories/{username}/{repo_slug}/commits/\n\
        \nReturns all commits in the repo in topological order (newest commit\nfirst).\
        \ All branches and tags are included (similar to\n`git log --all` and `hg\
        \ log`).\n\n## GET /repositories/{username}/{repo_slug}/commits/master\n\n\
        Returns all commits on rev `master` (similar to `git log master`,\n`hg log\
        \ master`).\n\n## GET /repositories/{username}/{repo_slug}/commits/dev?exclude=master\n\
        \nReturns all commits on ref `dev`, except those that are reachable on\n`master`\
        \ (similar to `git log dev ^master`).\n\n## GET /repositories/{username}/{repo_slug}/commits/?exclude=master\n\
        \nReturns all commits in the repo that are not on master\n(similar to `git\
        \ log --all ^master`).\n\n## GET /repositories/{username}/{repo_slug}/commits/?include=foo&include=bar&exclude=fu&exclude=fubar\n\
        \nReturns all commits that are on refs `foo` or `bar`, but not on `fu` or\n\
        `fubar` (similar to `git log foo bar ^fu ^fubar`).\n\nBecause the response\
        \ could include a very large number of commits, it\nis paginated. Follow the\
        \ 'next' link in the response to navigate to the\nnext page of commits. As\
        \ with other paginated resources, do not\nconstruct your own links.\n\nWhen\
        \ the include and exclude parameters are more than can fit in a\nquery string,\
        \ clients can use a `x-www-form-urlencoded` POST instead."
      security:
      - oauth2:
        - "repository"
      - basic: []
      - api_key: []
    post:
      tags:
      - "commits"
      description: "Identical to `GET /repositories/{username}/{repo_slug}/commits`,\n\
        except that POST allows clients to place the include and exclude\nparameters\
        \ in the request body to avoid URL length issues.\n\n**Note that this resource\
        \ does NOT support new commit creation.**"
      security:
      - oauth2:
        - "repository"
      - basic: []
      - api_key: []
  /snippets/{username}/{encoded_id}/comments:
    get:
      tags:
      - "snippets"
      description: "Used to retrieve a paginated list of all comments for a specific\n\
        snippet.\n\nThis resource works identical to commit and pull request comments.\n\
        \nThe default sorting is oldest to newest and can be overridden with\nthe\
        \ `sort` query parameter."
      security:
      - oauth2:
        - "snippet"
      - basic: []
      - api_key: []
    post:
      tags:
      - "snippets"
      description: "Creates a new comment.\n\nThe only required field in the body\
        \ is `content.raw`.\n\nTo create a threaded reply to an existing comment,\
        \ include `parent.id`."
      security:
      - oauth2:
        - "snippet"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/pullrequests/{pull_request_id}/activity:
    get:
      tags:
      - "pullrequests"
      description: "Returns a paginated list of the pull request's activity log.\n\
        \nThis includes comments that were made by the reviewers, updates and\napprovals."
      security:
      - oauth2:
        - "pullrequest"
      - basic: []
      - api_key: []
  /repositories/{username}:
    get:
      tags:
      - "repositories"
      description: "Returns a paginated list of all repositories owned by the specified\n\
        account or UUID.\n\nThe result can be narrowed down based on the authenticated\
        \ user's role.\n\nE.g. with `?role=contributor`, only those repositories that\
        \ the\nauthenticated user has write access to are returned (this includes\
        \ any\nrepo the user is an admin on, as that implies write access).\n\nThis\
        \ endpoint also supports filtering and sorting of the results. See\n[filtering\
        \ and sorting](../../meta/filtering) for more details."
      security:
      - oauth2:
        - "repository"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/pullrequests/{pull_request_id}/merge:
    post:
      tags:
      - "pullrequests"
      description: "Merges the pull request."
      security:
      - oauth2:
        - "pullrequest:write"
      - basic: []
      - api_key: []
  /users/{username}/ssh-keys/:
    get:
      tags:
      - "ssh"
      description: "Returns a specific SSH public key belonging to a user.\n\nExample:\n\
        ```\n$ curl https://api.bitbucket.org/2.0/users/markadams-atl/ssh-keys/{fbe4bbab-f6f7-4dde-956b-5c58323c54b3}\n\
        \n{\n    \"comment\": \"user@myhost\",\n    \"created_on\": \"2018-03-14T13:17:05.196003+00:00\"\
        ,\n    \"key\": \"ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKqP3Cr632C2dNhhgKVcon4ldUSAeKiku2yP9O9/bDtY\"\
        ,\n    \"label\": \"\",\n    \"last_used\": \"2018-03-20T13:18:05.196003+00:00\"\
        ,\n    \"links\": {\n        \"self\": {\n            \"href\": \"https://api.bitbucket.org/2.0/users/markadams-atl/ssh-keys/b15b6026-9c02-4626-b4ad-b905f99f763a\"\
        \n        }\n    },\n    \"owner\": {\n        \"display_name\": \"Mark Adams\"\
        ,\n        \"links\": {\n            \"avatar\": {\n                \"href\"\
        : \"https://bitbucket.org/account/markadams-atl/avatar/32/\"\n           \
        \ },\n            \"html\": {\n                \"href\": \"https://bitbucket.org/markadams-atl/\"\
        \n            },\n            \"self\": {\n                \"href\": \"https://api.bitbucket.org/2.0/users/markadams-atl\"\
        \n            }\n        },\n        \"type\": \"user\",\n        \"username\"\
        : \"markadams-atl\",\n        \"uuid\": \"{d7dd0e2d-3994-4a50-a9ee-d260b6cefdab}\"\
        \n    },\n    \"type\": \"ssh_key\",\n    \"uuid\": \"{b15b6026-9c02-4626-b4ad-b905f99f763a}\"\
        \n}\n```"
      security:
      - oauth2:
        - "account"
      - basic: []
      - api_key: []
    put:
      tags:
      - "ssh"
      description: "Updates a specific SSH public key on a user's account\n\nNote:\
        \ Only the 'comment' field can be updated using this API. To modify the key\
        \ or comment values, you must delete and add the key again.\n\nExample:\n\
        ```\n$ curl -X PUT -H \"Content-Type: application/json\" -d '{\"label\": \"\
        Work key\"}' https://api.bitbucket.org/2.0/users/markadams-atl/ssh-keys/{b15b6026-9c02-4626-b4ad-b905f99f763a}\n\
        \n{\n    \"comment\": \"\",\n    \"created_on\": \"2018-03-14T13:17:05.196003+00:00\"\
        ,\n    \"key\": \"ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKqP3Cr632C2dNhhgKVcon4ldUSAeKiku2yP9O9/bDtY\"\
        ,\n    \"label\": \"Work key\",\n    \"last_used\": \"2018-03-20T13:18:05.196003+00:00\"\
        ,\n    \"links\": {\n        \"self\": {\n            \"href\": \"https://api.bitbucket.org/2.0/users/markadams-atl/ssh-keys/b15b6026-9c02-4626-b4ad-b905f99f763a\"\
        \n        }\n    },\n    \"owner\": {\n        \"display_name\": \"Mark Adams\"\
        ,\n        \"links\": {\n            \"avatar\": {\n                \"href\"\
        : \"https://bitbucket.org/account/markadams-atl/avatar/32/\"\n           \
        \ },\n            \"html\": {\n                \"href\": \"https://bitbucket.org/markadams-atl/\"\
        \n            },\n            \"self\": {\n                \"href\": \"https://api.bitbucket.org/2.0/users/markadams-atl\"\
        \n            }\n        },\n        \"type\": \"user\",\n        \"username\"\
        : \"markadams-atl\",\n        \"uuid\": \"{d7dd0e2d-3994-4a50-a9ee-d260b6cefdab}\"\
        \n    },\n    \"type\": \"ssh_key\",\n    \"uuid\": \"{b15b6026-9c02-4626-b4ad-b905f99f763a}\"\
        \n}\n```"
      security:
      - oauth2:
        - "account:write"
      - basic: []
      - api_key: []
    delete:
      tags:
      - "ssh"
      description: "Deletes a specific SSH public key from a user's account\n\nExample:\n\
        ```\n$ curl -X DELETE https://api.bitbucket.org/2.0/users/markadams-atl/ssh-keys/{b15b6026-9c02-4626-b4ad-b905f99f763a}\n\
        ```"
      security:
      - oauth2:
        - "account:write"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/pipelines_config/ssh/key_pair:
    get:
      tags:
      - "pipelines"
      description: "Retrieve the repository SSH key pair excluding the SSH private\
        \ key. The private key is a write only field and will never be exposed in\
        \ the logs or the REST API."
      operationId: "getRepositoryPipelineSshKeyPair"
    put:
      tags:
      - "pipelines"
      description: "Create or update the repository SSH key pair. The private key\
        \ will be set as a default SSH identity in your build container."
      operationId: "updateRepositoryPipelineKeyPair"
    delete:
      tags:
      - "pipelines"
      description: "Delete the repository SSH key pair."
      operationId: "deleteRepositoryPipelineKeyPair"
  /users/{username}/ssh-keys:
    get:
      tags:
      - "ssh"
      description: "Returns a paginated list of the user's SSH public keys.\n\nExample:\n\
        \n```\n$ curl https://api.bitbucket.org/2.0/users/markadams-atl/ssh-keys\n\
        {\n    \"page\": 1,\n    \"pagelen\": 10,\n    \"size\": 1,\n    \"values\"\
        : [\n        {\n            \"comment\": \"user@myhost\",\n            \"\
        created_on\": \"2018-03-14T13:17:05.196003+00:00\",\n            \"key\":\
        \ \"ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKqP3Cr632C2dNhhgKVcon4ldUSAeKiku2yP9O9/bDtY\"\
        ,\n            \"label\": \"\",\n            \"last_used\": \"2018-03-20T13:18:05.196003+00:00\"\
        ,\n            \"links\": {\n                \"self\": {\n               \
        \     \"href\": \"https://api.bitbucket.org/2.0/users/markadams-atl/ssh-keys/b15b6026-9c02-4626-b4ad-b905f99f763a\"\
        \n                }\n            },\n            \"owner\": {\n          \
        \      \"display_name\": \"Mark Adams\",\n                \"links\": {\n \
        \                   \"avatar\": {\n                        \"href\": \"https://bitbucket.org/account/markadams-atl/avatar/32/\"\
        \n                    },\n                    \"html\": {\n              \
        \          \"href\": \"https://bitbucket.org/markadams-atl/\"\n          \
        \          },\n                    \"self\": {\n                        \"\
        href\": \"https://api.bitbucket.org/2.0/users/markadams-atl\"\n          \
        \          }\n                },\n                \"type\": \"user\",\n  \
        \              \"username\": \"markadams-atl\",\n                \"uuid\"\
        : \"{d7dd0e2d-3994-4a50-a9ee-d260b6cefdab}\"\n            },\n           \
        \ \"type\": \"ssh_key\",\n            \"uuid\": \"{b15b6026-9c02-4626-b4ad-b905f99f763a}\"\
        \n        }\n    ]\n}\n```"
      security:
      - oauth2:
        - "account"
      - basic: []
      - api_key: []
    post:
      tags:
      - "ssh"
      description: "Adds a new SSH public key to the specified user account and returns\
        \ the resulting key.\n\nExample:\n```\n$ curl -X POST -H \"Content-Type: application/json\"\
        \ -d '{\"key\": \"ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKqP3Cr632C2dNhhgKVcon4ldUSAeKiku2yP9O9/bDtY\
        \ user@myhost\"}' https://api.bitbucket.org/2.0/users/markadams-atl/ssh-keys\n\
        \n{\n    \"comment\": \"user@myhost\",\n    \"created_on\": \"2018-03-14T13:17:05.196003+00:00\"\
        ,\n    \"key\": \"ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKqP3Cr632C2dNhhgKVcon4ldUSAeKiku2yP9O9/bDtY\"\
        ,\n    \"label\": \"\",\n    \"last_used\": \"2018-03-20T13:18:05.196003+00:00\"\
        ,\n    \"links\": {\n        \"self\": {\n            \"href\": \"https://api.bitbucket.org/2.0/users/markadams-atl/ssh-keys/b15b6026-9c02-4626-b4ad-b905f99f763a\"\
        \n        }\n    },\n    \"owner\": {\n        \"display_name\": \"Mark Adams\"\
        ,\n        \"links\": {\n            \"avatar\": {\n                \"href\"\
        : \"https://bitbucket.org/account/markadams-atl/avatar/32/\"\n           \
        \ },\n            \"html\": {\n                \"href\": \"https://bitbucket.org/markadams-atl/\"\
        \n            },\n            \"self\": {\n                \"href\": \"https://api.bitbucket.org/2.0/users/markadams-atl\"\
        \n            }\n        },\n        \"type\": \"user\",\n        \"username\"\
        : \"markadams-atl\",\n        \"uuid\": \"{d7dd0e2d-3994-4a50-a9ee-d260b6cefdab}\"\
        \n    },\n    \"type\": \"ssh_key\",\n    \"uuid\": \"{b15b6026-9c02-4626-b4ad-b905f99f763a}\"\
        \n}\n```"
      security:
      - oauth2:
        - "account:write"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/issues/{issue_id}/changes/{change_id}:
    get:
      tags:
      - "issue_tracker"
      description: "Returns the specified issue change object.\n\nThis resource is\
        \ only available on repositories that have the issue\ntracker enabled."
      security:
      - oauth2:
        - "issue"
      - basic: []
      - api_key: []
  /teams/{username}/followers:
    get:
      tags:
      - "teams"
      description: "Returns the list of accounts that are following this team."
      security:
      - oauth2: []
      - basic: []
      - api_key: []
  /snippets/{username}/{encoded_id}/{node_id}/files/{path}:
    get:
      tags:
      - "snippets"
      description: "Retrieves the raw contents of a specific file in the snippet.\
        \ The\n`Content-Disposition` header will be \"attachment\" to avoid issues\
        \ with\nmalevolent executable files.\n\nThe file's mime type is derived from\
        \ its filename and returned in the\n`Content-Type` header.\n\nNote that for\
        \ text files, no character encoding is included as part of\nthe content type."
      security:
      - oauth2:
        - "snippet"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/pipelines/{pipeline_uuid}/steps/{step_uuid}/log:
    get:
      tags:
      - "pipelines"
      description: "Retrieve the log file for a given step of a pipeline.\n\nThis\
        \ endpoint supports (and encourages!) the use of [HTTP Range requests](https://tools.ietf.org/html/rfc7233)\
        \ to deal with potentially very large log files."
      operationId: "getPipelineStepLogForRepository"
  /addon/linkers/{linker_key}:
    get:
      tags:
      - "addon"
      description: ""
      security:
      - oauth2: []
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/refs/tags:
    get:
      tags:
      - "refs"
      description: ""
      security:
      - oauth2:
        - "repository"
      - basic: []
      - api_key: []
    post:
      tags:
      - "refs"
      description: "Creates a new tag in the specified repository.\n\nThe payload\
        \ of the POST should consist of a JSON document that\ncontains the name of\
        \ the tag and the target hash.\n\n```\n{\n    \"name\" : \"new tag name\"\
        ,\n    \"target\" : {\n        \"hash\" : \"target commit hash\",\n    }\n\
        }\n```\n\nThis endpoint does support using short hash prefixes for the commit\n\
        hash, but it may return a 400 response if the provided prefix is\nambiguous.\
        \ Using a full commit hash is the preferred approach."
      security:
      - oauth2:
        - "repository:write"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/commit/{node}/approve:
    post:
      tags:
      - "commits"
      description: "Approve the specified commit as the authenticated user.\n\nThis\
        \ operation is only available to users that have explicit access to\nthe repository.\
        \ In contrast, just the fact that a repository is\npublicly accessible to\
        \ users does not give them the ability to approve\ncommits."
      security:
      - oauth2:
        - "repository:write"
      - basic: []
      - api_key: []
    delete:
      tags:
      - "commits"
      description: "Redact the authenticated user's approval of the specified commit.\n\
        \nThis operation is only available to users that have explicit access to\n\
        the repository. In contrast, just the fact that a repository is\npublicly\
        \ accessible to users does not give them the ability to approve\ncommits."
      security:
      - oauth2:
        - "repository:write"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/pipelines_config/schedules/{schedule_uuid}/executions/:
    get:
      tags:
      - "pipelines"
      description: "Retrieve the executions of a given schedule."
      operationId: "getRepositoryPipelineScheduleExecutions"
  /repositories/{username}/{repo_slug}/pullrequests/{pull_request_id}/commits:
    get:
      tags:
      - "pullrequests"
      description: "Returns a paginated list of the pull request's commits.\n\nThese\
        \ are the commits that are being merged into the destination\nbranch when\
        \ the pull requests gets accepted."
      security:
      - oauth2:
        - "pullrequest"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/src:
    get:
      tags:
      - "source"
      - "repositories"
      description: "This endpoint redirects the client to the directory listing of\
        \ the\nroot directory on the main branch.\n\nThis is equivalent to directly\
        \ hitting\n[/2.0/repositories/{username}/{repo_slug}/src/{node}/{path}](src/%7Bnode%7D/%7Bpath%7D)\n\
        without having to know the name or SHA1 of the repo's main branch.\n\nTo create\
        \ new commits, [POST to this endpoint](#post)"
      security:
      - oauth2:
        - "repository"
      - basic: []
      - api_key: []
    post:
      tags:
      - "source"
      - "repositories"
      description: "This endpoint is used to create new commits in the repository\
        \ by\nuploading files.\n\nTo add a new file to a repository:\n\n```\n$ curl\
        \ https://api.bitbucket.org/2.0/repositories/username/slug/src \\\n    -F\
        \ /repo/path/to/image.png=@image.png\n```\n\nThis will create a new commit\
        \ on top of the main branch, inheriting the\ncontents of the main branch,\
        \ but adding (or overwriting) the\n`image.png` file to the repository in the\
        \ `/repo/path/to` directory.\n\nThis endpoint accepts `multipart/form-data`\
        \ (as in the example above), as\nwell as `application/x-www-form-urlencoded`.\n\
        \n## multipart/form-data\n\nA `multipart/form-data` post contains a series\
        \ of \"form fields\" that\nidentify both the individual files that are being\
        \ uploaded, as well as\nadditional, optional meta data.\n\nFiles are uploaded\
        \ in file form fields (those that have a\n`Content-Disposition` parameter)\
        \ whose field names point to the remote\npath in the repository where the\
        \ file should be stored. Path field\nnames are always interpreted to be absolute\
        \ from the root of the\nrepository, regardless whether the client uses a leading\
        \ slash (as the\nabove `curl` example did).\n\nFile contents are treated as\
        \ bytes and are not decoded as text.\n\nThe commit message, as well as other\
        \ non-file meta data for the\nrequest, is sent along as normal form field\
        \ elements. Meta data fields\nshare the same namespace as the file objects.\
        \ For `multipart/form-data`\nbodies that should not lead to any ambiguity,\
        \ as the\n`Content-Disposition` header will contain the `filename` parameter\
        \ to\ndistinguish between a file named \"message\" and the commit message\
        \ field.\n\n## application/x-www-form-urlencoded\n\nIt is also possible to\
        \ upload new files using a simple\n`application/x-www-form-urlencoded` POST.\
        \ This can be convenient when\nuploading pure text files:\n\n```\n$ curl https://api.bitbucket.org/2.0/repositories/atlassian/bbql/src/\
        \ \\\n  --data-urlencode \"/path/to/me.txt=Lorem ipsum.\" \\\n  --data-urlencode\
        \ \"message=Initial commit\" \\\n  --data-urlencode \"author=Erik van Zijst\
        \ <erik.van.zijst@gmail.com>\"\n```\n\nThere could be a field name clash if\
        \ a client were to upload a file\nnamed \"message\", as this filename clashes\
        \ with the meta data property\nfor the commit message. To avoid this and to\
        \ upload files whose names\nclash with the meta data properties, use a leading\
        \ slash for the files,\ne.g. `curl --data-urlencode \"/message=file contents\"\
        `.\n\nWhen an explicit slash is omitted for a file whose path matches that\
        \ of\na meta data parameter, then it is interpreted as meta data, not as a\n\
        file.\n\n## Executables and links\n\nWhile this API aims to facilitate the\
        \ most common use cases, it is\npossible to perform some more advanced operations\
        \ like creating a new\nsymlink in the repository, or creating an executable\
        \ file.\n\nFiles can be supplied with a `x-attributes` value in the\n`Content-Disposition`\
        \ header. For example, to upload an executable\nfile, as well as create a\
        \ symlink from `README.txt` to `README`:\n\n```\n--===============1438169132528273974==\n\
        Content-Type: text/plain; charset=\"us-ascii\"\nMIME-Version: 1.0\nContent-Transfer-Encoding:\
        \ 7bit\nContent-ID: \"bin/shutdown.sh\"\nContent-Disposition: attachment;\
        \ filename=\"shutdown.sh\"; x-attributes:\"executable\"\n\n#!/bin/sh\nhalt\n\
        \n--===============1438169132528273974==\nContent-Type: text/plain; charset=\"\
        us-ascii\"\nMIME-Version: 1.0\nContent-Transfer-Encoding: 7bit\nContent-ID:\
        \ \"/README.txt\"\nContent-Disposition: attachment; filename=\"README.txt\"\
        ; x-attributes:\"link\"\n\nREADME\n--===============1438169132528273974==--\n\
        ```\n\nLinks are files that contain the target path and have\n`x-attributes:\"\
        link\"` set.\n\nWhen overwriting links with files, or vice versa, the newly\
        \ uploaded\nfile determines both the new contents, as well as the attributes.\
        \ That\nmeans uploading a file without specifying `x-attributes=\"link\"`\
        \ will\ncreate a regular file, even if the parent commit hosted a symlink\
        \ at\nthe same path.\n\nThe same applies to executables. When modifying an\
        \ existing executable\nfile, the form-data file element must include\n`x-attributes=\"\
        executable\"` in order to preserve the executable status\nof the file.\n\n\
        Note that this API does not support the creation or manipulation of\nsubrepos\
        \ / submodules."
      security:
      - oauth2:
        - "repository:write"
      - basic: []
      - api_key: []
  /snippets/{username}/{encoded_id}/{revision}/diff:
    get:
      tags:
      - "snippets"
      description: "Returns the diff of the specified commit against its first parent.\n\
        \nNote that this resource is different in functionality from the `patch`\n\
        resource.\n\nThe differences between a diff and a patch are:\n\n* patches\
        \ have a commit header with the username, message, etc\n* diffs support the\
        \ optional `path=foo/bar.py` query param to filter the\n  diff to just that\
        \ one file diff (not supported for patches)\n* for a merge, the diff will\
        \ show the diff between the merge commit and\n  its first parent (identical\
        \ to how PRs work), while patch returns a\n  response containing separate\
        \ patches for each commit on the second\n  parent's ancestry, up to the oldest\
        \ common ancestor (identical to\n  its reachability).\n\nNote that the character\
        \ encoding of the contents of the diff is\nunspecified as Git and Mercurial\
        \ do not track this, making it hard for\nBitbucket to reliably determine this."
      security:
      - oauth2:
        - "snippet"
      - basic: []
      - api_key: []
  /snippets/{username}/{encoded_id}/watchers:
    get:
      tags:
      - "snippets"
      description: "Returns a paginated list of all users watching a specific snippet."
      security:
      - oauth2:
        - "snippet"
      - basic: []
      - api_key: []
      deprecated: true
  /repositories/{username}/{repo_slug}/branch-restrictions/{id}:
    get:
      tags:
      - "branchrestrictions"
      description: "Returns a specific branch restriction rule."
      security:
      - oauth2:
        - "repository:admin"
      - basic: []
      - api_key: []
    put:
      tags:
      - "branchrestrictions"
      description: "Updates an existing branch restriction rule.\n\nFields not present\
        \ in the request body are ignored.\n\nSee [`POST`](../../branch-restrictions#post)\
        \ for details."
      security:
      - oauth2:
        - "repository:admin"
      - basic: []
      - api_key: []
    delete:
      tags:
      - "branchrestrictions"
      description: "Deletes an existing branch restriction rule."
      security:
      - oauth2:
        - "repository:admin"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/pipelines/{pipeline_uuid}/steps/{step_uuid}:
    get:
      tags:
      - "pipelines"
      description: "Retrieve a given step of a pipeline."
      operationId: "getPipelineStepForRepository"
  /repositories/{username}/{repo_slug}/commit/{node}/statuses/build:
    post:
      tags:
      - "repositories"
      - "commitstatuses"
      description: "Creates a new build status against the specified commit.\n\nIf\
        \ the specified key already exists, the existing status object will\nbe overwritten.\n\
        \nWhen creating a new commit status, you can use a URI template for the URL.\n\
        Templates are URLs that contain variable names that Bitbucket will\nevaluate\
        \ at runtime whenever the URL is displayed anywhere similar to\nparameter\
        \ substitution in\n[Bitbucket Connect](https://developer.atlassian.com/bitbucket/concepts/context-parameters.html).\n\
        For example, one could use `https://foo.com/builds/{repository.full_name}`\n\
        which Bitbucket will turn into `https://foo.com/builds/foo/bar` at render\
        \ time.\nThe context variables available are `repository` and `commit`."
      security:
      - oauth2:
        - "repository"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}:
    get:
      tags:
      - "repositories"
      description: "Returns the object describing this repository."
      security:
      - oauth2:
        - "repository"
      - basic: []
      - api_key: []
    post:
      tags:
      - "repositories"
      description: "Creates a new repository.\n\nNote: In order to set the project\
        \ for the newly created repository,\npass in either the project key or the\
        \ project UUID as part of the\nrequest body as shown in the examples below:\n\
        \n```\n$ curl -X POST -H \"Content-Type: application/json\" -d '{\n    \"\
        scm\": \"git\",\n    \"project\": {\n        \"key\": \"MARS\"\n    }\n}'\
        \ https://api.bitbucket.org/2.0/repositories/teamsinspace/hablanding\n```\n\
        \nor\n\n```\n$ curl -X POST -H \"Content-Type: application/json\" -d '{\n\
        \    \"scm\": \"git\",\n    \"project\": {\n        \"key\": \"{ba516952-992a-4c2d-acbd-17d502922f96}\"\
        \n    }\n}' https://api.bitbucket.org/2.0/repositories/teamsinspace/hablanding\n\
        ```\n\nThe project must only be assigned for repositories belonging to a team.\n\
        If the repository owner is a team and the project is not provided, the\nrepository\
        \ is automatically assigned to the oldest project in the team.\n\nNote: In\
        \ the examples above, the username `teamsinspace`,\nand/or the repository\
        \ name `hablanding` can be replaced by UUIDs."
      security:
      - oauth2:
        - "repository:admin"
      - basic: []
      - api_key: []
    put:
      tags:
      - "repositories"
      description: "Since this endpoint can be used to both update and to create a\n\
        repository, the request body depends on the intent.\n\n### Creation\n\nSee\
        \ the POST documentation for the repository endpoint for an example\nof the\
        \ request body.\n\n### Update\n\nNote: Changing the `name` of the repository\
        \ will cause the location to\nbe changed. This is because the URL of the repo\
        \ is derived from the\nname (a process called slugification). In such a scenario,\
        \ it is\npossible for the request to fail if the newly created slug conflicts\n\
        with an existing repository's slug. But if there is no conflict,\nthe new\
        \ location will be returned in the `Location` header of the\nresponse."
      security:
      - oauth2:
        - "repository:admin"
      - basic: []
      - api_key: []
    delete:
      tags:
      - "repositories"
      description: "Deletes the repository. This is an irreversible operation.\n\n\
        This does not affect its forks."
      security:
      - oauth2:
        - "repository:delete"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/default-reviewers/{target_username}:
    get:
      tags:
      - "pullrequests"
      description: "Returns the specified reviewer.\n\nThis can be used to test whether\
        \ a user is among the repository's\ndefault reviewers list. A 404 indicates\
        \ that that specified user is not\na default reviewer."
      security:
      - oauth2:
        - "repository:admin"
      - basic: []
      - api_key: []
    put:
      tags:
      - "pullrequests"
      description: "Adds the specified user to the repository's list of default\n\
        reviewers.\n\nThis method is idempotent. Adding a user a second time has no\
        \ effect."
      security:
      - oauth2:
        - "repository:admin"
      - basic: []
      - api_key: []
    delete:
      tags:
      - "pullrequests"
      description: "Removes a default reviewer from the repository."
      security:
      - oauth2:
        - "repository:admin"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/issues/{issue_id}/comments:
    get:
      tags:
      - "issue_tracker"
      description: "Returns all comments that were made on the specified issue.\n\n\
        The default sorting is oldest to newest and can be overridden with\nthe `sort`\
        \ query parameter."
      security:
      - oauth2:
        - "issue"
      - basic: []
      - api_key: []
  /snippets/{username}/{encoded_id}/{node_id}:
    get:
      tags:
      - "snippets"
      description: "Identical to `GET /snippets/encoded_id`, except that this endpoint\n\
        can be used to retrieve the contents of the snippet as it was at an\nolder\
        \ revision, while `/snippets/encoded_id` always returns the\nsnippet's current\
        \ revision.\n\nNote that only the snippet's file contents are versioned, not\
        \ its\nmeta data properties like the title.\n\nOther than that, the two endpoints\
        \ are identical in behavior."
      security:
      - oauth2:
        - "snippet"
      - basic: []
      - api_key: []
    put:
      tags:
      - "snippets"
      description: "Identical to `UPDATE /snippets/encoded_id`, except that this endpoint\n\
        takes an explicit commit revision. Only the snippet's \"HEAD\"/\"tip\"\n(most\
        \ recent) version can be updated and requests on all other,\nolder revisions\
        \ fail by returning a 405 status.\n\nUsage of this endpoint over the unrestricted\
        \ `/snippets/encoded_id`\ncould be desired if the caller wants to be sure\
        \ no concurrent\nmodifications have taken place between the moment of the\
        \ UPDATE\nrequest and the original GET.\n\nThis can be considered a so-called\
        \ \"Compare And Swap\", or CAS\noperation.\n\nOther than that, the two endpoints\
        \ are identical in behavior."
      security:
      - oauth2:
        - "snippet:write"
      - basic: []
      - api_key: []
    delete:
      tags:
      - "snippets"
      description: "Deletes the snippet.\n\nNote that this only works for versioned\
        \ URLs that point to the latest\ncommit of the snippet. Pointing to an older\
        \ commit results in a 405\nstatus code.\n\nTo delete a snippet, regardless\
        \ of whether or not concurrent changes\nare being made to it, use `DELETE\
        \ /snippets/{encoded_id}` instead."
      security:
      - oauth2:
        - "snippet:write"
      - basic: []
      - api_key: []
  /repositories/{username}/{repo_slug}/pullrequests/{pull_request_id}/patch:
    get:
      tags:
      - "pullrequests"
      description: ""
      security:
      - oauth2:
        - "pullrequest"
      - basic: []
      - api_key: []
  /addon/linkers/{linker_key}/values/:
    get:
      tags:
      - "addon"
      description: ""
      security:
      - oauth2: []
      - basic: []
      - api_key: []
    delete:
      tags:
      - "addon"
      description: ""
      security:
      - oauth2: []
      - basic: []
      - api_key: []
  /users/{username}/hooks/{uid}:
    get:
      tags:
      - "users"
      - "webhooks"
      description: "Returns the webhook with the specified id installed on the given\n\
        user account."
      security:
      - oauth2:
        - "webhook"
      - basic: []
      - api_key: []
    put:
      tags:
      - "users"
      - "webhooks"
      description: "Updates the specified webhook subscription.\n\nThe following properties\
        \ can be mutated:\n\n* `description`\n* `url`\n* `active`\n* `events`"
      security:
      - oauth2:
        - "webhook"
      - basic: []
      - api_key: []
    delete:
      tags:
      - "users"
      - "webhooks"
      description: "Deletes the specified webhook subscription from the given user\n\
        account."
      security:
      - oauth2:
        - "webhook"
      - basic: []
      - api_key: []
  /teams/{username}/hooks:
    get:
      tags:
      - "teams"
      - "webhooks"
      description: "Returns a paginated list of webhooks installed on this team."
      security:
      - oauth2:
        - "webhook"
      - basic: []
      - api_key: []
    post:
      tags:
      - "teams"
      - "webhooks"
      description: "Creates a new webhook on the specified team.\n\nTeam webhooks\
        \ are fired for events from all repositories belonging to\nthat team account.\n\
        \nNote that only admins can install webhooks on teams."
      security:
      - oauth2:
        - "webhook"
      - basic: []
      - api_key: []
  /repositories:
    get:
      tags:
      - "repositories"
      description: "Returns a paginated list of all public repositories.\n\nThis endpoint\
        \ also supports filtering and sorting of the results. See\n[filtering and\
        \ sorting](../meta/filtering) for more details."
      security:
      - oauth2:
        - "repository"
      - basic: []
      - api_key: []
  /snippets/{username}/{encoded_id}/{revision}/patch:
    get:
      tags:
      - "snippets"
      description: "Returns the patch of the specified commit against its first\n\
        parent.\n\nNote that this resource is different in functionality from the\
        \ `diff`\nresource.\n\nThe differences between a diff and a patch are:\n\n\
        * patches have a commit header with the username, message, etc\n* diffs support\
        \ the optional `path=foo/bar.py` query param to filter the\n  diff to just\
        \ that one file diff (not supported for patches)\n* for a merge, the diff\
        \ will show the diff between the merge commit and\n  its first parent (identical\
        \ to how PRs work), while patch returns a\n  response containing separate\
        \ patches for each commit on the second\n  parent's ancestry, up to the oldest\
        \ common ancestor (identical to\n  its reachability).\n\nNote that the character\
        \ encoding of the contents of the patch is\nunspecified as Git and Mercurial\
        \ do not track this, making it hard for\nBitbucket to reliably determine this."
      security:
      - oauth2:
        - "snippet"
      - basic: []
      - api_key: []
  /teams/{username}/members:
    get:
      tags:
      - "teams"
      description: "All members of a team.\n\nReturns all members of the specified\
        \ team. Any member of any of the\nteam's groups is considered a member of\
        \ the team. This includes users\nin groups that may not actually have access\
        \ to any of the team's\nrepositories.\n\nNote that members using the \"private\
        \ profile\" feature are not included."
      security:
      - oauth2:
        - "account"
      - basic: []
      - api_key: []
securityDefinitions:
  basic:
    description: "Basic HTTP Authentication as per [RFC-2617](https://tools.ietf.org/html/rfc2617)\
      \ (Digest not supported). Note that Basic Auth with username and password as\
      \ credentials is only available on accounts that have 2-factor-auth / 2-step-verification\
      \ disabled. If you use 2fa, you should authenticate using OAuth2 instead."
    type: "basic"
  api_key:
    description: "API Keys can be used as Basic HTTP Authentication credentials and\
      \ provide a substitute for the account's actual username and password. API Keys\
      \ are only available to team accounts and there is only 1 key per account. API\
      \ Keys do not support scopes and have therefore access to all contents of the\
      \ account."
    type: "apiKey"
    name: "Authorization"
    in: "header"
  oauth2:
    description: "OAuth 2 as per [RFC-6749](https://tools.ietf.org/html/rfc6749)."
    type: "oauth2"
    authorizationUrl: "https://bitbucket.org/site/oauth2/authorize"
    tokenUrl: "https://bitbucket.org/site/oauth2/access_token"
    flow: "accessCode"
    scopes:
      wiki: "Read and modify your repositories' wikis"
      pullrequest:write: "Read and modify your repositories and their pull requests"
      pipeline:variable: "Access your repositories' build pipelines and configure\
        \ their variables"
      project:write: "Read and modify your team's project settings, and read and transfer\
        \ repositories within your team's projects"
      pipeline:write: "Access and rerun your repositories' build pipelines"
      snippet: "Read your snippets"
      repository:delete: "Delete your repositories"
      repository:write: "Read and modify your repositories"
      issue: "Read your repositories' issues"
      email: "Read your account's primary email address"
      repository: "Read your repositories"
      issue:write: "Read and modify your repositories' issues"
      webhook: "Read and modify your repositories' webhooks"
      pipeline: "Access your repositories' build pipelines"
      snippet:write: "Read and modify your snippets"
      account: "Read your account information"
      repository:admin: "Administer your repositories"
      pullrequest: "Read your repositories and their pull requests"
      project: "Read your team's project settings and read repositories contained\
        \ within your team's projects"
      team: "Read your team membership information"
      team:write: "Read and modify your team membership information"
      account:write: "Read and modify your account information"
x-radar-pages:
- content: "\n# Authentication methods\n\nThe purpose of this section is to describe\
    \ how to authenticate when making API calls using the Bitbucket REST API.\n\n\
    -----\n\n*On this page*\n\n* [Oauth 2](#oauth-2)\n  * [Making requests](#make-requests)\n\
    \  * [Repository cloning](#repo-clone)\n  * [Refresh tokens](#refresh-tokens)\n\
    * [Scopes](#scopes-bbc)\n* [App passwords](#app-pw)\n* [Basic auth](#basic-auth)\n\
    \n---\n\n# Bitbucket Cloud OAuth 2.0 <a name=\"oauth-2\"></a>\n\nOur OAuth 2 implementation\
    \ is merged in with our existing OAuth 1 in\nsuch a way that existing OAuth 1\
    \ consumers automatically become\nvalid OAuth 2 clients. The only thing you need\
    \ to do is edit your\nexisting consumer and configure a callback URL.\n\nOnce\
    \ that is in place, you'll have the following 2 URLs:\n\n    https://bitbucket.org/site/oauth2/authorize\n\
    \    https://bitbucket.org/site/oauth2/access_token\n\nFor obtaining access/bearer\
    \ tokens, we support all 4 of RFC-6749's grant\nflows, plus a custom Bitbucket\
    \ flow for exchanging JWT tokens for access tokens:\n\n\n### 1. Authorization\
    \ Code Grant (4.1)\n\nThe full-blown 3-LO flow. Request authorization from the\
    \ end user by\nsending their browser to:\n\n    https://bitbucket.org/site/oauth2/authorize?client_id={client_id}&response_type=code\n\
    \nThe callback includes the `?code={}` query parameter that you can swap\nfor\
    \ an access token:\n\n    $ curl -X POST -u \"client_id:secret\" \\\n      https://bitbucket.org/site/oauth2/access_token\
    \ \\\n      -d grant_type=authorization_code -d code={code}\n\n\n### 2. Implicit\
    \ Grant (4.2)\n\nThis flow is useful for browser-based add-ons that operate without\
    \ server-side backends.\n\nRequest the end user for authorization by directing\
    \ the browser to:\n\n    https://bitbucket.org/site/oauth2/authorize?client_id={client_id}&response_type=token\n\
    \nThat will redirect to your preconfigured callback URL with a fragment\ncontaining\
    \ the access token\n(`#access_token={token}&token_type=bearer`) where your page's\
    \ js can\npull it out of the URL.\n\n\n### 3. Resource Owner Password Credentials\
    \ Grant (4.3)\n\nUseful if you have the end user's password but you want to use\
    \ a more\nsecure end user access token instead. This method will not work when\
    \ the user has two-step verification enabled.\n\n    $ curl -X POST -u \"client_id:secret\"\
    \ \\\n      https://bitbucket.org/site/oauth2/access_token -d grant_type=password\
    \ \\\n      -d username={username} -d password={password}\n\n\n### 4. Client Credentials\
    \ Grant (4.4)\n\nSomewhat like our existing \"2-LO\" flow for OAuth 1. Obtain\
    \ an access\ntoken that represents not an end user, but the owner of the\nclient/consumer:\n\
    \n    $ curl -X POST -u \"client_id:secret\" \\\n      https://bitbucket.org/site/oauth2/access_token\
    \ \\\n      -d grant_type=client_credentials\n\n\n### 5. Bitbucket Cloud JWT Grant\
    \ (urn:bitbucket:oauth2:jwt)\n\nIf your Atlassian Connect add-on uses JWT authentication,\
    \ you can swap a\nJWT for an OAuth access token. The resulting access token represents\
    \ the\naccount for which the add-on is installed.\n\nMake sure you send the JWT\
    \ token in the Authorization request header\nusing the \"JWT\" scheme (case sensitive).\
    \ Note that this custom scheme\nmakes this different from HTTP Basic Auth (and\
    \ so you cannot use \"curl\n-u\").\n\n    $ curl -X POST -H \"Authorization: JWT\
    \ {jwt_token}\" \\\n      https://bitbucket.org/site/oauth2/access_token \\\n\
    \      -d grant_type=urn:bitbucket:oauth2:jwt\n\n\n## Making Requests <a name=\"\
    make-requests\"></a>\n\nOnce you have an access token, as per RFC-6750, you can\
    \ use it in a request in any of\nthe following ways (in decreasing order of desirability):\n\
    \n1. Send it in a request header: `Authorization: Bearer {access_token}`\n2. Include\
    \ it in a (application/x-www-form-urlencoded) POST body as `access_token={access_token}`\n\
    3. Put it in the query string of a non-POST: `?access_token={access_token}`\n\n\
    \n## Repository Cloning <a name=\"repo-clone\"></a>\n\nSince add-ons will not\
    \ be able to upload their own SSH keys to clone\nwith, access tokens can be used\
    \ as Basic HTTP Auth credentials to\nclone securely over HTTPS. This is much like\
    \ GitHub, yet slightly\ndifferent:\n\n    $ git clone https://x-token-auth:{access_token}@bitbucket.org/user/repo.git\n\
    \nThe literal string `x-token-auth` as a substitute for username is\nrequired\
    \ (note the difference with GitHub where the actual token is in\nthe username\
    \ field).\n\n\n## Refresh Tokens <a name=\"refresh-tokens\"></a>\n\nOur access\
    \ tokens expire in one hour. When this happens you'll get 401\nresponses.\n\n\
    Most access tokens grant responses (Implicit and JWT excluded). Therefore, you\
    \ should include a\nrefresh token that can then be used to generate a new access\
    \ token,\nwithout the need for end user participation:\n\n    $ curl -X POST -u\
    \ \"client_id:secret\" \\\n      https://bitbucket.org/site/oauth2/access_token\
    \ \\\n      -d grant_type=refresh_token -d refresh_token={refresh_token}\n\n\n\
    # Scopes for the Bitbucket Cloud REST API <a name=\"scopes-bbc\"></a>\n\nBitbucket's\
    \ API applies a number of privilege scopes to endpoints. In order to access an\
    \ endpoint, a request will need to have the necessary scopes.\n\nScopes are declared\
    \ in the descriptor as a list of strings, with each string being the name of a\
    \ unique scope.\n\nA descriptor lacking the `scopes` element is implicitly assumed\
    \ to require all scopes and as a result, Bitbucket will require end users authorizing/installing\
    \ the add-on\nto explicitly accept all scopes.\n\nOur best practice suggests you\
    \ add the scopes your add-on needs, but no more than it needs.\n\nInvalid scope\
    \ strings will cause the descriptor to be rejected and the installation to fail.\n\
    \nFollowing is the set of all currently available scopes.\n\n### repository\n\n\
    Gives the add-on read access to all the repositories the authorizing user has\
    \ access to.\nNote that this scope does not give access to a repository's pull\
    \ requests.\n\n* access to the repo's source code\n* clone over https\n* access\
    \ the the file browsing API\n* download zip archives of the repo's contents\n\
    * the ability to view and use the issue tracker on any repo (created issues, comment,\
    \ vote, etc)\n* the ability to view and use the wiki on any repo (create/edit\
    \ pages)\n\n### repository:write\n\nGives the add-on write (not admin) access\
    \ to all the repositories the authorizing user has access to. No distinction is\
    \ made between public or private repos. This scope implies `repository`, which\
    \ does not need to be requested separately.\nThis scope alone does not give access\
    \ to the pull requests API.\n\n* push access over https\n* fork repos\n\n### repository:admin\n\
    \nGives the add-on admin access to all the repositories the authorizing user has\
    \ access to. No distinction is made between public or private repos. This scope\
    \ does not imply `repository` or `repository:write`. It gives access to the admin\
    \ features of a repo only, not direct access to its contents. Of course it can\
    \ be (mis)used to grant read access to another user account who can then clone\
    \ the repo, but repos that need to read of write source code would also request\
    \ explicit read or write.\nThis scope comes with access to the following functionality:\n\
    \n* view and manipulate committer mappings\n* list and edit deploy keys\n* ability\
    \ to delete the repo\n* view and edit repo permissions\n* view and edit branch\
    \ permissions\n* import and export the issue tracker\n* enable and disable the\
    \ issue tracker\n* list and edit issue tracker version, milestones and components\n\
    * enable and disable the wiki\n* list and edit default reviewers\n* list and edit\
    \ repo links (Jira/Bamboo/Custom)\n* list and edit the repository web hooks\n\
    * initiate a repo ownership transfer\n\n### snippet\n\nGives the add-on read access\
    \ to all the snippets the authorizing user has access to.\nNo distinction is made\
    \ between public and private snippets (public snippets are accessible without\
    \ any form of authentication).\n\n* view any snippet\n* create snippet comments\n\
    \n### snippet:write\n\nGives the add-on write access to all the snippets the authorizing\
    \ user can edit.\nNo distinction is made between public and private snippets (public\
    \ snippets are accessible without any form of authentication).\nThis implies the\
    \ Snippet Read scope which does not need to be requested separately.\n\n* edit\
    \ snippets\n* delete snippets\n\n### issue\n\nAbility to interact with issue trackers\
    \ the way non-repo members can.\nThis scope does not imply any other scopes and\
    \ does not give implicit access to the repository the issue is attached to.\n\n\
    * view, list and search issues\n* create new issues\n* comment on issues\n* watch\
    \ issues\n* vote for issues\n\n### issue:write\n\nThis implies `issue`, but adds\
    \ the ability to transition and delete issues.\nThis scope does not imply any\
    \ other scopes and does not give implicit access to the repository the issue is\
    \ attached to.\n\n* transition issues\n* delete issues\n\n### wiki\n\nGives access\
    \ to wikis. No distinction is made between read and write as wikis are always\
    \ editable by anyone.\nThis scope does not imply any other scopes and does not\
    \ give implicit access to the repository the wiki is attached to.\n\n* view wikis\n\
    * create pages\n* edit pages\n* push to wikis\n* clone wikis\n\n### pullrequest\n\
    \nGives the add-on read access to pull requests.\nThis scope implies `repository`,\
    \ giving read access to the pull request's destination repository.\n\n* see and\
    \ list pull requests\n* create and resolve tasks\n\n### pullrequest:write\n\n\
    Implies `pullrequest` but adds the ability to create, merge and decline pull requests.\n\
    This scope implies `repository:write`, giving write access to the pull request's\
    \ destination repository. This is necessary to facilitate merging.\n\n* merge\
    \ pull requests\n* decline pull requests\n* create pull requests\n* comment on\
    \ pull requests\n* approve pull requests\n\n### email\n\nAbility to see the user's\
    \ primary email address. This should make it easier to use Bitbucket Cloud as\
    \ a login provider to add-ons or external applications.\n\n### account\n\nAbility\
    \ to see all the user's account information. Note that this does not include any\
    \ ability to mutate any of the data.\n\n* see all email addresses\n* language\n\
    * location\n* website\n* full name\n* SSH keys\n* user groups\n\n### account:write\n\
    \nAbility to change properties on the user's account.\n\n* delete the authorizing\
    \ user's account\n* manage the user's groups\n* manupilate a user's email addresses\n\
    * change username, display name and avatar\n\n### team\n\nThe ability to find\
    \ out what teams the current user is part of. This is covered by the teams endpoint.\n\
    \n* information about all the groups and teams I am a member or admin of\n\n\n\
    ### team:write\n\nImplies `team`, but adds the ability to manage the teams that\
    \ the authorizing user is an admin on.\n\n* manage team permissions\n\n### webhook\n\
    \nGives access to webhooks. This scope is required for any webhook\nrelated operation.\n\
    \nThis scope gives read access to existing webhook subscriptions on all\nresources\
    \ you can access, without needing further scopes. This means that\na client can\
    \ list all existing webhook subscriptions on repository\n`foo/bar` (assuming the\
    \ principal user has access to this repo). The\nadditional `repository` scope\
    \ is not required for this.\n\nLikewise, existing webhook subscriptions for a\
    \ repo's issue tracker can be\nretrieved without holding the `issue` scope. All\
    \ that is required is the\n`webhook` scope.\n\nHowever, to create a webhook for\
    \ `issue:created`, the client will need to\nhave both the `webhook` as well as\
    \ `issue` scope.\n\n* list webhook subscriptions on any accessible repository,\
    \ user, team, or snippet\n* create/update/delete webhook subscriptions\n\n\n#\
    \ App passwords <a name=\"app-pw\"></a>\n\nApp passwords allow two-step verification\
    \ users to make API calls to their Bitbucket account through apps such as Sourcetree.\n\
    \nSome important points about app passwords:\n\n* You cannot view an app password\
    \ or adjust permissions after you create the app password. Because app passwords\
    \ are encrypted on our database and cannot be viewed by anyone. They are essentially\
    \ designed to be disposable. If you need to change the scopes or lost the password\
    \ just create a new one.\n* You cannot use them to log into your Bitbucket account.\n\
    * You cannot use app passwords to manage team actions.\n\n    App passwords are\
    \ tied to an individual account's credentials and should not be shared. If you're\
    \ sharing your app password you're essentially giving direct, authenticated, access\
    \ to everything that password has been scoped to do with the Bitbucket API's.\n\
    \n* You can use them for API call authentication, even if you don't have two-step\
    \ verification enabled.\n* You can set permission scopes (specific access rights)\
    \ for each app password.\n\n### Create an app password\n\nTo create an app password:\n\
    \n1. Select **Avatar > Bitbucket settings**.\n2. Click **App passwords** in the\
    \ Access management section.\n3. Click **Create app password**.\n4. Give the app\
    \ password a name related to the application that will use the password.\n5. Select\
    \ the specific access and permissions you want this application password to have.\n\
    6. Copy the generated password and either record or paste it into the application\
    \ you want to give access. The password is only displayed this one time.\n\nThat's\
    \ all there is to creating an app password. See your applications documentation\
    \ for how to apply the app password for a specific application.\n\n## Basic auth\
    \ <a name=\"basic-auth\"></a>\n\nBasic HTTP Authentication as per [RFC-2617](https://tools.ietf.org/html/rfc2617)\
    \ (Digest not supported). Note that Basic Auth with username and password as credentials\
    \ is only available on accounts that have 2-factor-auth / 2-step-verification\
    \ disabled. If you use 2fa, you should authenticate using OAuth2 instead.\n"
  title: "Authentication methods"
  description: "How to authenticate API actions"
  key: "authentication"
  icon: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxOTcuNjQ3MyAxODYuODEzOCI+CiAgPGRlZnM+CiAgICA8c3R5bGU+CiAgICAgIC5jbHMtMSB7CiAgICAgICAgaXNvbGF0aW9uOiBpc29sYXRlOwogICAgICB9CgogICAgICAuY2xzLTIgewogICAgICAgIGZpbGw6ICNkZTM1MGI7CiAgICAgIH0KCiAgICAgIC5jbHMtMyB7CiAgICAgICAgZmlsbDogI2ZmNTYzMDsKICAgICAgfQoKICAgICAgLmNscy00IHsKICAgICAgICBmaWxsOiAjZGZlMWU1OwogICAgICAgIG1peC1ibGVuZC1tb2RlOiBtdWx0aXBseTsKICAgICAgfQoKICAgICAgLmNscy01IHsKICAgICAgICBmaWxsO[...]"
- content: "\n# Filter and sort API objects\n\nYou can query the 2.0 API for specific\
    \ objects using a simple language which resembles SQL.\n\n---\n**On this page**\n\
    \n* [Supported endpoints](#supp-endpoints)\n* [Operators](#operators)\n* [Data\
    \ types](#data-types)\n* [Querying](#querying)\n    * [Repositoriess](#query-repo)\n\
    \    * [Pull requests](#query-pullreq)\n    * [Issues](#query-issues)\n    * [Refs,\
    \ tags, bookmarks](#query-ref)\n* [Sorting query results](#query-sort)\n\n----\n\
    \n### Supported endpoints <a name=\"supp-endpoints\"></a>\n\nSeveral 2.0 API resources\
    \ that return collections of objects all support a single, shared, generic querying\
    \ language that is used to filter down a result set.\n\nCurrently, the endpoints\
    \ which support filtering and sorting include:\n\n    /2.0/repositories/{username}\n\
    \    /2.0/repositories/{username}/{slug}/refs\n    /2.0/repositories/{username}/{slug}/refs/branches\n\
    \    /2.0/repositories/{username}/{slug}/refs/tags\n    /2.0/repositories/{username}/{slug}/forks\n\
    \    /2.0/repositories/{username}/{slug}/src\n    /2.0/repositories/{username}/{slug}/issues\n\
    \    /2.0/repositories/{username}/{slug}/pullrequests\n\nFiltering and sorting\
    \ supports several distinct operators and data types as well as basic features,\
    \ like logical operators (AND, OR) as shown in the following examples:\n\n\t(state\
    \ = \"open\" OR state = \"new\") AND assignee = null\n\treporter.username != \"\
    evzijst\" AND priority >= \"major\"\n\t(title ~ \"unicode\" OR content.raw ~ \"\
    unicode\") AND created_on > 2015-10-04T14:00:00-07:00\n\nFilter queries can be\
    \ added to the URL using the q=<query> query parameter. To sort the response,\
    \ add sort=<field>. Note that the entire query string is put in the q parameter\
    \ and hence needs to be URL-encoded as shown in the following example:\n\n\t/2.0/repositories/foo/bar/issues?q=state=\"\
    new\"&sort=-updated_on\n\n### Operators <a name=\"operators\"></a>\n\nFiltering\
    \ and sorting supports the following operators:\n\n<table class='aui'>\n    <thead>\n\
    \        <tr>\n            <th>Operator</th>\n            <th>Definition</th>\n\
    \            <th>Example</th>\n        </tr>\n    </thead>\n    <tr>\n       \
    \ <td>\"=\"</td>\n        <td>test for equality </td>\n        <td><code>username\
    \ = \"evzijst\"</code></td>\n    </tr>\n    <tr>\n        <td>\"!=\"</td>\n  \
    \      <td>not equal</td>\n        <td><code>is_private != true</code></td>\n\
    \    </tr>\n    <tr>\n        <td>\"~\"</td>\n        <td>case-insensitive text\
    \ contains </td>\n        <td><code>description ~ \"beef\"</code></td>\n    </tr>\n\
    \    <tr>\n        <td>\"!~\"</td>\n        <td>case-insensitive not contains\
    \ </td>\n        <td><code>description !~ \"fubar\"</code></td>\n    </tr>\n \
    \   <tr>\n        <td>\">\"</td>\n        <td>greater than</td>\n        <td><code>priority\
    \ > \"major\"</code></td>\n    </tr>\n    <tr>\n        <td>\">=\"</td>\n    \
    \    <td>greater than or equal</td>\n        <td><code>priority <= \"trivial\"\
    </code></td>\n    </tr>\n    <tr>\n        <td>\"<\"</td>\n        <td>less than</td>\n\
    \        <td><code>id < 1234</code></td>\n    </tr>\n    <tr>\n        <td>\"\
    <=\"</td>\n        <td>less than or equal </td>\n        <td><code>updated_on\
    \ <= 2015-03-04</code></td>\n    </tr>\n</table>\n\n### Data types <a name=\"\
    data-types\"></a>\n\nFiltering and sorting supports the following data types:\n\
    \n<table class='aui'>\n    <thead>\n        <tr>\n            <th>Type</th>\n\
    \            <th>Description</th>\n            <th>Example</th>\n        </tr>\n\
    \    </thead>\n    <tr>\n        <td><b>String</b></td>\n        <td>any text\
    \ inside double quotes</td>\n        <td><code>\"foo\"</code></td>\n    </tr>\n\
    \    <tr>\n        <td><b>Number</b></td>\n        <td>arbitrary precision integers\
    \ and floats</td>\n        <td><code>1, -10.302</code></td>\n    </tr>\n    <tr>\n\
    \        <td><b>Null</b></td>\n        <td>to test for the absence of a value</td>\n\
    \        <td><code>null</code></td>\n    </tr>\n    <tr>\n        <td><b>boolean</b></td>\n\
    \        <td>the unquoted strings true or false</td>\n        <td><code>true,\
    \ false</code></td>\n    </tr>\n    <tr>\n        <td><b>datetime</b></td>\n \
    \       <td>an unquoted <a href=\"https://en.wikipedia.org/wiki/ISO_8601\">ISO-8601</a>\
    \ date time string with the timezone offset, milliseconds and entire time component\
    \ being optional</td>\n        <td><code>2015-03-04T14:08:59.123+02:00</code>,\
    \ <code>2015-03-04T14:08:59</code> Date time strings are assumed to be in UTC,\
    \ unless an explicit timezone offset is provided.</td>\n    </tr>\n</table>\n\n\
    ## Querying <a name=\"querying\"></a>\n\nObjects can be filtered based on their\
    \ properties. In principle, every element in an object's JSON document can be\
    \ used as a filter criterion.\n\n### Repositories <a name=\"query-repo\"></a>\n\
    \nYou can query the following fields in the repository resource:\n\n    uuid (string)\n\
    \    full_name (string)\n    scm (string)\n    owner (embedded user object)\n\
    \    name (string)\n    description (string)\n    created_on (datetime)\n    updated_on\
    \ (datetime)\n    size (number)\n    language (string)\n    parent (embedded repository\
    \ object)\n    fork_policy (string)\n    is_private (boolean)\n    has_issues\
    \ (boolean)\n    has_wiki (boolean)\n\nFields that contain embedded instances\
    \ of other object types (e.g. owner is an embedded user object, while parent is\
    \ an embedded repository) can be traversed recursively. For instance:\n\n\tparent.owner.username\
    \ = \"bitbucket\"\n\n### Pull Requests <a name=\"query-pullreq\"></a>\n\nYou can\
    \ query the following fields in the pull request resource:\n\n    id (number)\n\
    \    title (string)\n    description (string)\n    author (embedded user object)\n\
    \    reviewers (embedded user object)\n    state (string)\n    source.repository\
    \ (embedded repository object)\n    source.branch.name (string)\n    destination.repository\
    \ (embedded repository object)\n    destination.branch.name (string)\n    close_source_branch\
    \ (boolean)\n    closed_by (embedded user object)\n    reason (string)\n    created_on\
    \ (datetime)\n    updated_on (datetime)\n    task_count (number)\n    comment_count\
    \ (number)\n\n**For example**\n\nTo find pull requests which merge into master,\
    \ come from a fork of the repo rather than a branch inside the repo, and on which\
    \ I am a reviewer:\n\n```\nsource.repository.full_name != \"main/repo\" AND state\
    \ = \"OPEN\" AND reviewers.username = \"evzijst\" AND destination.branch.name\
    \ = \"master\"\n```\n```\n/2.0/repositories/main/repo/pullrequests?q=source.repository.full_name+%21%3D+%22main%2Frepo%22+AND+state+%3D+%22OPEN%22+AND+reviewers.username+%3D+%22evzijst%22+AND+destination.branch.name+%3D+%22master%22\n\
    ```\n\n### Issues <a name=\"query-issues\"></a>\n\nYou can query the following\
    \ fields in the issues resource:\n\n    id (number)\n    title (string)\n    reporter\
    \ (embedded user object)\n    assignee (embedded user object)\n    content.raw\
    \ (string)\n    created_on (datetime)\n    updated_on (datetime)\n    state (string)\n\
    \    kind (string)\n    priority (string)\n    version (string)\n    component\
    \ (string)\n    milestone (string)\n    watches (number)\n    votes (number)\n\
    \n**For example**\n\nTo find new or on-hold issues related to the UI, created\
    \ or updated in the last day (SF local time), that have not yet been assigned\
    \ to anyone:\n\n```\n(state = \"new\" OR state = \"on hold\") AND assignee = null\
    \ AND component = \"UI\" and updated_on > 2015-11-11T00:00:00-07:00\n```\n```\n\
    /2.0/repositories/main/repo/issues?q=%28state+%3D+%22new%22+OR+state+%3D+%22on+hold%22%29+AND+assignee+%3D+null+AND+component+%3D+%22UI%22+and+updated_on+%3E+2015-11-11T00%3A00%3A00-07%3A00\n\
    ```\n\n### Refs (Branches/Tags/Bookmarks) <a name=\"query-ref\"></a>\n\nYou can\
    \ query the following fields in the refs resource:\n\n    name (string)\n    type\
    \ (string)\n\n**For example**\n\nTo find all tags with the string \"2015\" in\
    \ the name:\n\n```\nname ~ \"2015\"\n```\n```\n/2.0/repositories/{username}/{slug}/refs/tags?q=name+%7E+%222015%22\n\
    ```\nOr all my branches and bookmarks:\n\n```\nname ~ \"erik/\"\n```\n```\n/2.0/repositories/{username}/{slug}/refs/tags?q=name+%7E+%22erik%2F%22\n\
    ```\n## Sorting query results <a name=\"query-sort\"></a>\n\nYou can sort result\
    \ sets using the ?sort=<field> query parameter, available on the same resources\
    \ that support filtering:\n\n* In principle, every field that can be queried can\
    \ also be used as a key for sorting.\n* By default the sort order is ascending.\
    \ To reverse the order, prefix the field name with a hyphen (e.g. ?sort=-updated_on).\n\
    * Only one field can be sorted on. Compound fields (e.g. sort on state first,\
    \ followed by updated_on) are not supported.\n\n\n"
  title: "Filter and sort API objects"
  description: "Query the 2.0 API for specific objects"
  key: "filtering"
  icon: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB2aWV3Qm94PSIwIDAgMTk0LjE5MTkgMTQ3LjYwOTIiPgogIDxkZWZzPgogICAgPHN0eWxlPgogICAgICAuY2xzLTEgewogICAgICAgIGlzb2xhdGlvbjogaXNvbGF0ZTsKICAgICAgfQoKICAgICAgLmNscy0yIHsKICAgICAgICBmaWxsOiAjY2ZkNGRiOwogICAgICB9CgogICAgICAuY2xzLTMsIC5jbHMtNCB7CiAgICAgICAgZmlsbDogIzg3NzdkOTsKICAgICAgfQoKICAgICAgLmNscy00IHsKICAgICAgICBtaXgtYmxlbmQtbW9kZTogbXVsdGlwbHk7CiAgICAgIH0KC[...]"
- content: "\n# Pagination\n\nEndpoints that return collections of objects should\
    \ always apply pagination.\nPaginated collections are always wrapped in the following\
    \ wrapper object:\n\n```json\n{\n  \"size\": 5421,\n  \"page\": 2,\n  \"pagelen:\
    \ 10,\n  \"next\": \"https://api.bitbucket.org/2.0/repositories/pypy/pypy/commits?page=3\"\
    ,\n  \"previous\": \"https://api.bitbucket.org/2.0/repositories/pypy/pypy/commits?page=1\"\
    ,\n  \"values\": [\n    ...\n  ]\n}\n```\n\nPagination is often page-bound, with\
    \ a query parameter page indicating which\npage is to be returned.\n\nHowever,\
    \ clients are not expected to construct URLs themselves by manipulating\nthe page\
    \ number query parameter. Instead, the response contains a link to the\nnext page.\
    \ This link should be treated as an opaque location that is not to be\nconstructed\
    \ by clients or even assumed to be predictable. The only contract\naround the\
    \ next link is that it will return the next chunk of results.\n\nLack of a next\
    \ link in the response indicates the end of the collection.\n\nThe paginated response\
    \ contains the following fields:\n\n<table class='aui'>\n    <thead>\n       \
    \ <tr>\n            <th>Field</th>\n            <th>Value</th>\n        </tr>\n\
    \    </thead>\n    <tr>\n        <td><code>size</code></td>\n        <td>Total\
    \ number of objects in the response. This is an optional element that is not provided\
    \ in all responses, as it can be expensive to compute. </td>\n    </tr>\n    <tr>\n\
    \        <td><code>page</code></td>\n        <td>Page number of the current results.\
    \ This is an optional element that is not provided in all responses.</td>\n  \
    \  </tr>\n    <tr>\n        <td><code>pagelen</code></td>\n        <td>Current\
    \ number of objects on the existing page. Globally, the minimum length is 10 and\
    \ the maximum is 100. Some APIs may specify a different default.</td>\n    </tr>\n\
    \    <tr>\n        <td><code>next</code></td>\n        <td>Link to the next page\
    \ if it exists. The last page of a collection does not have this value. Use this\
    \ link to navigate the result set and refrain from constructing your own URLs.</td>\n\
    \    </tr>\n    <tr>\n        <td><code>previous</code></td>\n        <td>Link\
    \ to previous page if it exists. A collections first page does not have this value.\
    \ This is an optional element that is not provided in all responses. Some result\
    \ sets strictly support forward navigation and never provide previous links. Clients\
    \ must anticipate that backwards navigation is not always available.\n       \
    \ Use this link to navigate the result set and refrain from constructing your\
    \ own URLs.</td>\n    </tr>\n    <tr>\n        <td><code>values</code></td>\n\
    \        <td>The list of objects. This contains at most <code>pagelen</code> objects.</td>\n\
    \    </tr>\n</table>\n\nThe link to the next page is included such that you don't\
    \ have to hardcode or construct any links.  Only values and next are guaranteed\
    \ (except the last page, which lacks next). This is because the previous and size\
    \ values can be expensive for some data sets.\n\nIt is important to realize that\
    \ Bitbucket support both list-based pagination and iterator-based pagination.\
    \ List-based pagination assumes that the collection is a discrete, immutable,\
    \ consistently ordered, finite array of objects with a fixed size. Clients navigate\
    \ a list-based collection by requesting offset-based chunks. In Bitbucket Cloud,\
    \ list-based responses include the optional size, page, and previous element.\
    \ The the next and previous links typically resemble something like /foo/bar?page=4.\n\
    \nHowever, not all result sets can be treated as immutable and finite – much like\
    \ how programming languages tend to distinguish between lists and arrays on one\
    \ hand and iterators or stream on the other. Where an list-based pagination offers\
    \ random access into any point in a collection, iterator-based pagination can\
    \ only navigate forward one element at a time. In Bitbucket such iterator-based\
    \ pagination contains the next link and pagelen elements, but not necessarily\
    \ anything else. In these cases, the next link's value often contains an unpredictable\
    \ hash instead of an explicit page number. The commits resource uses iterator-based\
    \ pagination.\n"
  title: "Pagination"
  description: "Learn more about pagination"
  key: "pagination"
  icon: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB2aWV3Qm94PSIwIDAgMjM4LjgyIDE1MS42Ij48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2IyZDRmZjt9LmNscy0ye2ZpbGw6IzRjOWFmZjt9LmNscy0ze2ZpbGw6IzAwNTJjYzt9LmNscy00e29wYWNpdHk6MC42O30uY2xzLTV7ZmlsbDp1cmwoI2xpbmVhci1ncmFkaWVudCk7fS5jbHMtNntmaWxsOnVybCgjbGluZWFyLWdyYWRpZW50LTIpO30uY2xzLTd7ZmlsbDp1cmwoI2xpbmVhci1ncmFkaWVudC0zKTt9LmNscy04e2ZpbGw6dXJsKCNsaW5lYXItZ3JhZGllbnQtN[...]"
- content: "\n# Partial responses\n\nBy default, each endpoint returns the full representation\
    \ of a resource and in\nsome cases that can be a lot of data. For example, retrieving\
    \ a list of pull\nrequests can amount to quite a large document.\n\nFor better\
    \ performance, you can ask the server to only return the fields you\nreally need\
    \ and to omit unwanted data. To request a partial response and to\nadd or remove\
    \ specific fields from a response, use the `fields` query\nparameter.\n\n\n##\
    \ Example\n\nMost API resources embed a substantial list of links pointing to\
    \ related\nresources. This saves the client from constructing its own URLs, but\
    \ is\nsomewhat wasteful when the client doesn't need them.\n\nTo significantly\
    \ reduce the size of the response, use `?fields=-links`:\n\n```\n$ curl https://api.bitbucket.org/2.0/users/evzijst?fields=-links\n\
    {\n  \"username\": \"evzijst\",\n  \"website\": \"\",\n  \"display_name\": \"\
    Erik van Zijst\",\n  \"uuid\": \"{a288a0ab-e13b-43f0-a689-c4ef0a249875}\",\n \
    \ \"created_on\": \"2010-07-07T05:16:36+00:00\",\n  \"location\": null,\n  \"\
    type\": \"user\"\n}\n```\n\n## Fields parameter syntax\n\nThe `fields` parameter\
    \ supports 3 modes of operation:\n\n1. Removal of select fields (e.g. `-links`)\n\
    2. Pulling in additional fields not normally returned by an endpoint, while\n\
    \   still getting all the default fields (e.g. `+reviewers`)\n3. Omitting all\
    \ fields, except those specified (e.g. `owner.username`)\n\nThe fields parameter\
    \ can contain a list of multiple comma-separated field names\n(e.g. `fields=owner.username,uuid,links.self.href`).\
    \ The parameter itself is\nnot repeated.\n\nAs discussed at [Condensed Versus\
    \ Full Objects](serialization#representations),\nmost objects that are embedded\
    \ inside other objects (like how `owner` is an\nembedded `user` object in `repository`)\
    \ appear in \"condensed\" form that omits\nmany fields. The `fields` parameter\
    \ allows us to pull in additional fields in\nsuch cases.\n\nFor example, the embedded\
    \ repository object in a pull request does not normally\ncontain its `owner`.\
    \ To add that in we can use:\n`+values.destination.repository.owner`.\n\n\n##\
    \ Wildcards\n\nThe asterisk can be used to match all fields on a particular level.\
    \ For\nexample, removing all entries from the `links` element can be done like\
    \ this:\n\n```\n$ curl https://api.bitbucket.org/2.0/users/evzijst?fields=-links.*\n\
    {\n  \"username\": \"evzijst\",\n  \"website\": \"\",\n  \"display_name\": \"\
    Erik van Zijst\",\n  \"uuid\": \"{a288a0ab-e13b-43f0-a689-c4ef0a249875}\",\n \
    \ \"links\": {},\n  \"created_on\": \"2010-07-07T05:16:36+00:00\",\n  \"location\"\
    : null,\n  \"type\": \"user\"\n}\n```\n\nWildcards can be used in combination\
    \ with exclusion and inclusion. For\ninstance, `-*,+foo,+bar` will remove all\
    \ elements from the root level and then\nadd in `foo` and `bar`.\n\n\n## URL encoding\n\
    \nBe aware that when using the `+foo.bar` syntax in the query string, that the\n\
    \"+\" must be URL encoded as \"%2B\" and so the URL will be:\n\n```\nhttps://api.bitbucket.org/2.0/repositories/evzijst/interruptingcow?fields=%2Bowner.created_on\n\
    ```\n\nWithout URL escaping, \"+\" is interpreted as an encoded space which will\
    \ not\nmatch any fields.\n\n\n## Field discovery\n\nWhile a resource's `self`\
    \ URL, as well its \"collection\" URL typically return\nthe full object with all\
    \ its fields, there are some exceptions for fields that\nare overly verbose or\
    \ costly to generate.\n\nFor instance, a pull request contains the embedded lists\
    \ of reviewers and\nparticipants. These fields are included from the `self` URL,\
    \ but not from the\n`/pullrequests` collections resource, as it would impact performance\
    \ too much.\n\nTo discover any additional fields that might not be included by\
    \ default,\n`fields=*` can be used.\n\n\n## More examples\n\nIf we want to get\
    \ a list of all reviewer usernames on pull requests I created,\nwe could combine\
    \ a [filter](filtering) with a partial response. This will omit\nall other data\
    \ from the response:\n\n```\n/2.0/repositories/bitbucket/bitbucket/pullrequests?fields=values.id,values.reviewers.username,values.state&q=author.username%3D%22erik%22\n\
    {\n  \"values\": [\n    {\n      \"reviewers\": [\n        {\n          \"username\"\
    : \"abhin\"\n        },\n        {\n          \"username\": \"dtao\"\n       \
    \ },\n        {\n          \"username\": \"csomme\"\n        }\n      ],\n   \
    \   \"state\": \"OPEN\",\n      \"id\": 11355\n    },\n    {\n      \"reviewers\"\
    : [\n        {\n          \"username\": \"csomme\"\n        },\n        {\n  \
    \        \"username\": \"abhin\"\n        },\n        {\n          \"username\"\
    : \"dstevens\"\n        }\n      ],\n      \"state\": \"MERGED\",\n      \"id\"\
    : 11347\n    },\n    {\n      \"reviewers\": [\n        {\n          \"username\"\
    : \"csomme\"\n        },\n        {\n          \"username\": \"jmooring\"\n  \
    \      },\n        {\n          \"username\": \"zdavis\"\n        },\n       \
    \ {\n          \"username\": \"flexbox\"\n        }\n      ],\n      \"state\"\
    : \"OPEN\",\n      \"id\": 11344\n    }\n  ]\n}\n```\n"
  title: "Partial responses"
  description: "Tweak which fields are returned"
  key: "partial-response"
  icon: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB2aWV3Qm94PSIwIDAgMTYyLjQ0ODcgMjEwLjExMTUiPgogIDxkZWZzPgogICAgPHN0eWxlPgogICAgICAuY2xzLTEgewogICAgICAgIGlzb2xhdGlvbjogaXNvbGF0ZTsKICAgICAgfQoKICAgICAgLmNscy0yLCAuY2xzLTYsIC5jbHMtOCB7CiAgICAgICAgZmlsbDogbm9uZTsKICAgICAgfQoKICAgICAgLmNscy0yLCAuY2xzLTggewogICAgICAgIHN0cm9rZTogIzAwNjVmZjsKICAgICAgICBzdHJva2Utd2lkdGg6IDJweDsKICAgICAgfQoKICAgICAgLmNscy0yIHsKI[...]"
- content: "\n# Open API Specification and Object Representations\n\n----\n\n*On this\
    \ page*\n\n* [Open API Specification](#oai)\n* [JSON Schema](#jsonschema)\n* [Condensed\
    \ Versus Full Objects](#representations)\n\n____\n\n\n## Open API Specification\
    \ <a name=\"aoi\"></a>\n\nBitbucket uses the [Open API Specification](https://openapis.org)\
    \ (OAI,\nformerly known as Swagger) to describe its APIs. Our OAI specification\
    \ schema\nis hosted at [https://api.bitbucket.org/swagger.json](https://api.bitbucket.org/swagger.json)\n\
    and serves as the canonical definition and comprehensive declaration of all\n\
    available endpoints.\n\nThe OAI specification makes writing client applications\
    \ easier by:\nauto-generating boilerplate code (like data object classes) and\
    \ dealing with\nauthentication and error handling.\n\nYou can find a comprehensive\
    \ set of open tools for the OAI specification at:\n[https://github.com/swagger-api](https://github.com/swagger-api).\n\
    \n\n## JSON Schema <a name=\"jsonschema\"></a>\n\nBitbucket uses JSON Schema to\
    \ describe the layout of every type of object\nconsumed or produced by the API.\
    \ These schemas are collected under the\n`#definitions` element of our swagger.json\
    \ file.\n\nWhen an endpoint expects an object as part of a POST or PUT, it also\
    \ expects\nthe object to validate against the JSON schemas. The same applies to\
    \ objects\nreturned by an endpoint.\n\n\n## Condensed Versus Full Objects <a name=\"\
    representations\"></a>\n\nMost objects in Bitbucket come both in \"full\" and\
    \ \"partial\" representation.\nThe full representation is when all elements are\
    \ included. This is the layout\nreturned by a resource's `self` location (e.g.\
    \ `/2.0/repositories/foo/bar`),\nas well as resource collection endpoints (e.g.\
    \ `/2.0/repositories`).\n\nHowever, Bitbucket objects often embed other objects.\
    \ For example, a `repository`\nobject embeds a `user` object for its owner. Likewise,\
    \ a `pullrequest` object\nembeds its `repository` object.\n\nThese related objects\
    \ are embedded, or inlined, to reduce the \"chatter\" when\nclients make frequent\
    \ followup API calls to collect information on common,\nrelated information.\n\
    \nEmbedded related objects are typically limited in their fields to avoid such\n\
    object graphs from becoming too deep and noisy. They often exclude their own\n\
    nested objects in an attempt to strike a balance between performance and\nutility.\n\
    \nAn object's embedded or condensed representation tends to be standardized,\n\
    meaning the fields included is the same set, regardless of where the object\n\
    was embedded.\n"
  title: "Schemas and Serialization"
  description: "Learn more about object representations"
  key: "serialization"
  icon: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyMjAuNzYyNCAyMDUuNTg2Ij4KICA8ZGVmcz4KICAgIDxzdHlsZT4KICAgICAgLmNscy0xIHsKICAgICAgICBpc29sYXRpb246IGlzb2xhdGU7CiAgICAgIH0KCiAgICAgIC5jbHMtMiwgLmNscy02IHsKICAgICAgICBtaXgtYmxlbmQtbW9kZTogbXVsdGlwbHk7CiAgICAgIH0KCiAgICAgIC5jbHMtMTMsIC5jbHMtMywgLmNscy00LCAuY2xzLTYgewogICAgICAgIGZpbGw6IG5vbmU7CiAgICAgICAgc3Ryb2tlOiAjYzFjN2QwOwogICAgICAgIHN0cm9rZS1saW5lY2FwOiByb3VuZDsKICAgICAgICBzdHJva2UtbWl0ZXJsa[...]"
- content: "\n# URI, UUID, and structures\n\nYou should be familiar with REST architecture\
    \ before writing an integration. Read this overview page to gain a good understanding\
    \ of Bitbucket's REST implementation.\n\n----\n**On this page**\n\n* [URI structure](#uri-structure)\n\
    * [HTTP methods](#http-methods)\n* [UUID](#uuid)\n    * [User object and UUID](#userobj)\n\
    \    * [Repository object and UUID](#repo-obj)\n    * [Team object and UUID](#teamobj)\n\
    * [Standard error repsponses](#stand-error)\n* [Standard ISO-8601 timestamps](#timestamp)\n\
    \n----\n\n\n## URI structure <a name=\"uri-structure\"></a>\n\nAll Bitbucket Cloud\
    \ requests start with the `https://api.bitbucket.org/2.0` prefix (for the 2.0\
    \ API) and `https://api.bitbucket.org/1.0` prefix (1.0 API).\n\nThe next segment\
    \ of the URI path depends on the endpoint of the request. For example, using the\
    \ curl command and the repositories endpoint you can list all the issues on Bitbucket's\
    \ tutorial repository:\n\n```\ncurl https://api.bitbucket.org/2.0/repositories/tutorials/tutorials.bitbucket.org\n\
    ```\nGiven a specific endpoint, you can then drill down to a particular aspect\
    \ or resource of that endpoint. The issues resource on a repository is an example:\n\
    \n```\ncurl https://api.bitbucket.org/1.0/repositories/tutorials/tutorials.bitbucket.org/issues\n\
    ```\n### HTTP methods <a name=\"http-methods\"></a>\nA given endpoint or resource\
    \ has a series of actions (or methods) associated with it. The Bitbucket service\
    \ supports these standard HTTP methods:\n\n<table class='aui'>\n    <thead>\n\
    \        <tr>\n            <th>Call</th>\n            <th>Description</th>\n \
    \       </tr>\n    </thead>\n    <tr>\n        <td>GET</td>\n        <td>Retrieves\
    \ information.  </td>\n    </tr>\n    <tr>\n        <td>PUT</td>\n        <td>Updates\
    \ existing information.</td>\n    </tr>\n    <tr>\n        <td>POST</td>\n   \
    \     <td>Creates new information.</td>\n    </tr>\n    <tr>\n        <td>DELETE</td>\n\
    \        <td>Removes existing information.</td>\n    </tr>\n</table>\n\nFor example,\
    \ you can call use the POST action on the issues resource and create an issue\
    \ on the issue tracker.\n\n**Specifying content length**\n\nYou can get a `411\
    \ Length Required` response. If this happens, the API requires a Content-Length\
    \ header but the client is not sending it. You should add the header yourself,\
    \ for example using the curl client:\n\n```\ncurl -r PUT --header \"Content-Length:\
    \ 0\" -u user:pass https://api.bitbucket.org/1.0/emails/rap@atlassian.com\n```\n\
    ## Universally Unique Identifier <a name=\"uuid\"></a>\n\nUUID's provide a single\
    \ point of recognition for users, teams, and repositories. The UUID is distinct\
    \ from the username, team name, and repository name fields and remains the same\
    \ even when those fields change. For example when a user changes their username\
    \ or moves a repository you will need to modify calls which use those identifiers\
    \ but not if you are pointing to the UUID.\n\n### UUID examples and structure\n\
    \nUUID's work with both the 1.0 and 2.0 APIs for the user, team, and repository\
    \ objects. The following examples the following characters are replacements for\
    \ curly brackets: `%7B` replaces `{`  and `%7D` replaces `}`. You will see this\
    \ structure in the following example sections.\n\n### User object and UUID <a\
    \ name=\"userobj\"></a>\n\nWhen you make a call using either the username or the\
    \ UUID for that user the response is the same.\n\n**Call with username**:\n\n\
    ```\ncurl https://api.bitbucket.org/2.0/users/tutorials\n```\n\n***Call with UUID\
    \ for the user**:\n\n```\ncurl https://api.bitbucket.org/2.0/users/%7Bc788b2da-b7a2-404c-9e26-d3f077557007%7D\n\
    ```\n\n**Response**\n```JSON\n{\n    \"username\": \"tutorials\",\n    \"website\"\
    : \"https://tutorials.bitbucket.org/\",\n    \"display_name\": \"tutorials account\"\
    ,\n    \"uuid\": \"{c788b2da-b7a2-404c-9e26-d3f077557007}\",\n    \"links\": {\n\
    \        \"self\": {\n            \"href\": \"https://api.bitbucket.org/2.0/users/tutorials\"\
    \n        },\n        \"repositories\": {\n            \"href\": \"https://api.bitbucket.org/2.0/repositories/tutorials\"\
    \n        },\n        \"html\": {\n            \"href\": \"https://bitbucket.org/tutorials\"\
    \n        },\n        \"followers\": {\n            \"href\": \"https://api.bitbucket.org/2.0/users/tutorials/followers\"\
    \n        },\n        \"avatar\": {\n            \"href\": \"https://bitbucket-assetroot.s3.amazonaws.com/c/photos/2013/Nov/25/tutorials-avatar-1563784409-6_avatar.png\"\
    \n        },\n        \"following\": {\n            \"href\": \"https://api.bitbucket.org/2.0/users/tutorials/following\"\
    \n        }\n    },\n    \"created_on\": \"2011-12-20T16:34:07.132459+00:00\"\
    ,\n    \"location\": \"Santa Monica, CA\",\n    \"type\": \"user\"\n}\n```\n\n\
    ### Repository object and UUID <a name=\"repo-obj\"></a>\n\nOnce you have the\
    \ UUID for a repository you no longer need a username or team name to make the\
    \ API call so long as you use an empty field. This helps you resolve repositories\
    \ no matter if the username or team name changes.\n\n**Call with team name (1team)\
    \ and repository name (moxie)**:\n\n```\ncurl https://api.bitbucket.org/2.0/repositories/1team/moxie\n\
    ```\n**Call with UUID and empty field**:\n\n```\ncurl https://api.bitbucket.org/2.0/repositories/%7B%7D/%7B21fa9bf8-b5b2-4891-97ed-d590bad0f871%7D\n\
    ```\n\n**Call with UUID and teamname**:\n\n```\ncurl https://api.bitbucket.org/2.0/repositories/1team/%7B21fa9bf8-b5b2-4891-97ed-d590bad0f871%7D\n\
    ```\n\n**Response**\n\n```JSON\n{\n    \"created_on\": \"2013-11-08T01:11:03.222520+00:00\"\
    ,\n    \"description\": \"\",\n    \"fork_policy\": \"allow_forks\",\n    \"full_name\"\
    : \"1team/moxie\",\n    \"has_issues\": false,\n    \"has_wiki\": false,\n   \
    \ \"is_private\": false,\n    \"language\": \"\",\n    \"links\": {\n        \"\
    avatar\": {\n            \"href\": \"https://bitbucket.org/1team/moxie/avatar/32/\"\
    \n        },\n        \"branches\": {\n            \"href\": \"https://api.bitbucket.org/2.0/repositories/1team/moxie/refs/branches\"\
    \n        },\n        \"clone\": [\n            {\n                \"href\": \"\
    https://bitbucket.org/1team/moxie.git\",\n                \"name\": \"https\"\n\
    \            },\n            {\n                \"href\": \"ssh://git@bitbucket.org/1team/moxie.git\"\
    ,\n                \"name\": \"ssh\"\n            }\n        ],\n        \"commits\"\
    : {\n            \"href\": \"https://api.bitbucket.org/2.0/repositories/1team/moxie/commits\"\
    \n        },\n        \"downloads\": {\n            \"href\": \"https://api.bitbucket.org/2.0/repositories/1team/moxie/downloads\"\
    \n        },\n        \"forks\": {\n            \"href\": \"https://api.bitbucket.org/2.0/repositories/1team/moxie/forks\"\
    \n        },\n        \"hooks\": {\n            \"href\": \"https://api.bitbucket.org/2.0/repositories/1team/moxie/hooks\"\
    \n        },\n        \"html\": {\n            \"href\": \"https://bitbucket.org/1team/moxie\"\
    \n        },\n        \"pullrequests\": {\n            \"href\": \"https://api.bitbucket.org/2.0/repositories/1team/moxie/pullrequests\"\
    \n        },\n        \"self\": {\n            \"href\": \"https://api.bitbucket.org/2.0/repositories/1team/moxie\"\
    \n        },\n        \"tags\": {\n            \"href\": \"https://api.bitbucket.org/2.0/repositories/1team/moxie/refs/tags\"\
    \n        },\n        \"watchers\": {\n            \"href\": \"https://api.bitbucket.org/2.0/repositories/1team/moxie/watchers\"\
    \n        }\n    },\n    \"name\": \"moxie\",\n    \"owner\": {\n        \"display_name\"\
    : \"the team\",\n        \"links\": {\n            \"avatar\": {\n           \
    \     \"href\": \"https://bitbucket.org/account/1team/avatar/32/\"\n         \
    \   },\n            \"html\": {\n                \"href\": \"https://bitbucket.org/1team/\"\
    \n            },\n            \"self\": {\n                \"href\": \"https://api.bitbucket.org/2.0/teams/1team\"\
    \n            }\n        },\n        \"type\": \"team\",\n        \"username\"\
    : \"1team\",\n        \"uuid\": \"{aa559944-83c9-4963-a9a8-69ac8d9cf5d2}\"\n \
    \   },\n    \"project\": {\n        \"key\": \"PROJ\",\n        \"links\": {\n\
    \            \"avatar\": {\n                \"href\": \"https://bitbucket.org/account/user/1team/projects/PROJ/avatar/32\"\
    \n            },\n            \"html\": {\n                \"href\": \"https://bitbucket.org/account/user/1team/projects/PROJ\"\
    \n            }\n        },\n        \"name\": \"Untitled project\",\n       \
    \ \"type\": \"project\",\n        \"uuid\": \"{ab52aaeb-16ad-4fb0-bb1d-47e4f00367ff}\"\
    \n    },\n    \"scm\": \"git\",\n    \"size\": 33348,\n    \"type\": \"repository\"\
    ,\n    \"updated_on\": \"2013-11-08T01:11:03.263237+00:00\",\n    \"uuid\": \"\
    {21fa9bf8-b5b2-4891-97ed-d590bad0f871}\",\n    \"website\": \"\"\n}\n```\n\n###\
    \ Team object and UUID <a name=\"teamobj\"></a>\n\nThis example shows a call for\
    \ a list of team members using both the team name and with the UUID for the team\
    \ object. As the call is unauthenticated in the following example the response\
    \ object will only show members with public profiles. The response is the same\
    \ in either case.\n\n**Call with teamname**\n\n```\ncurl https://api.bitbucket.org/2.0/teams/1team/members\n\
    ```\n**Call with UUID for team object**\n\n```\ncurl https://api.bitbucket.org/2.0/teams/%7Baa559944-83c9-4963-a9a8-69ac8d9cf5d2%7D/members\n\
    ```\n\n**Response**\n\n```JSON\n{\n    \"page\": 1,\n    \"pagelen\": 50,\n  \
    \  \"size\": 2,\n    \"values\": [\n        {\n            \"created_on\": \"\
    2011-12-20T16:34:07.132459+00:00\",\n            \"display_name\": \"tutorials\
    \ account\",\n            \"links\": {\n                \"avatar\": {\n      \
    \              \"href\": \"https://bitbucket.org/account/tutorials/avatar/32/\"\
    \n                },\n                \"followers\": {\n                    \"\
    href\": \"https://api.bitbucket.org/2.0/users/tutorials/followers\"\n        \
    \        },\n                \"following\": {\n                    \"href\": \"\
    https://api.bitbucket.org/2.0/users/tutorials/following\"\n                },\n\
    \                \"hooks\": {\n                    \"href\": \"https://api.bitbucket.org/2.0/users/tutorials/hooks\"\
    \n                },\n                \"html\": {\n                    \"href\"\
    : \"https://bitbucket.org/tutorials/\"\n                },\n                \"\
    repositories\": {\n                    \"href\": \"https://api.bitbucket.org/2.0/repositories/tutorials\"\
    \n                },\n                \"self\": {\n                    \"href\"\
    : \"https://api.bitbucket.org/2.0/users/tutorials\"\n                },\n    \
    \            \"snippets\": {\n                    \"href\": \"https://api.bitbucket.org/2.0/snippets/tutorials\"\
    \n                }\n            },\n            \"location\": null,\n       \
    \     \"type\": \"user\",\n            \"username\": \"tutorials\",\n        \
    \    \"uuid\": \"{c788b2da-b7a2-404c-9e26-d3f077557007}\",\n            \"website\"\
    : \"https://tutorials.bitbucket.org/\"\n        },\n        {\n            \"\
    created_on\": \"2013-12-10T14:44:13+00:00\",\n            \"display_name\": \"\
    Dan Stevens [Atlassian]\",\n            \"links\": {\n                \"avatar\"\
    : {\n                    \"href\": \"https://bitbucket.org/account/dans9190/avatar/32/\"\
    \n                },\n                \"followers\": {\n                    \"\
    href\": \"https://api.bitbucket.org/2.0/users/dans9190/followers\"\n         \
    \       },\n                \"following\": {\n                    \"href\": \"\
    https://api.bitbucket.org/2.0/users/dans9190/following\"\n                },\n\
    \                \"hooks\": {\n                    \"href\": \"https://api.bitbucket.org/2.0/users/dans9190/hooks\"\
    \n                },\n                \"html\": {\n                    \"href\"\
    : \"https://bitbucket.org/dans9190/\"\n                },\n                \"\
    repositories\": {\n                    \"href\": \"https://api.bitbucket.org/2.0/repositories/dans9190\"\
    \n                },\n                \"self\": {\n                    \"href\"\
    : \"https://api.bitbucket.org/2.0/users/dans9190\"\n                },\n     \
    \           \"snippets\": {\n                    \"href\": \"https://api.bitbucket.org/2.0/snippets/dans9190\"\
    \n                }\n            },\n            \"location\": null,\n       \
    \     \"type\": \"user\",\n            \"username\": \"dans9190\",\n         \
    \   \"uuid\": \"{1cd06601-cd0e-4fce-be03-e9ac226978b7}\",\n            \"website\"\
    : \"\"\n        }\n    ]\n}\n```\n\n## Standardized error responses <a name=\"\
    stand-error\"></a>\n\nThe 2.0 API standardizes the error response layout. The\
    \ 2.0 API serves a JSON\nobject along with the appropriate HTTP status code. The\
[...]
