// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"reflect"
	"github.com/petergtz/pegomock"
	url "net/url"
)

func AnyUrlURL() url.URL {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(url.URL))(nil)).Elem()))
	var nullValue url.URL
	return nullValue
}

func EqUrlURL(value url.URL) url.URL {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue url.URL
	return nullValue
}
