apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  creationTimestamp: null
  name: default-image-from-pod-templates
spec:
  steps:
  - args:
    - mvn
    - test
    image: jenkinsxio/builder-maven:0.0.408
    name: run-tests
    resources: {}
status:
  stepsCompleted: null
