apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  creationTimestamp: null
  labels:
    branch: master
    build: "1"
    jenkins.io/pipelineType: build
    owner: abayer
    repository: golang-qs-test
  name: abayer-golang-qs-test-master-dfq8f-1
spec:
  params:
  - name: version
    value: 0.0.1
  pipelineRef:
    apiVersion: tekton.dev/v1alpha1
    name: abayer-golang-qs-test-master-dfq8f-1
  podTemplate: {}
  resources:
  - name: abayer-golang-qs-test-master-dfq8f
    resourceRef:
      apiVersion: tekton.dev/v1alpha1
      name: abayer-golang-qs-test-master-dfq8f
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
