metadata:
  creationTimestamp: null
  labels:
    branch: master
    build: "1"
    jenkins.io/pipelineType: build
    owner: abayer
    repository: golang-qs-test
  name: abayer-golang-qs-test-master-dfq8f-1
pipelineRef: null
pipelineRunRef: null
stages:
- depth: 0
  name: from-build-pack
  taskRef: abayer-golang-qs-test-master-dfq8f-from-build-pack-1
