// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	auth "github.com/jenkins-x/jx/pkg/auth"
	"github.com/petergtz/pegomock"
	"reflect"
)

func AnyAuthAuthConfigService() auth.AuthConfigService {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(auth.AuthConfigService))(nil)).Elem()))
	var nullValue auth.AuthConfigService
	return nullValue
}

func EqAuthAuthConfigService(value auth.AuthConfigService) auth.AuthConfigService {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue auth.AuthConfigService
	return nullValue
}
