// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	gits "github.com/jenkins-x/jx/pkg/gits"
	"github.com/petergtz/pegomock"
	"reflect"
)

func AnyGitsGitter() gits.Gitter {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(gits.Gitter))(nil)).Elem()))
	var nullValue gits.Gitter
	return nullValue
}

func EqGitsGitter(value gits.Gitter) gits.Gitter {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue gits.Gitter
	return nullValue
}
