// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	golang_jenkins "github.com/jenkins-x/golang-jenkins"
	"github.com/petergtz/pegomock"
	"reflect"
)

func AnyGolangJenkinsJenkinsClient() golang_jenkins.JenkinsClient {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(golang_jenkins.JenkinsClient))(nil)).Elem()))
	var nullValue golang_jenkins.JenkinsClient
	return nullValue
}

func EqGolangJenkinsJenkinsClient(value golang_jenkins.JenkinsClient) golang_jenkins.JenkinsClient {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue golang_jenkins.JenkinsClient
	return nullValue
}
