// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"github.com/petergtz/pegomock"
	versioned0 "k8s.io/metrics/pkg/client/clientset/versioned"
	"reflect"
)

func AnyPtrToVersioned0Clientset() *versioned0.Clientset {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(*versioned0.Clientset))(nil)).Elem()))
	var nullValue *versioned0.Clientset
	return nullValue
}

func EqPtrToVersioned0Clientset(value *versioned0.Clientset) *versioned0.Clientset {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue *versioned0.Clientset
	return nullValue
}
