// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"reflect"
	"github.com/petergtz/pegomock"
	rest "k8s.io/client-go/rest"
)

func AnyPtrToRestConfig() *rest.Config {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(*rest.Config))(nil)).Elem()))
	var nullValue *rest.Config
	return nullValue
}

func EqPtrToRestConfig(value *rest.Config) *rest.Config {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue *rest.Config
	return nullValue
}
