// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"reflect"
	"github.com/petergtz/pegomock"
	versioned "k8s.io/metrics/pkg/client/clientset/versioned"
)

func AnyPtrToVersionedClientset() *versioned.Clientset {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(*versioned.Clientset))(nil)).Elem()))
	var nullValue *versioned.Clientset
	return nullValue
}

func EqPtrToVersionedClientset(value *versioned.Clientset) *versioned.Clientset {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue *versioned.Clientset
	return nullValue
}
