// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"reflect"
	"github.com/petergtz/pegomock"
	auth "github.com/jenkins-x/jx/pkg/auth"
)

func AnyPtrToAuthAuthConfig() *auth.AuthConfig {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(*auth.AuthConfig))(nil)).Elem()))
	var nullValue *auth.AuthConfig
	return nullValue
}

func EqPtrToAuthAuthConfig(value *auth.AuthConfig) *auth.AuthConfig {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue *auth.AuthConfig
	return nullValue
}
