// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"reflect"
	"github.com/petergtz/pegomock"
	golang_jenkins "github.com/jenkins-x/golang-jenkins"
)

func AnyPtrToGolangJenkinsJenkins() *golang_jenkins.Jenkins {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(*golang_jenkins.Jenkins))(nil)).Elem()))
	var nullValue *golang_jenkins.Jenkins
	return nullValue
}

func EqPtrToGolangJenkinsJenkins(value *golang_jenkins.Jenkins) *golang_jenkins.Jenkins {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue *golang_jenkins.Jenkins
	return nullValue
}
