// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	vault "github.com/jenkins-x/jx/pkg/vault"
	"github.com/petergtz/pegomock"
	"reflect"
)

func AnyVaultClient() vault.Client {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(vault.Client))(nil)).Elem()))
	var nullValue vault.Client
	return nullValue
}

func EqVaultClient(value vault.Client) vault.Client {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue vault.Client
	return nullValue
}
