// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/jenkins-x/jx/pkg/apis/jenkins.io/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ComplianceCheckLister helps list ComplianceChecks.
type ComplianceCheckLister interface {
	// List lists all ComplianceChecks in the indexer.
	List(selector labels.Selector) (ret []*v1.ComplianceCheck, err error)
	// ComplianceChecks returns an object that can list and get ComplianceChecks.
	ComplianceChecks(namespace string) ComplianceCheckNamespaceLister
	ComplianceCheckListerExpansion
}

// complianceCheckLister implements the ComplianceCheckLister interface.
type complianceCheckLister struct {
	indexer cache.Indexer
}

// NewComplianceCheckLister returns a new ComplianceCheckLister.
func NewComplianceCheckLister(indexer cache.Indexer) ComplianceCheckLister {
	return &complianceCheckLister{indexer: indexer}
}

// List lists all ComplianceChecks in the indexer.
func (s *complianceCheckLister) List(selector labels.Selector) (ret []*v1.ComplianceCheck, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.ComplianceCheck))
	})
	return ret, err
}

// ComplianceChecks returns an object that can list and get ComplianceChecks.
func (s *complianceCheckLister) ComplianceChecks(namespace string) ComplianceCheckNamespaceLister {
	return complianceCheckNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// ComplianceCheckNamespaceLister helps list and get ComplianceChecks.
type ComplianceCheckNamespaceLister interface {
	// List lists all ComplianceChecks in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1.ComplianceCheck, err error)
	// Get retrieves the ComplianceCheck from the indexer for a given namespace and name.
	Get(name string) (*v1.ComplianceCheck, error)
	ComplianceCheckNamespaceListerExpansion
}

// complianceCheckNamespaceLister implements the ComplianceCheckNamespaceLister
// interface.
type complianceCheckNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all ComplianceChecks in the indexer for a given namespace.
func (s complianceCheckNamespaceLister) List(selector labels.Selector) (ret []*v1.ComplianceCheck, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.ComplianceCheck))
	})
	return ret, err
}

// Get retrieves the ComplianceCheck from the indexer for a given namespace and name.
func (s complianceCheckNamespaceLister) Get(name string) (*v1.ComplianceCheck, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("compliancecheck"), name)
	}
	return obj.(*v1.ComplianceCheck), nil
}
