// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	gits "github.com/jenkins-x/jx/pkg/gits"
	"github.com/petergtz/pegomock"
	"reflect"
)

func AnyPtrToGitsGitRelease() *gits.GitRelease {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(*gits.GitRelease))(nil)).Elem()))
	var nullValue *gits.GitRelease
	return nullValue
}

func EqPtrToGitsGitRelease(value *gits.GitRelease) *gits.GitRelease {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue *gits.GitRelease
	return nullValue
}
