// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	auth "github.com/jenkins-x/jx/pkg/auth"
	"github.com/petergtz/pegomock"
	"reflect"
)

func AnyPtrToAuthAuthServer() *auth.AuthServer {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(*auth.AuthServer))(nil)).Elem()))
	var nullValue *auth.AuthServer
	return nullValue
}

func EqPtrToAuthAuthServer(value *auth.AuthServer) *auth.AuthServer {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue *auth.AuthServer
	return nullValue
}
