// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"reflect"

	gits "github.com/jenkins-x/jx/v2/pkg/gits"
	"github.com/petergtz/pegomock"
)

func AnyPtrToGitsListCommitsArguments() *gits.ListCommitsArguments {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(*gits.ListCommitsArguments))(nil)).Elem()))
	var nullValue *gits.ListCommitsArguments
	return nullValue
}

func EqPtrToGitsListCommitsArguments(value *gits.ListCommitsArguments) *gits.ListCommitsArguments {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue *gits.ListCommitsArguments
	return nullValue
}
