// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	gits "github.com/jenkins-x/jx/pkg/gits"
	"github.com/petergtz/pegomock"
	"reflect"
)

func AnyPtrToGitsGitUser() *gits.GitUser {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(*gits.GitUser))(nil)).Elem()))
	var nullValue *gits.GitUser
	return nullValue
}

func EqPtrToGitsGitUser(value *gits.GitUser) *gits.GitUser {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue *gits.GitUser
	return nullValue
}
