// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"reflect"
	"github.com/petergtz/pegomock"
	github "github.com/google/go-github/github"
)

func AnySliceOfPtrToGithubRepositoryInvitation() []*github.RepositoryInvitation {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*([]*github.RepositoryInvitation))(nil)).Elem()))
	var nullValue []*github.RepositoryInvitation
	return nullValue
}

func EqSliceOfPtrToGithubRepositoryInvitation(value []*github.RepositoryInvitation) []*github.RepositoryInvitation {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue []*github.RepositoryInvitation
	return nullValue
}
