// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"github.com/petergtz/pegomock"
	"reflect"
	time "time"
)

func AnyTimeTime() time.Time {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(time.Time))(nil)).Elem()))
	var nullValue time.Time
	return nullValue
}

func EqTimeTime(value time.Time) time.Time {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue time.Time
	return nullValue
}
